### ISSUE TITLE
EP 930s | Establish EP 930s via Caseflow Intake

### ISSUE THREAD

**Issue by nicholasholtz** [department-of-veterans-affairs/caseflow#10009]
## Background
VBA uses 930EPs to track corrections needed to decisions that were previously processed and cleared under their primary EP. 

For instance, a 030 EP Higher Level Review EP was cleared and it is found that there was an error on the decision, such as not all claimed issues decided. The station would then establish a 930EP series in order to correct the decision from the 030EP claim.

AMO is currently considering adding new 930EP claim labels so that we can track other metrics from these decisions.

## Chunks of work
1. Accidentally cleared EPs
1. Missed contentions (different than missing ratings in CorpDB)
1. Incorrect decisions

## 1, 2. Proposed MVP flow for accidentally cleared EPs + missed contentions
Note: what is the difference btw closed and cleared and cancelled?
- cleared = should be decided, waiting for decision issues on the request issues. if they accidentally clear them, the request issues don't get decisions
- cancelled = it never happened. they don't get credit for cancelled claims so they can re-intake those

1. User searches for the case in Caseflow 

1. User navigates to Add/Remove issues page - #11195 
   - change the navigation, change error message/remove it

1. Add/Remove issues page contains all of the request issues from the closed EP - #11385
   - populate all request issues from former EP, **but do not allow users to update the contention text, withdraw, or remove them** 
   - add the option "Correct", which adds a new request issue that's connected to that incorrect request issue
   - the new 930 EP would contain request issues that were "corrected" or "added"

1. User can also add/remove issues - #11386
   - users can add/remove issues if they need to, which will go onto a 930
   - the new 930 EP would contain request issues that were "corrected" or "added"

1. When user clicks Establish EP, a modal or in-line edit explains that they are creating a 930 EP in VBMS and they can make further corrections in VBMS - https://github.com/department-of-veterans-affairs/caseflow/issues/11387
   - add modal or inline edit

1. Establish 930 EP and connect to closed 040 or 030, attach correct label - https://github.com/department-of-veterans-affairs/caseflow/issues/11191
   - connection between 930 and SC or HLR EP happens naturally via the end product establishments table - we need it at the Caseflow level for MVP
   - create the mapping btw SC and HLR EP codes and the 930 EP codes, spreadsheet above

1. Replace original SC or HLR EP decision issues from the resulting 930 EP
   - TO DO

## Questions
- Can 930 EPs be perpetually created? Yes

## Resources
Jane Chi provided this spreadsheet of 930s on 6/14/2019: 
[AMA 930 Labels.xlsx](https://github.com/department-of-veterans-affairs/caseflow/files/3292113/AMA.930.Labels.xlsx)

## Older resources
Lauren Sylvia from AMO provided this list of claim labels for 930s:
In support of implementing the ability for 930s to be established in Caseflow:

The claim labels below meet the need of what AMO is looking for, but we need to ensure that Caseflow can support establishing the 930s with them. 
 
AMA HLR Rating Control
AMA PMC HLR Rating Control
AMA Supp Rating Control
AMA PMC Supp Rating Control
AMA HLR Non-Rating Control
AMA PMC HLR Non-Rating Control
AMA Supp Non-Rating Control
AMA PMC Supp Non-Rating Control
AMA HLR Correction of Rating LQE
AMA PMC HLR Correction of Rating LQE
AMA HLR Correction of Non-Rating LQE
AMA PMC HLR Correction of Non-Rating LQE
AMA Supp Correction of Rating LQE
AMA PMC Supp Correction of Rating LQE
AMA Supp Correction of Non-Rating LQE
AMA PMC Supp Correction of Non-Rating LQE
AMA HLR Correction of Rating NQE
AMA PMC HLR Correction of Rating NQE
AMA HLR Correction of Non-Rating NQE
AMA PMC HLR Correction of Non-Rating NQE
AMA Supp Correction of Rating NQE
AMA PMC Supp Correction of Rating NQE
AMA Supp Correction of Non-Rating NQE
AMA PMC Supp Correction of Non-Rating NQE
AMA Remand Rating Control
AMA PMC Remand Rating Control
AMA Remand Non-Rating Control
AMA PMC Remand Non-Rating Control
AMA Remand Rating Correction of NQE
AMA PMC Remand Rating Correction of LQE
AMA Remand Non-Rating Correction of LQE
AMA PMC Remand Non-Rating Correction of LQE
AMA Remand Rating Correction of NQE
AMA PMC Remand Rating Correction of NQE
AMA Remand Non-Rating Correction of NQE
AMA PMC Remand Non-Rating Correction of NQE
AMA BVA Grant Rating Control
AMA PMC BVA Grant Rating Control
AMA BVA Grant Non-Rating Control
AMA PMC BVA Grant Non-Rating Control
AMA BVA Grant Rating Correction of LQE
AMA PMC BVA Grant Rating Correction of LQE
AMA BVA Grant Non-Rating Correction of LQE
AMA PMC BVA Grant Non-Rating Correction of LQE
AMA BVA Grant Rating Correction of NQE
AMA PMC BVA Grant Rating Correction of NQE
AMA BVA Grant Non-Rating Correction of NQE
AMA PMC BVA Grant Non-Rating Correction of NQE
AMA HLR DTA Error Non-Rating
AMA HLR DTA Error Rating
AMA Board DTA Error Non-Rating
AMA Board DTA Error Rating
AMA HLR DTA Error NR – Correction of LQE
AMA HLR DTA Error Rating – Correction of LQE
AMA Board DTA Error NR – Correction of LQE
AMA Board DTA Error Rating – Correction of LQE
AMA HLR DTA Error NR – Correction of NQE
AMA HLR DTA Error Rating – Correction of NQE
AMA Board DTA Error NR – Correction of NQE
AMA Board DTA Error Rating – Correction of NQE

### Scenario: a user identified a decision was incorrectly made, for example, they granted an issue instead of denying it.

1. Search in Caseflow (development complete)
    **- Enhancement requested: Show receipt date for the claim in search results** #11835 
1. Click link and navigate to Edit issues page (development complete)
1. Click Add issue
1. **Add issue screen shows view the previous decision's ratings - they are now "request issues" (engineering work)** #11836 
      - **Change logic to allow all decisions that are related to this claim to show as options to add to the 930**
      - **Change validation for these issues, so they can be added on a regular, originally in-taken claim as well**
1. User can add the issue that needs new decision (development complete)
1. If missed issues as well as an incorrect decision, user can add missed issues (development complete)
1. Establish the 930 (development complete)

## 3. Correcting incorrect decisions via EP 930s (Part 2: incorrect decisions)

Scenario: a user identified a decision was incorrectly made. For example, they DTA'd an issue instead of denying it. The DTA Supplemental Claim EP was not finalized and decided.
1. Same as above
1. **Ensure DTA supplemental claim EPs that have been accidentally cleared can be edited via 930s** #11837 
1. **When EP 930 was established, remove the incorrectly added issue from the DTA supplemental claim** #11838

**Comment by shanear** [comment]
I feel like we probably want to be doing requirements stuff in appeals-design-research or some other non open source repo.

**Comment by shanear** [comment]
Also, this is a dup of https://github.com/department-of-veterans-affairs/appeals-design-research/issues/962

**Comment by laurjpeterson** [comment]
Open questions
- What mistakes do users most commonly make?
- What data fields need to be corrected?
   - **contention dispositions?** YES
   - EP code?
   - form type?
   - benefit type?
   - claimant?
   - user?
   - station?
   - other fields?
- Assume it's just editing contention dispositions, do they want to start with all issues?
- Confirm who the users are? Veteran Service Representatives (VSRs), Claims Assistants (CAs)?
- How should we connect the EP correction to the next issue that could be appealed (previous VA decisions)? How might the correction live in the EP chain? Should we delete the originally appealed issue with the incorrect decision from the chain?
- Should this flow be started in VBMS or Caseflow?
- Issue has been decided but has already been intaken again. Should that EP be able to be corrected? (LP's gut is no) Is there a time frame where closed EPs can be corrected?

Notes:
- VBMS folks know the most about 930 EPs. Either they're done with development on the VBMS side and can receive 930s or they aren't
- VBMS - next release in a few weeks
- June/mid-June to test functionality for EP 930s
	- thurs for BGS, VBMS
- Mike Palmer
- For just 030 claim or 040 claim - I accidentally close it. Needs to be reopened. You can’t open the 030 or 040 because of double credit. So they need to open the 930. 
	- 930s are a weird thing. Only done so a user doesn’t receive second credit for work
	- a claim would need to come through Caseflow to know if it’s completed
	- if we created the 930 in VBMS, might not work
	- can’t create a claim in VBMS

Other ideas:
- Button to "correct EP"
   - use the same issues from the former EP
- Could we use the same "Edit in Caseflow" button that's in VBMS today?

Next steps:
- [ ] Ask Jane to find a user to ask these questions to and shadow a user that is creating 930 EPs to make corrections - @laurjpeterson 
- [ ] Email some of our questions to Mike, Jane, cc: Nate to verify some requirements - @laurjpeterson 
- [ ] Creating a research plan for 930 EPs - @carolaponce 
- [ ] Ask for the full EP codes (930 followed by some text) and the modifiers - @leikkisa
- [ ] Figure out how VBMS wants the 930 connection to the original claim EPs. Should this be in Caseflow or VBMS? - @leikkisa

**Comment by carolaponce** [comment]
https://github.com/department-of-veterans-affairs/appeals-design-research/issues/962#issuecomment-442667194

**Comment by carolaponce** [comment]
@laurjpeterson and all.  As I'm preparing to talk to users, I have drafted a few questions.  Feel free to provide any feedback you have. I'm trying to understand the process better.

-  How do users create a 930EP? 
What does that process look like? (This questions will most likely be answered when talking to users)
 
-  About the note - _What are examples of “other metrics” for decisions that can be captured with Corrective EPs?_
Will there be a way to capture any needed metrics from decisions that are made and/or corrected under the 930EP series? 

- Would the 930EP need to be created through the intake tool in order to capture needed data for the contentions?

- How do users find the 930 EP in VBMS after it's created?

- _Can 930 EPs be perpetually created? Yes_ 
 ^What does this mean exactly? Is there any time sensitivity with creating correction files.

- Can we propose a better process? or an in-product solution?

**Comment by laurjpeterson** [comment]
Emailed Jane 5/2.

@carolaponce - your questions look great! a few comments below. 

> Will there be a way to capture any needed metrics from decisions that are made and/or corrected under the 930EP series?
- I think this is a good question for Nate, Jane, or Mike, but not for users. It may also be a question for VBA's reporting team, PA&I.

> Would the 930EP need to be created through the intake tool in order to capture needed data for the contentions?
- I like this question, and I think it's something that we would suggest after digging a bit further into this. Based on how users create EP 930s today, and the flow of how they'd do it for HLRs and SCs, we'd want to propose whether to start in Caseflow or start in VBMS.

> Can 930 EPs be perpetually created? Yes
> ^What does this mean exactly? Is there any time sensitivity with creating correction files.
- This is trying to convey that users could create a 930 EP to create an 030 or 040 EP. If they made a mistake on that 930 EP, though, they'd create another 930 EP to correct it. And so on.

**Comment by laurjpeterson** [comment]
[slack thread](https://dsva.slack.com/archives/CFBLH2LR4/p1557239225074700) where VBMS answers a few questions

**Comment by leikkisa** [comment]
Adding a comment about being able to edit whether a Veteran opted in their legacy issues.  It seems like an important field to be able to correct, probably for 930s and also in edit generally.

https://dsva.slack.com/archives/CA1QBDLEL/p1559656638001000

**Comment by laurjpeterson** [comment]
## 6/12: Observing VBA employees creating EP930s and a CA intaking a claim 

## Goals
- see how claims assistants/VSRs work EPs *post-intake* so we can map our understanding of how issues/contentions, etc. flow from caseflow into VBMS
- see the 930 EP creation flow

## Interview guide
- LP: intros and roles
- LP: explain the goals of our meeting
- Opening questions for Claims Assistants:
   - How would you describe your role? What are your major responsibilities?
- Post-intake
   - Can you show us how you receive a supplemental claim or higher level reveiw that was establishd by Caseflow Intake? 
   - What happens next?
   - What data do you find the most important?
- EP 930s
   - Tell us about the most recent time you created an EP 930. 
   - In what other circumstances do you create EP 930s?
   - Walk us through the process in VBMS

**Comment by laurjpeterson** [comment]
# 6/12 - interview with VBA
Tim Denley - supervisor for the Intake team in DROC 
Lauren Sylvia - program admin within AMO
Jane Chi - AMO operations, Caseflow liaision
Dayna - AMO operations, Caseflow liaison backup
Liz - CA for DROC, one demo
Marc Mullin - Intake analyst for DROC Seattle
	* assigning work, reviewing, QR, working through bugs
Sheila - VSR at Seattle DROC, demo
Lynn - program admin chief
Gary Vogel - Sea-Tac DROC IPC coach


* See how claims assistants/VSRs work EPs/post-intake/so we can map our understanding of how issues/contentions, etc. flow from caseflow into VBMS
* see the 930 EP creation flow
* curious about what you can do with respect to editing claims outside of Caseflow 
	* can you remove a contention?
	* can clear and cancel EPs so want to see what else

## Claims assistant (Liz)

### Role/responsibilities
* review mail, everything in the packet, all forms
* Is there any pending claim, any duplicate, any legacy?
	* Veterans send multiple apps for the same issues
* notification letter to see what they’re eligible for
* process is established through VBMS 
	* 0996 - EP 030 - HLR
	* 0995 - EP 040 - SC
		* reconsideration of a claim that was previously denied
* Centralized Mail Portal - review packet
	* go to VBMS - validate that it can be intaken
	* might update address or 
* then Caseflow Intake and establish the claim
* In the meantime, manage evidence on other screen 
	* long loading time**

* claims assistants work off 3 screens

### Intaking the SC
* “claims” tab 
	* saw the 040
* contention title ok
	* would use notification letter to clarify the issue

* sometimes have duplicate mail - St. Pete will work it before us

### Intaking the HLR 
* verify address
* verify phone number
* Different names: Sergio DeLeon (in VBMS) vs. Sergio DeLeon Jr. (on the form)
	* verify name in SHARE
	* edit name in Mail Portal index 
		* issue - if caseflow doesn’t have the name as it appears in VBMS, document won’t upload

* “we dream of a little calendar” LOL

#### SSOC opt-in note
* people who have never been in legacy will check the opt-in
* people who need to check it do check it

## VSR (Sheila)
* pre-deveopment VSR
* one of the first people to get the EP after Liz
* 1st thing to do?
* Working on 3 screens
	* 3 VBMS screens open: profile, claim, documents page
* She works under Liz in Mail Portal as well - detailed to also working mail portal, caseflow intake

### Working an SC
* Note: SCs have an evidence requirement, but no date requirement
* *Arrives with the caution sign*, not ready because missing classification under the contention - first indication that no one else touched this
* *add the classification* - group issues together, but we don’t use this data as VSRs
* *Pull up forms for this*
	* Look at the decision date - to see if there is additional evidence that she needs to look at
	* Evidence will move forward - based on the new evidence, will evaluate for development actions
* Please allow us to edit what comes in as a contention - want to pull out the words that we want: shortened title, etc. 
	* where we import this contention into various forms and documents
	* this entire sentence comes in, which is hard
	* goes in our exams, confuses the doctors
		* risk: so many exam clarifications - practically unreadable
* can delete contentions in VBMS
	* but told she can’t delete the contentions
	* but then we just popped it out of Caseflow 
	* using Caseflow for AMA metrics
* can add more contentions in VBMS 
	* would be helpful if limited to doing only appropriate movement
	* shouldn’t be able to add contentions
* *add rated issues (from rating code sheet)*
	* Caseflow from the rating decision date…
		* have to pull contentions from rating decisions
	* diagnostic code, description (“back disc condition”), percentage, effective date, service connection
* *then look for items for development*
	* e.g. exam
* *after VSR has done all of the development, make it ready for decision*
* *goes back into the sky, then gets assigned by NWQ to a Rater for rating*
	* for HLR, will go to a DRO instead of a Rater

### Unidentified issue
* UNIDENTIFIED ISSUE - Edit in Caseflow to fix
	* she made a note - found which rating decision (1970)
	* 25315253
* Sally: Can VSRs add missing ratings? If you find the decision document?
	* Raters would be the ones fixing this
	* Can add the rating in VBMS-R
		* do a backfill rating, backfill that into VBMS-R
* Need clarification about non-rating vs. rating in the intake screens**
* first selection, unknown issue
	* they’re thinking that they’re not seeing it in the prior screen
	* first option is unknown
	* going to go ahead and pick it
	* in follow-up, talk about the unidentified issue 

## EP 930s
* As CAs - establish EP 930 :
	* when the Raters have told us we need to clarify an error about evidence later
	* or we notice an error in the system
* happens through VBMS
* 040 was closed in error - when the claim had already been closed, evidence came in, and they were eligible - have a coach or Rater tell us.
	* accidentally closed - 99% of the time it’s user error (could be process mistakes or incorrect clicks)
	
* claim == EP
* there are 80 different EP 930 selections btw AMA and non-AMA
	* because of claim labels
	* they’ll email

### Reasons
* Correct what was on the previous claim, or closed early before anything was done. Also missed issues that should have been on the previous claim that were not. 

### Process
* Actions
* New Claim
	* Benefit type
	* Payee
	* EP & Claim Label - LOTS
	* Claim Type
	* Claimant
…
* coach will assign?
	* NWQ will put 930s in coach work queue
		* NWQ routes EP 930s - doing what they can to route these based on the station that closed the previous EP 030s and 040s
	* coach can filter claims hey have
	* look at 930s - supplemental rating controls
	* assign to appropriate
* the manual says every time you create an EP 9300 you have to have a note to explain it. Sheila’s experience nonetheless is that the note is an exception, rather than the rule
* Note - can associate with Veteran or Claim, and then choose the EP
* What info from the original claim do they need on the established EP 930?
	* Need:
		* date of claim, issues on it, label associated
		* AMA supplemental rating
	* What will they change/edit?
		* Need to change the contention (edit contention text)
			* adding contentions back in
			* all information would be the same
			* not claim date, not claimant, etc.
		* would the label itself be something you’re trying to correct? 
			* Yes. The label will be related, but not the same
		* besides corrections, there are missed issues. 
			* if a previous claim established 4 issues but the Veteran had 5
			* EP 930 would be used to add the 5th issue
			* In this case, the EP would only list what would need to be corrected
			* pick out contentions from rating decisions when establishing SC and HLR - need to pick among them, but also add others in case there are missed issues
* If an issue is taken in on a 930, and it was also on an original claim. Would there be on a disposition on the original AND the 930?
	* e.g SC closed incorrectly. No decision was made for that contention/issue. The 930 would then have the disposition of that contention
* **the new disposition replaces the previous disposition


* is there a reason that we can’t re-establish? Other than the 930?
	* AMA is congressionally mandated - as part of it, we’re required to report all of our data for the next 7 years
	* allowing the system to re-activate a previously closed, whether it appropriately or otherwise, we could inflate what our work is
	* aligns with what Veteran Service Center (non-AMA stuff) does?

* could entertain reactivating instead?

**Comment by laurjpeterson** [comment]
Potential MVP flow:
1. User clicks `Edit in Caseflow` in VBMS on the closed SC or HLR
1. User navigates to Add/Remove issues page
   - change the navigation, change error message/remove it
1. Add/Remove issues page contains all of the request issues from the closed EP
   - populate the correct request issues from former EP
1. User can add/remove issues ONLY
1. When user clicks Establish EP, a modal or in-line edit explains that they are creating a 930 EP in VBMS and they can make further corrections in VBMS
   - add modal or inline edit
1. Establish 930 EP and connect to closed 040 or 030, attach correct label
   - connection between 930 and SC or HLR EP happens naturally via the end product establishments table - we need it at the Caseflow level for MVP
   - create the mapping btw SC and HLR EP codes and the 930 EP codes, spreadsheet above
1. Replace original SC or HLR EP decision issues from the resulting 930 EP
   - TO DO

Note: 
- "claim" and "EP" terminology is used interchangeably
- Today, if an EP is closed and the user clicks Edit in Caseflow, the user might navigate to a page where there is an error message
- An HLR has multiple end products. One could be clear and another still pending. If this is the case, we should indicate which issues are on a cleared end product? These issues should go on a 930 instead?

**Comment by laurjpeterson** [comment]
Created #5 and added it to this epic - https://github.com/department-of-veterans-affairs/caseflow/issues/11191

**Comment by laurjpeterson** [comment]
Closing this one, because scope was delivered for 8/2. 

930s work continuing in https://github.com/department-of-veterans-affairs/caseflow/issues/11639

**Comment by jimruggiero** [comment]
Consolidated all requirements from Epic #11639 into here to track all stories for all three parts in one Epic. @leikkisa @aroltsch @laurjpeterson @Sjones352 @jcq

**Comment by laurjpeterson** [comment]
@jimruggiero @leikkisa - whaddaya say we close this one?!

**Comment by leikkisa** [comment]
@laurjpeterson That sounds good to me! There's a couple of small PRs still to get done but we can go ahead and close this epic.
