### ISSUE TITLE
Styleguide Component | Progress Indicator

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#1009]
As a designer and developer, I want to know what it looks like for a user to see what a past, current and future step in a process looks like. 

# Acceptance Criteria 

- [x] Verify that the height of the process bars are 7px height 
- [x] Verify that current and past completed steps is in  `gray-dark` (#323A45) and future step is in `gray-light` (#AEB0B5)
- [x] Verify that the text for all process, whether in completed or current step, is in semi-bold and the font color is #323A45
- [x] Verify that copy (below) follows beneath title of component

# Mockup

![image](https://cloud.githubusercontent.com/assets/13420618/24362114/c8898698-12d9-11e7-9497-90ed54084a03.png)

# Description Copy 

The Caseflow App uses a minimal progress indicator to guide users through important tasks. This allows users to view where they are and what to expect in the process. Each task is labeled with a progress bar, number, and  name. 

For contrast, `gray-dark` (#323A45) is for current and past completed steps while `gray-light` (#AEB0B5) is used for future steps. This color scheme also ensures compliance with 508 Accessibility and US Web Design Standards. 

------

This story is the first place we will implement the progress indicator.
https://github.com/department-of-veterans-affairs/caseflow/issues/617

We should make sure the progress indicator is reusable, and is added to the styleguide.

Follow up with Lara and Kavi about design.

**Comment by gnakm** [comment]
**_View -  Decision Review page - Current Step Progress Indicator_**
<img width="702" alt="screen shot 2017-02-09 at 6 28 47 pm" src="https://cloud.githubusercontent.com/assets/4975959/22807569/af647e00-eef5-11e6-9263-80cd4e612fe1.png">

**_View -  EP Creation page - Current Step Progress Indicator_**
<img width="682" alt="screen shot 2017-02-09 at 6 29 03 pm" src="https://cloud.githubusercontent.com/assets/4975959/22807571/b26acdd4-eef5-11e6-9df2-4b9aa2b66869.png">

**_View -  Route Claim page - Current Step Progress Indicator_**
<img width="682" alt="screen shot 2017-02-09 at 6 29 03 pm" src="https://cloud.githubusercontent.com/assets/4975959/22807571/b26acdd4-eef5-11e6-9df2-4b9aa2b66869.png">

**_View -  Existing EP page - Current Step Progress Indicator_**
<img width="682" alt="screen shot 2017-02-09 at 6 29 03 pm" src="https://cloud.githubusercontent.com/assets/4975959/22807571/b26acdd4-eef5-11e6-9df2-4b9aa2b66869.png">

**_View -  EP Confirmation page - Current Step Progress Indicator_**
<img width="685" alt="screen shot 2017-02-09 at 6 29 10 pm" src="https://cloud.githubusercontent.com/assets/4975959/22807572/b5334cd0-eef5-11e6-9416-df34adabcc38.png">

**Comment by gnakm** [comment]
@lakohl Could you add a copy title and description for the progress indicator in the style guide?

**Comment by lakohl** [comment]
done!

**Comment by lakohl** [comment]
Sorry I did it in Issue: #617
Do you want me to copy and paste it above too?

**Comment by mmlumba** [comment]
@lakohl can you add the title/description in a comment on this ticket?

**Comment by lakohl** [comment]
I think I'm not understanding what you need. IT seems to be something other than the AC in in #617. Can you elaborate?

**Comment by gnakm** [comment]
@lakohl We're adding a little description next to ever UI component and we were wondering if you could put one together for the Progress Indicator. 

The title would be `Progress Indicator` and we need a mini description of it's purpose!

![image](https://cloud.githubusercontent.com/assets/13420618/23661060/78bdec0a-0319-11e7-836d-a63636c73ce4.png)

**Comment by lakohl** [comment]
Gotcha, sorry for the confusion!

**Comment by mmlumba** [comment]
@gnakm @lakohl Do you have a description for the Progress Bar for the style guide?

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Validated Browsers: FF and Chrome

Steps to Validate: 
1. Go to Dispatch as a caseworker and monitor the progress bar as you create EPs with duplicates and special issues

Screenshots:
<img width="1355" alt="screen shot 2017-03-10 at 4 11 50 pm" src="https://cloud.githubusercontent.com/assets/23038505/24361083/073ca7c4-12d7-11e7-979f-147a67144018.png">
<img width="1339" alt="screen shot 2017-03-10 at 4 12 12 pm" src="https://cloud.githubusercontent.com/assets/23038505/24361082/073c7bc8-12d7-11e7-9a4a-d2ed429292ee.png">
<img width="1377" alt="screen shot 2017-03-10 at 10 23 20 am" src="https://cloud.githubusercontent.com/assets/23038505/24361084/074216dc-12d7-11e7-9d7f-4444bd607b62.png">
<img width="1349" alt="screen shot 2017-03-15 at 9 23 18 am" src="https://cloud.githubusercontent.com/assets/23038505/24361106/176a53f8-12d7-11e7-8db0-b9e13da93180.png">
<img width="1252" alt="screen shot 2017-03-22 at 11 08 29 am" src="https://cloud.githubusercontent.com/assets/23038505/24361135/2b376a38-12d7-11e7-9d18-bbec1ee18a6c.png">

**Comment by gnakm** [comment]
As a designer and developer, I want to know what it looks like for a user to see what a past, current and future step in a process looks like. 

# Acceptance Criteria 

- [ ] Verify that the height of the process bars are 7px height 
- [ ] Verify that current and past completed steps is in  `gray-dark` (#323A45) and future step is in `gray-light` (#AEB0B5)
- [ ] Verify that the text for all process, whether in completed or current step, is in semi-bold and the font color is #323A45
- [ ] Verify that copy (below) follows beneath title of component


# Mockup

![image](https://cloud.githubusercontent.com/assets/13420618/24362114/c8898698-12d9-11e7-9497-90ed54084a03.png)


# Description Copy 

The Caseflow App uses a minimal progress indicator to guide users through important tasks. This allows users to view where they are and what to expect in the process. Each task is labeled with a progress bar, number, and  name. 

For contrast, `gray-dark` (#323A45) is for current and past completed steps while `gray-light` (#AEB0B5) is used for future steps. This color scheme also ensures compliance with 508 Accessibility and US Web Design Standards. 

/cc: @mmlumba @astewarttistatech

**Comment by astewarttistatech** [comment]
There is no place where the mocks or the description reside @gnakm @mmlumba Marking this as failed.

**Comment by astewarttistatech** [comment]
@mmlumba sorry to be a nit picker but "grey-dark" isn't highlighted in the copy on the page currently. @gnakm Do you want to continue this way?

<img width="1344" alt="screen shot 2017-03-27 at 1 47 30 pm" src="https://cloud.githubusercontent.com/assets/23038505/24370121/3c297e22-12f4-11e7-9af0-50af76d55a5c.png">

**Comment by gnakm** [comment]
@astewarttistatech Nit-picking is good. I just added it to the issue above. 

/cc: @mmlumba for awareness.

**Comment by mmlumba** [comment]
@astewarttistatech The changes @gnakm proposed for the highlights should be deployed now

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Validated on: FF and Chrome

Steps to Validate: 
1. Go to the style guide and match the copy and mocks of the AC to what is displayed in actual style-guide. 

Screenshots:
<img width="1267" alt="screen shot 2017-03-28 at 8 01 33 am" src="https://cloud.githubusercontent.com/assets/23038505/24403903/fa9ae2d6-138c-11e7-93b6-33929b2c35d4.png">
