### ISSUE TITLE
Fix scenarios that lead to duplicated organization tasks

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#10335]
While exploring how we could [get rid of `GenericTask.verify_org_task_unique`](https://github.com/department-of-veterans-affairs/caseflow/issues/10328) and [still be notified](https://github.com/department-of-veterans-affairs/caseflow/issues/10329) when duplicated tasks were created, @tomas-nava and I [ran a query on the underlying data](https://caseflow-looker.va.gov/sql/jqpyf5pxgrpvgb) in the `tasks` table and discovered that there are 800 or more tasks that are duplicates of existing organization tasks. Spot-checking a handful of these tasks reveals that many of these tasks are indeed duplicate tasks that were not caught by the `verify_org_task_unique` or any other mechanism in the application. 

We do not expect there to be duplicated tasks in the application and their presence could result in appeals being delayed in processing, hearings being scheduled more than once, or any number of other unexpected behaviours.

This ticket exists to identify the various scenarios that result in duplicated organization tasks and track progress on resolving those bugs.

## Related tickets:
* [ ] Get rid of GenericTask.verify_org_task_unique #10328
* [ ] Set up alert to notify us of non-unique organization tasks #10329
* [x] Stop creating duplicate TrackVeteranTasks #10336
* [x] Stop creating duplicate ColocatedTasks #10337
* [x] Caseflow::Error::DuplicateOrgTask on duplicate ChangeHearingDispositionTasks #10554

**Comment by monfresh** [comment]
Here is a Sentry error upon creating a duplicate EvidenceSubmissionWindowTask: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5946/events/420785/
```
Caseflow::Error::DuplicateOrgTask: Appeal 4203 already has an active task of type EvidenceSubmissionWindowTask assigned to MailTeam. No action necessary
```
