### ISSUE TITLE
Styleguide component | Layout section - Actions

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1089]
As a developer and designer, I want clear and consistent actions to implement actions across our application so users can complete tasks and move through apps more accurately.
 
## Acceptance Criteria 

1. Verify that there is a section called `Layout` in the style guide 
1. The dimensions of the white canvas on the style guide should be 708 x 37px
1. Verify that there is a section called `Actions` under `Layout`
1. Verify that the description for `Actions` appears under the title (see copy)
1. Verify that the component appears under the description (see mocks)
1. Verify that there is a `Layout` section in the side nav
1. Verify that clicking on the above takes you to the right section in the style guide

## Mocks

_Make sure you are logged into Invision before clicking on the Craft link_

**Layout Actions**

![image](https://cloud.githubusercontent.com/assets/13420618/24010550/9d6fc230-0a4e-11e7-9f62-1ffb592062b1.png)

## Copy:

**Title**

Layout Actions

**Description**

For most task-based pages, Primary and Secondary Actions sit under the App Canvas.  The number of actions per page should be limited intentionally. These tasks should relate specifically to the user’s goal for the page they are on. 

The actions at the bottom of the page are arranged such as the primary task (the task that takes the user forward) is on the bottom right of the App Canvas. The label of this action usually hints at the title of the next page. Escape actions are placed to the left of the primary action. On the bottom left, of the App Canvas, there will be a back link, preferably with a description of where the user will go to or a link to the main page after a user has completed a task. These are actions that allow the user to move back a step or completely leave the task they’re working on.

The consistent layout and arrangement of these actions reinforces the users mental model as the use Caseflow. You should avoid placing these actions in other parts of the page without good reason.

## Notes: 

1. We will be revisiting this issue after our next app. Until then, this is the most optimal solution for all products.
2. Some challenges to consider for the future: multiple actions carrying you forward; mobile usage

**Comment by nikitarockz** [comment]
As a user, I want clear actions to efficiently move through the app and complete my tasks accurately. 

As a developer and designer, I want clear and consistent actions to increase design and development efficiency across apps. 

*** Depends on the use case/perspective you want to use. User for front end changes and the second for the living style guide (what exists in commons). 

## Acceptance Criteria 

1. Verify that in the living style guide that there is a title called Layout Sections - Actions (WIP) and section for Actions. For visual reference: #1138 
1. Verify that the below copy is beneath the title with Actions (all caps). (see Copy below) 

> For most task-based pages, Primary and Secondary Actions sit under the App Canvas.  The number of actions per page should be limited intentionally. These tasks should relate specifically to the user’s goal for the page they are on. 

The actions at the bottom of the page are arranged such as the primary task (the task that takes the user forward) is on the bottom right of the App Canvas. The label of this action usually hints at the title of the next page.  In the rare instance where there are multiple paths forward, use a secondary button style to indicate the less common paths and place it to the left of the primary action. Escape actions are on the bottom left.  These are actions that allow the user to move back a step or completely leave the task they’re working on.

The consistent layout and arrangement of these actions re-enforces the users mental model as the use Caseflow. You should avoid placing these actions in other parts of the page without good reason.

1. Verify that that the living style guide has the correct UI components (see mock)
1. Verify that a link called Layout Sections - Actions (WIP)to the side bar section- Layout Sections- Actions (WIP). For visual reference: #1002
1. Verify that clicking on this takes you to the right section.  


## Mockups

![image](https://cloud.githubusercontent.com/assets/13420618/23623371/ce75f12e-026f-11e7-8b6f-8c608c0e21c8.png)

## Notes: 

1. For now, we will have primary button on the right for moving forward and secondary button for moving backwards on the left. 
2. We should talk more about it and consider any edits (back link, not having a back button, where does cancel go...) 
3. Some challenges to consider: multiple actions carrying you forward; mobile usage 

## Related Issues

**Comment by nikitarockz** [comment]
# Story Review

> *** Depends on the use case/perspective you want to use. User for front end changes and the second for the living style guide (what exists in commons).   

I like the perspective of the design and engineer because they will be grabbing the code and using them to make mocks.  The user basically is going to say I want a button.  As a Product Owner, I am going to say make the button match the style guide.  So I feel these are more for designers and engineers.  

- For AC 1, Is there specific location for where this new title will be displayed?  Will it be between 2 other titles or at the end of the current list of titles?
- For AC 3, What are the "correct UI components" (This could be a little ambiguous.)?  Are they the following:

     - Back to preview
     - Cancel
     - Submit End Product

- For AC 4, I have a question mark for where you want the new navigation link positioned. This may not be a big deal.  

- Related Stories, I added the 2 stories you referencing there with their title and number.  I find that having the title helps me know whether or not I really need to click the link.

**Comment by gnakm** [comment]
This issue is still a WIP and below are things to go over the design meeting tomorrow 3/16. The current actionable links/button placements are different from the one that was found in the styleguide. 

## Current Layout Actions

**Form 8**
![image](https://cloud.githubusercontent.com/assets/13420618/23982197/3b83c358-09e2-11e7-9a1f-48ee183b259f.png)

**eFolder Express** 
![image](https://cloud.githubusercontent.com/assets/13420618/23982205/43cfef3c-09e2-11e7-9104-3f713418462c.png)

**Dispatch**
![image](https://cloud.githubusercontent.com/assets/13420618/23982208/4d74003c-09e2-11e7-940e-16cfb02e9419.png)

![image](https://cloud.githubusercontent.com/assets/13420618/23982249/99e26fa8-09e2-11e7-8664-bd13f30a8c72.png)

## Suggestions
![image](https://cloud.githubusercontent.com/assets/13420618/23982407/a12c2ed8-09e3-11e7-8e49-0e0901f89880.png)
This seems to be the general pattern for the actions. 
- The idea is that the confirmation/ actionable item is the only one in a button and most prominent. 
- The back option has a carrot and is just a link.
- Cancel is next to the action

![image](https://cloud.githubusercontent.com/assets/13420618/23982316/2fa6069e-09e3-11e7-813d-4287ef519992.png)
This version makes the cancel version a little more prominent but still secondary compared to the main button. I think that the cancel button is actually important because opting out is still a conscious decision. We also have a modal that pops up to make sure that users are confident in this decision.

**Comment by gnakm** [comment]
Final design and story after design meeting discussion. 

--

As a user, I want clear actions to efficiently move through the app and complete my tasks accurately. 

As a developer and designer, I want clear and consistent actions to increase design and development efficiency across apps. 

## Acceptance Criteria 

- [ ] Verify that the below copy is beneath the title (see Copy below) 
- [ ] Verify that that the living style guide has the correct UI components (see mock)
- [ ] Verify that clicking on this takes you to the right section. 
- [ ] On the side nav, `Actions` can be found under `Layout`. 


## Copy:

Actions

For most task-based pages, Primary and Secondary Actions sit under the App Canvas.  The number of actions per page should be limited intentionally. These tasks should relate specifically to the user’s goal for the page they are on. 

The actions at the bottom of the page are arranged such as the primary task (the task that takes the user forward) is on the bottom right of the App Canvas. The label of this action usually hints at the title of the next page. Escape actions are placed to the left of the primary action. On the bottom left, of the App Canvas, there will be a back link, preferably with a description of where the user will go to or a link to the main page after a user has completed a task. These are actions that allow the user to move back a step or completely leave the task they’re working on.

The consistent layout and arrangement of these actions reinforces the users mental model as the use Caseflow. You should avoid placing these actions in other parts of the page without good reason.

## Mockups

![image](https://cloud.githubusercontent.com/assets/13420618/24010550/9d6fc230-0a4e-11e7-9f62-1ffb592062b1.png)

## Notes: 

1. We will be revisiting this issue after our next app. Until then, this is the most optimal solution for all products.
2. Some challenges to consider for the future: multiple actions carrying you forward; mobile usage

**Comment by Sjones352** [comment]
### Tasks to do
- [ ]  Verify that there is a section called `Layout` in the style guide 
- [ ] The dimensions of the white canvas on the style guide should be 714 x 50px
- [ ] Verify that there is a section called `Actions` under `Layout`
- [ ] Verify that the description for `Actions` appears under the title (see copy)
- [ ] Verify that the component appears under the description (see mocks)
- [ ] Verify that there is a `Layout` section in the side nave and `Actions` appears under layout
- [ ] Verify that clicking on the above takes you to the right section in the style guide

<img width="629" alt="screen shot 2017-04-25 at 10 51 19 pm" src="https://cloud.githubusercontent.com/assets/23080951/25416172/61ddde24-2a0a-11e7-8a5e-0b4a62663e88.png">

**Comment by mmlumba** [comment]
Original AC for 6:
1. Verify that there is a `Layout` section in the side nave and `Actions` appears under layout

**Comment by Sjones352** [comment]
<img width="516" alt="screen shot 2017-04-27 at 7 42 49 pm" src="https://cloud.githubusercontent.com/assets/23080951/25535060/dbdca2e6-2c03-11e7-9a80-14327f0b5e23.png">

**Comment by astewarttistatech** [comment]
The title is incorrect based on AC. @Sjones352 

Current View: 
<img width="1084" alt="screen shot 2017-05-03 at 8 52 48 am" src="https://cloud.githubusercontent.com/assets/23038505/25661272/fbb3c5ee-2fdd-11e7-8545-42a4f1a3ec87.png">

**Comment by gnakm** [comment]
Layout makes sense and Action is a subsection of Layout.

**Comment by Sjones352** [comment]
**Actions Section**
<img width="790" alt="screen shot 2017-05-04 at 7 32 53 pm" src="https://cloud.githubusercontent.com/assets/23080951/25729308/8b0ccce8-3102-11e7-86d3-1bd929b4e157.png">
**Margin-Right For Cancel button**
<img width="1244" alt="screen shot 2017-05-04 at 7 34 26 pm" src="https://cloud.githubusercontent.com/assets/23080951/25729330/af0e6fde-3102-11e7-8bfa-2f3bc1eb242d.png">
**Margin-top**
<img width="1244" alt="screen shot 2017-05-04 at 7 34 47 pm" src="https://cloud.githubusercontent.com/assets/23080951/25729349/cadb5c90-3102-11e7-84f9-3a3bdded1dc2.png">

**Comment by astewarttistatech** [comment]
**PASSED** due to change in AC

Validated in: UAT, Dev, and Preprod
Browsers: FF and Chrome

Steps to Validate: 
1. Access style guide
2. Validate Layout: Actions section against mocks and AC

Screenshots: 
See above comments.
