### ISSUE TITLE
[Tech spec] Improve maintainability of tasks and task actions

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#10894]
Maintenance and extension of the task model and task actions continues to occupy an extensive amount of developer time. This epic exists to address some of the issues that cause tasks and actions to occupy so much developer time.

### Process to add new task action

The rough outline of the process for adding a new action to a task is as follows:
1. Caseflow user group determines need for some action needing to be taken on a task.
1. Caseflow product owners are made aware of the need and communicate to developers.
1. Developers clarify requirements and create new action (if it did not exist before).
1. Developers add code to make action appear for specific task type under the correct conditions.
1. Developers write tests to confirm it appears as expected.
1. Code is released to production.

### Initiative goals

This development cycle takes weeks to complete. The goals of this initiative include the following:
1. Reduce the length of time it takes to add new tasks and actions.
1. Reduce amount of time developers spend adding new tasks and actions.
1. Increase comprehensibility of task and actions code.
1. Increase transparency of tasks and actions for folks using Caseflow.

### Proposed approach

In order to accomplish these four goals I propose we **move conditional task action logic out of code** and into configurations stored outside of the code.

A quick sketch of an administrative interface for this might look something like the following (#10893):
![image](https://user-images.githubusercontent.com/32683958/58483702-bebc4900-812e-11e9-91f4-3b8e86e2defe.png)

### Code changes
* [ ] Move conditional blocks out of [`available_actions` method](https://github.com/department-of-veterans-affairs/caseflow/blob/949b06739d7b4c98e12f846bcd762892aab23a9a/app/models/tasks/generic_task.rb#L34) and into configuration hashes for each task class (#10888).
* [ ] Add support for mutually exclusive task actions that determine their label and value based on the state of the task (#10889).
* [ ] Move task actions configurations out of code entirely and into database.
* [ ] Create front-end interface for more accessible configuration of task actions (#10893).

### Drawbacks

**Incorrectly available actions**: Currently when developers add task actions we can identify potential situations when a given action should not be available and prevent it from being available (judge checkout should not be available until attorney checkout is completed, for example). If task action configurations are more easily modified then we are more likely to end up adding task actions to . We can address this by having the task actions know what conditions they are not allowed to be applied to so that they cannot be added to sets of conditions.

**Environment drift**: If task actions are moved out of the code then we are more likely to have task actions be different in local and production. We can mitigate this by regularly copying production action sets into our database seeding routine (or doing something similar, depending on how the configurations are stored).

**Comment by pkarman** [comment]
Another Drawback would be versioning -- if/when action chains change, there's no visibility into who/what/when as there is with code.

I like the idea of making this more self-serve. I worry that the drawbacks outweigh the savings in developer time (and shift the developer time burden to debugging things that are no longer in the code).

Do we have any sense from the business side whether the churn in these workflow definitions is simply heavier at this point in history?

**Comment by lowellrex** [comment]
> Another Drawback would be versioning -- if/when action chains change, there's no visibility into who/what/when as there is with code.

On previous projects that have allowed user-defined rules, we've just logged all the changes to the database so we could determine who and what changes were made.

> I like the idea of making this more self-serve. I worry that the drawbacks outweigh the savings in developer time (and shift the developer time burden to debugging things that are no longer in the code).

I think you're totally right. The self-service idea is definitely the highest effort part of the proposal and potentially the lowest benefit (and biggest headache). However, I think each step along the path toward a self-service interface offers incremental yet significant benefit.

Adding support for mutually exclusive task actions that determine their label and value based on the state of the task would unify the way we build `available_actions` (they always return an array of `TASK_ACTIONS` directly) which have started to drift. This aims to increase comprehensibility of task and actions code which still takes quite some time for new developer to get ramped up on. A sketch of this approach has been included in PR #10889.

Moving conditional blocks out of [`available_actions` methods](https://github.com/department-of-veterans-affairs/caseflow/blob/949b06739d7b4c98e12f846bcd762892aab23a9a/app/models/tasks/generic_task.rb#L34) and into configuration hashes for each task class will constrain how we can build the set of actions available for each task (only logical AND conditions, returned actions are explicitly defined). This aims to make it clearer which set of conditions are resulting in which actions and again make the code more comprehensible. A sketch of this approach has been included in PR #10888.

I think the two efforts above offer the biggest reward for the least cost. However, should we choose to move task actions configurations out of code entirely and into the database would allow us to more quickly change (though we would have to test task actions more thoroughly to ensure they could not end up in an unacceptable state).
