### ISSUE TITLE
Support AMA CAVC Remands (Scope/Plan)

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#10991]
# Background
Lit Support encompasses customer service, correspondence, motions, and receiving and routing CAVC remands at the Board. I call them the department of edge cases, because they often handle complex appeals scenarios.

Lit Support responsibilities:

- Customer service = answering Veteran questions, like status inquiries
- Correspondence = sending correspondence to Veterans and other audiences that require attorneys to write (this is distinct from mail correspondence that other admin teams send, like hearing clarification letters). A key example of this is answering congressional inquiries.
- Motions = there are three major types of post-decisional motions that this team handles: Motion for Reconsideration, Motion to Vacate, and Clear and Unmistakeable Error. There are also pre-decisional motions and AOD motions.
- CAVC remands = when a Veteran appeals to CAVC, and CAVC sends the case back to the Board for development

## CAVC Remands
**CAVC Remands**. When cases get to CAVC (highest court) but are sent back down to BVA because the Board may have overlooked something or made a mistake.

# Requirements/Stories

### Goals
1. Gather requirements for supporting AMA CAVC remands
2. Understand the current process, any pain points, and potential workflows
3. Get an understanding of the core jobs to be done for each user involved in the process
Details: [User Research Study: CAVC Remands #13784](https://github.com/department-of-veterans-affairs/caseflow/issues/13784)

### Phase 1: Intake

**Scope:** 

Finding the relevant case in Caseflow based on the information from email and the CAVC website

**Stories:** 

As a lit support user: 

- [x] When I have reviewed all of the relevant information in my email and the CAVC website, I want to jump into Caseflow so I can carry out the necessary processes whether it be a Remand, Reversal, or Death Dismissal.
- [x] I want to find and pull up the relevant case in Caseflow by searching for the case on the Search Page 

### Phase 2: Intake - Remand

**Scope:** 

Once the relevant case is found in Caseflow, processing it as a CAVC Remand. 

**Stories:** 

- [x]  When I have a remand order, I want to kick off a remand workflow in Caseflow so I can work the case. #14708 
- [x] When I have a remand case without mandate, I want the task to automatically be placed on hold for ninety days so that I can come back to the case hoping that mandate has been made (so we can further act on the case). [#14773](https://github.com/department-of-veterans-affairs/caseflow/issues/14773)
   _ What is the process after the mandate is complete? Are we adding tasks to the "Actions" drop down? If so, what are the task names?
  - If no mandate yet, repeat process [#9207](https://github.com/department-of-veterans-affairs/caseflow/issues/9207) ✅
- [x] When I have mandate on the remand case, I want to create a new appeals stream for the remand workflow so I can create the space for a new decision. #14792 
- [ ] When I have a new appeals stream for the remand case, I want to add/edit issues from the original case so that they can match the issues argued for in the court order details. #14795
- [ ] When I have a remand case, I should have a limited set of admin actions on the root task before the 90 day letter task, so that I can get necessary actions in order as ordered by the Court. #15140 
- [ ] As a Caseflow user who has access to view documents for a case, I need Reader to be able to determine what the CAVC document types are and display them labeled appropriately, so that I can easily distinguish CAVC documents in the appellants file #15238 
- [ ] Update Case Order Logic [#14959](https://github.com/department-of-veterans-affairs/caseflow/issues/14959)
- [ ] Update Auto-Distribution Priority Cases Algorithm [#14958](https://github.com/department-of-veterans-affairs/caseflow/issues/14958)

### Phase 3: Intake - Reversal

**Scope:** 

Once the relevant case is found in Caseflow, process it as a CAVC Reversal.

**Stories:** 

- When I have mandate on the remand case, I want to create a new appeals stream for the reversal workflow so I can create the space for a new decision.
- As a lit support user, if a mark that the case is a Straight Reversal, the case needs to be routed to Case Storage (for legacy) and Case Distribution (for AMA). 
~~- As a lit support user, I need to mark whether this is a "Point of Law" or "Straight Reversal", so I can complete the next task~~
~~- As a lit support user, when I have indicated a "Point of Law" reversal and have the case follow the Remand path [unclear]~~
~~- As a lit support user, when I have indicated a "Straight Reversal" I want to [unclear]~~
~~- [Happens outside of Caseflow, consider having a reminder or check-list] As a lit support user, I want to download all the pertinent documents on the court order from the CAVC website, so that I can upload them to VBMS to ensure that the documents are present there and accessible.~~

### Phase 4: Intake - Death Dismissal

- [ ]  Carry our a case all the way out into post dispatch with decisions, log-in as lit support and see if there is a add a new task action for death dismissals.

**Scope:** 

Once the relevant case is found in Caseflow, process a death dismissal if the veteran or appellant has passed away. 

**Stories:** 

- When I have a death dismissal case without judgement or mandate dates, I want the task to automatically be placed on hold for ninety days so that I can come back to the case hoping that the judgement or mandate has been made (so we can further act on the case). 
- When a litigation support user creates a new death dismissal appeal stream, the appeal should be added to case distribution as priority. 
~~As a lit support user, I want to complete a death dismissal order, if the veteran or appellant has passed away~~
~~- As a lit support user, I want include the link of the ruling letter and send it to the (original?) judge so that it can be signed
~~- As a judge, I want to receive the ruling letter for a death dismissal so that I can sign it and sent it back to the lit support user~~
~~- As a lit support user, I want to receive the signed ruling letter so that I can can send it out to the veteran or appellant's representative~~
~~- [Happens outside of Caseflow, consider having a reminder or check-list] As a lit support user, I want to download all the pertinent documents on the court order from the CAVC website, so that I can upload them to VBMS to ensure that the documents are present there and accessible.~~

### Phase 5: 90-day letter

**Scope:** 

Once the CAVC has been processed (the Add Court Remand form has been completed), a 90-day letter needs to be sent to the appellant and tracked. 

**Stories:** 

As a lit support user:

- When I've completed the intake process, I want to generate a 90-day letter with specific details and orders about the case from the Court so that I can send the letter to the veteran / appellant for response. #15076 
- Design task for 90 day letter, figure out if go into "hold" queue

### Phase 6: Retrieve

**Scope:** 

Once the CAVC has been processed (the Add Court Remand form has been completed) and a 90-day letter needs to be sent to the appellant a response needs to be tracked. 

**Stories:** 

As a mail team member:

- [ ] When I receive a 90-day letter response (specific to CAVC remands?), I want to route the document and task to the appropriate user so they can act on it accordingly. Similar to the Evidence Submission Task #15239
- Enter decision from veteran: extension (= "on hold" already under "actions"), looks good (= "send to judge" under "actions), or hearing (need to add an action potentially and think through backend)

### Phase 7: Assign, Draft, Review

No need to build and test for this phase

→ Task type name: Remand

→ Top priority cases right below 

→ CAVC remand cases and AOD cases are automatically in front of the line, auto distributed to judges and don't wait in some queue

- remands were pulled, putting AMA cases in VACOLS only
- Potentially design a task for "assign, draft, review" for tracking purposes

**Scope:** 

(scope) 

**Stories:** 

- All the same existing attorney, judge, and dispatch checkout flows, however, CAVC orders always have top priority so these must be prioritized for action above regular decisions, but not above AOD cases.

# Resources: 
[Background & Opportunity ](https://docs.google.com/presentation/d/1zndziCiiB22FrpzdI2SqWdOXbWqekqaJ4UY6r3QDGAU/edit#slide=id.g935ded86e1_0_6)
[Workflow Diagram](https://whimsical.com/VyXzGFZxWmr3mg7Fzy9Tvi)
[UX/UI Designs](https://www.figma.com/file/8noUqRbvCJzdpwkSNCb8lZ/CAVC-Remand-Designs?node-id=289%3A286)
[Product Brief](https://docs.google.com/document/d/1-EzNBC83BjyiRhtBl_s5rrf2Qejp4b7NHsVC7JW4FzA/edit)

**Comment by geronimoramos** [comment]
Relevant notes from previously speaking with Lit Support:
- *LP: As we think about the work we're doing with your team, with Litigation Support, the projects within it are: first motions to vacate, then motions for reconsideration, then clear and unmistakable error. Then CAVC. We're still in motions to vacate. And as these rich conversations have shown, you can see how the complexity does increase as you dig in, so that complexity can take time. I would love your guidance, this whole team, if we need to reprioritize at any time.*
- Kate: They're all a big deal. But in terms of ours, it's actually easier for us to just do it in VACOLS because that's what we're used to. And that's what we've been doing. It's going to be the lift at the end for someone to take that information and then put it in Caseflow. We're gonna start a very basic spreadsheet of veteran name, veteran C number, and what action we took in VACOLS for him or her. If there's more information than that, that you think we should be including on that spreadsheet, just let me know.
- *LP: I think the main thing is with CAVC and court remands, we need to create a new docket number, right?*
- Kate: It's the same docket number as the underlying board decision. Basically, essentially, instead of the Board vacating our own decision, the Court vacated our decision. And it can be similarly limited by issue. They could affirm us as to an issue; vacate and remand us as to another issue.
- *LP: We could create another task. Kind of like the motion to vacate task that Lit Support is already able to add to appeals because the docket number is still valid. Add that court remand task and do whatever work we need to get done. That's less complex. And then the work we're doing right now to adopt some but not all issues from the former decision into the next step can be reused when we get to that CAVC point.*
- Kate: I think so. Yeah.

**Comment by araposo-tistatech** [comment]
moved to jira, closing
