### ISSUE TITLE
Use config from back-end to define organization queue tabs

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#11045]
#10620 changes the way we build `OrganizationQueue` from using components to using a mostly static configuration defined on the front-end. #10049 sends the organization's table configuration from the back-end to the front-end. This ticket exists to use the configuration we receive from the back-end in place of the one we've defined on the front-end. We will continue to draw tasks from the global redux state, not the queue table configuration.

## 🚫 Blocked by
* [ ] Build OrganizationQueue from static configuration #10620
* [ ] Pass columns to display in queue table view from back-end #10049

## Acceptance criteria
* [ ] Use the back-end's configuration to generate components on the front-end
* [ ] Remove the nearly-static configuration on the front-end introduced in #10620
