### ISSUE TITLE
Switch already-scheduled hearing Type to Virtual Hearing (Gen2 functionality)

### ISSUE THREAD

**Issue by nicholer** [department-of-veterans-affairs/caseflow#11508]
## Story
As a Hearing Coordinator, I want to switch an already-scheduled Veteran from a Video hearing to a Virtual hearing.

### Invision Link
https://va-gov.invisionapp.com/share/8AUO95JMRW7#/screens/391731042

> Use Invision's Inspect feature to grab exact copy and see other detailed specs:
> - click on a prototype link in an issue
> - click the Inspect icon </> in the bottom right of the screen
> - choose `Already a member? Sign in`
> - login using the Caseflow Invision account (see 1password)
> - use Inspect 🎉

### Description
The flow shown in the prototype is provided for context and much of the functionality already exists. Here are the updates / new functionality:

#### Hearing Details
- On **Hearing Details**, the Hearing Coordinator is able to update the Hearing Type
  - The Hearing Type field is a dropdown
  - Hearings can be switched between Video and Virtual (and later between Central and Virtual), but cannot be switched between Video and Central
- When the Hearing Coordinator changes the Type from Video to Virtual and selects 'Save' a **modal** appears with the following:
  - Hearing date - display-only - dd/mm/yyyy
  - Hearing time - display-only - both EST and Veteran's local time
  - Veteran Email - input field
    - pre-populated with email displayed on Case Details
    - editable by Hearing Coordinator
    - a validation error displays if the email is not properly formatted
  - POA/Representative Email
    - pre-populated with email displayed on Case Details
    - editable by Hearing Coordinator
    - a validation error displays if the email is not properly formatted
  - When the Hearing Coordinator selects to submit/confirm on the modal, Caseflow attempts to:
    - schedule the virtual hearing (via Pexip)
    - send email notifications with calendar invites to the (1) Veteran Email, (2) POA/Representative Email, (3) email of the Judge assigned to the hearing _(email content will be a separate issue)_
    - saves Veteran Email and POA/Representative Email inputs for this hearing only _(Case Details data is not affected)_
- While the async jobs to schedule the hearing via Pexip and send the emails is in progress, the Hearing Details page displays: (_Revisions to alert messaging made 11/04_)
  - an info alert
  - Hearing Type value is 'Virtual' - field is disabled
  - VLJ Virtual Hearing Link - field is disabled with placeholder text that reads: "Scheduling in progress"
  - Veteran Email - disabled input field
  - POA / Representative Email - disabled input field
- When the async jobs are complete, the Hearing Details page displays:
  - Hearing Type dropdown field is enabled
  - VLJ Virtual Hearing Link - non-editable - This is the Judge URL to start/connect to the virtual hearing. Clicking the link opens the virtual hearing URL in a new tab.
  - Veteran Email - input field - editable by Hearing Coordinator
  - POA/Representative Email - input field - editable by Hearing Coordinator

#### Daily Docket
- On the **Daily Docket,** the 'Time/RO(s)' column heading is updated to read 'Type/Time/RO(s)'
  - The Hearing Type (Video, Virtual, or Central) displays above the hearing time / RO / number of issues.
- The **print view of the Daily Docket** displays the Type.
- After the Hearing Type is changed to virtual, the Daily Docket page depends on the async jobs status:
  - While the async jobs are in progress, the Daily Docket displays:
    - disabled VLJ Virtual Hearing Link, with placeholder text that reads "Scheduling in progress", in the Actions column
    - disabled hearing Time field
  - When the async jobs are complete, the Daily Docket displays the active VLJ Virtual Hearing Link in the Actions column. Clicking the link/label opens the virtual hearing URL in a new tab.

#### Your Hearing Schedule
- After the Hearing Type is changed to virtual:
  - The **Your Hearing Schedule** page displays Virtual in the Type column, and Virtual is included as a value in the column filter. 
   - If there are multiple Hearing Types for one day, all types are listed, separated by a comma. 

## Related Tickets
#11158, #12347

**Comment by carodew** [comment]
next steps (identified in 7/24 meeting) 

- design continues exploring questions we need answered
- design sets up a follow-up meeting to review additional flows
- engineering lightly writes up what information they need in order to start planing tech spec/architecture changes to support telehearing

**Comment by nicholer** [comment]
Next steps (identified in 7/30 meeting) 

- [ ] NR to finalize initial flow for converting to telehearings and back
- [ ] PS to try to setup feedback sessions with Hearings branch for Thursday
- [ ] PS to setup a meeting with telehearings tech team sometime next week
- [ ] PS to send AL tech specs

**Comment by carodew** [comment]
Noting that this work is lower in priority than the Veteran's tele-hearing research, and will be informed by that research.

**Comment by nicholer** [comment]
8/30 Design Sync

**Open Questions and Follow Ups**
- Do we store the POA (power of attorney) / representative email?
- If the hearing date or time is changed, Caseflow needs to be able to send another email to notify participants of the change

**Next Steps**
- Meeting with pilot Hearing Coordinators next week to determine if this first iteration functionality meets their needs
- Mock up an example of when scheduling a telehearing (sending email notifications) fails
- Allow Hearing Coordinator to switch from type Central to Telehearing.
- Explore what info would be useful to display on the Switch to Telehearing modal
  - Would it be useful to see the Veteran and representative timezone?
- Displaying the telehearing link on the Daily Docket:
  - Can we hide the full URL? And make the field label clickable? 
  - Do Hearing Coordinators and Judges need to be able to easily copy/paste the link?

**Comment by nicholer** [comment]
9/4 Stakeholder Design Review - Takeaways and next steps:

- **Research / Design**
  - Hearing Coordinators need to change the time of telehearings, and they can do that from the Daily Docket (lessens the importance of the flow that goes through Case Details)
  - Explore what additional telehearing metadata would be useful to display (multi-/dual-point; whether VA facility is required; etc)
  - Veteran and POA / Representative email - Consider adding a text field for input of additional email addresses, which wouldn't be saved by the system long-term but are associated with that hearing
- **Product**
  - Investigate generating an admin link from the telehearing solution, so Hearing Coordinators don't have to use the Judge link when they run tests

**Comment by nicholer** [comment]
@pshahVA @lomaxap I was trying to work through the scenario of when a virtual hearing disposition changes and Caseflow sends an email if it's been cancelled or postponed.

I could use more info about the usual workflow for hearing disposition changes. I've read through some tickets about nightly jobs and looked at demo, but I'm still uncertain of (1) when an email notification should be sent to the Veteran and (2) what the email notification should say about possible next steps.

**Comment by pshahVA** [comment]
Nichole, I was on a call, and there was thought of "resending" the email invite if the veteran lost it.  It would not be part of this first build, but maybe we could think of it as part of the design (in the future)

**Comment by nicholer** [comment]
@pshahVA Got it - added email resends to my list future functionality

**Comment by pshahVA** [comment]
@nicholer , I went through this one more time, and I had a question on the page where we update the hearing to "virtual".  Should we change the location to empty?  
However, I'm not sure if we should do that, because then if you change it back, we need to know what to set the location to.

**Comment by nicholer** [comment]
@pshahVA Good question. I think it'd make sense to change the Hearing Location to 'Virtual'. And if the type was switched back, then the Hearing Coordinator could either manually edit the Location on the Daily Docket page (probably not the best experience), or we require them to enter it in the modal when they're switching back?

**Comment by nicholer** [comment]
Design is complete, so moving to `Ready for Dev` pipeline until associated engineering tickets are complete

**Comment by ferristseng** [comment]
Done!!
