### ISSUE TITLE
Unify GenericTask and Task classes

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#11607]
The `GenericTask` class was [created last summer](https://github.com/department-of-veterans-affairs/caseflow/pull/6713) to extend the `Task` model in a more... generic way than the existing `Task` subclasses so that we could quickly roll out queues to different work groups at the Board. Once all `Task` subclasses inherit from `GenericTask`, we should combine those two classes into a single class to remove an unnecessary class and reduce confusion around why they both exist and how they are different.

## Blocked by 
* [x] Refactor `JudgeTask` to inherit from `GenericTask` #7630
* [x] Refactor `ColocatedTask` to inherit from `GenericTask` #11605
* [x] Refactor `AttorneyTask ` to inherit from `GenericTask` #11606 

## Acceptance criteria
* [x] Move all logic in `GenericTask` into `Task`
* [x] All classes that currently inherit from `GenericTask` inherit from `Task` (#12485)
* [x] Stop creating `GenericTask`s in the application (see https://github.com/department-of-veterans-affairs/caseflow/issues/11607#issuecomment-546942653) (#12487)
* [x] Update tests and generators to create `GenericTask`s instead of `Task`s (#12487)
* [x] Change type of [833 `GenericTask`s in production](https://caseflow-looker.va.gov/sql/9ctxpwxvrbvbs3) to `Task`
* [x] Remove `GenericTask` class
* ~[ ] Rename [`:generic_task` factory](https://github.com/department-of-veterans-affairs/caseflow/blob/5453cdcfd5d9c1bf283fad51dc92160e4cd29de6/spec/factories/task.rb#L97) to `:task`~

**Comment by lowellrex** [comment]
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | ||||||
2 | |||
3 | 
5 | 
8 | 
```

Estimating this at 1. Possible 2 because we anticipate a fairly significant amount of test changes.

**Comment by lowellrex** [comment]
Looks like our application is still creating `GenericTask`s (perhaps by way of [the `AssignToView`](https://github.com/department-of-veterans-affairs/caseflow/blob/5834be47e5145a31bf0f928a70b87d7d504f78d1/client/app/queue/AssignToView.jsx#L72)?). Adding that as an acceptance criteria.

[_Source: Looker_](https://caseflow-looker.va.gov/sql/4jpxsz3rcyfmjy)
![image](https://user-images.githubusercontent.com/32683958/67681606-0f490400-f964-11e9-9998-45b5fe055d8f.png)

**Comment by kevmo** [comment]
Changed 834 `GenericTask`s to `Task`s.

Here's the relevant portion of the Rake task output. Contains IDs of those tasks whose `type` has been changed + the reverting rake command.
```
Revert with: bundle exec rake tasks:change_type[Task,GenericTask,853,854,855,859,860,11836,11839,12227,12253,13476,13478,14342,14367,15398,15399,15401,15402,15683,15696,16535,16561,16566,16567,17206,17207,18001,18007,20120,20123,22629,22939,22940,22965,22966,23026,26227,26973,27110,29042,29182,30615,31115,31180,31194,31204,31225,31231,31237,31238,31249,31276,31429,31649,31727,31728,31729,31730,31957,31998,31999,32036,32037,32059,32060,32087,32183,32212,32243,32255,32383,32404,32415,32419,32420,32423,32424,32996,33428,33429,33440,33824,33897,34065,34571,34923,34924,34925,34929,35264,35311,35314,35318,35322,35323,35362,35364,35367,35732,35741,35742,35745,35746,36007,36051,36052,36113,36194,36195,36220,36221,36234,36252,36593,36597,37831,38502,39376,41582,41583,45244,45245,45524,45525,45535,45688,45743,45744,45760,45808,46143,51748,51749,66950,66953,67031,67035,72062,72954,72989,73004,74844,74845,74847,74890,74891,74926,74961,75125,75362,75363,75378,77290,77291,77300,77302,88553,91469,91475,108687,110790,110905,111254,111960,112780,112781,112792,112879,114040,119372,119384,128557,128562,130978,130994,130998,130999,131013,131331,131347,131383,131384,131422,131444,131454,131561,131587,131588,131678,131679,131708,131709,131719,131857,132014,132023,132712,132800,133798,133934,133938,133955,133957,133961,133962,134821,134822,134903,134916,135102,136010,136521,136536,136538,136539,136540,136541,136543,136570,136585,136588,136800,136815,136818,137721,137728,137732,137737,137912,138061,138070,138473,138709,139148,139155,139186,139188,139557,139566,139720,139758,140093,140720,140817,140829,141358,142674,143921,143935,144325,144327,144333,144338,144358,144360,144567,145076,145095,145417,145419,145420,145421,145422,145423,145577,145629,146789,146791,147426,147504,148149,148167,148171,148174,148177,148180,148293,148294,148362,148402,148597,148602,148768,148775,148818,148839,148859,149404,149407,149423,149829,150774,151117,151119,151126,151130,151333,151376,151439,151464,151467,151480,151592,151639,151803,151824,151849,152484,152518,152537,152546,153171,153182,153197,153212,153227,153230,153237,153238,153252,153255,153256,153260,153282,153283,153286,153289,153290,153293,153294,153297,153300,153313,153351,159088,160053,160114,160126,160536,160552,161961,161971,161981,162517,162591,162899,163455,163458,163546,163754,163907,164129,164224,164277,164439,164440,164522,164789,164803,164873,164957,164970,165301,165322,165330,165340,165373,165387,165499,165530,165662,165834,166376,167540,167610,167616,167735,167736,167739,168212,168339,168675,168845,168975,169030,169038,169068,169114,169118,169125,169126,169135,170087,170465,170844,170855,171159,171635,172138,172160,172202,172206,172211,172212,172216,172218,172222,172224,172227,172228,172231,172232,172235,172238,172244,172245,172247,173807,173809,174377,174888,174957,174961,174969,174973,174978,175003,175007,175017,175066,175084,175103,175106,175118,175140,175145,175147,175148,175153,175166,175170,175177,175186,175189,175204,175264,175273,175282,175292,175776,175787,175799,176065,176213,176341,176342,176347,176349,176395,176417,176419,176427,176513,176541,176542,176558,176581,176652,176674,176819,176826,176857,176906,176910,176912,176917,176959,176961,176979,176991,176993,176994,177000,177015,177019,177022,177036,177038,177173,177177,177303,177328,177407,177483,177756,177926,177935,177941,178263,178264,178398,178427,178431,178530,178533,178556,178558,178562,179792,179794,179797,179801,179804,179807,179809,179811,179813,179815,179821,179823,179824,179827,179831,179834,179836,179854,179855,179873,179876,179884,179885,179892,179999,180005,180006,180007,180017,180022,180025,180028,180040,180306,180607,181054,181055,181056,181057,181058,181059,181073,181225,181231,181237,181256,181425,181462,181957,181963,181965,181973,181974,182155,182157,182389,182461,182462,182485,182573,182574,182576,182578,182579,182580,182584,182585,183331,183477,183478,183479,183481,183689,184850,185375,185379,185380,185381,185476,185809,185811,186395,187848,188543,188654,188691,188989,188990,188991,188992,188993,189005,189006,189215,189216,189236,189242,189582,189771,189817,189820,189883,189962,190036,190296,190369,190374,190387,190388,190408,190409,190473,190474,190482,190483,190495,190496,190563,190672,190681,190682,190693,190702,190711,190712,190754,190755,190761,190776,190777,190844,190845,190868,190899,191005,191016,191040,191388,191625,191727,191744,191759,191774,191817,191829,191842,191843,191848,191867,191985,191998,192001,192043,192045,192056,192086,192115,192116,192117,192134,192140,192147,192263,192694,192779,192924,192927,193072,193097,193107,193201,193229,193232,193233,193234,193236,193239,193240,193361,194657,194813,194815,194819,194820,194829,194831,194833,194834,194841,194845,194846,194849,194927,195196,195198,195658,195659,195665,195666,195681,195682,195722,195723,195732,195733,195758,195759,195774,195775,195894,195895,195936,195937,196529,196530,196552,196553,196680,196683,196700,198025,198104,198379,199471,200384,200643,200648,200654,200787,200821,201316,201333,201387,201423,201498,201983,202101,202354,202411,203349,204729,204814,204926,205307,205764,205818,205866,206767,207121,207255,208329,211611,216598,217514,217515,217516,219234,219457,219465,220537,222045,222948,222994,223002,223080,225709,225721,225772,225794,225828,225835,225837,225926,225990,226093,226129,226828,226855,231056,231749,231856,232578,235749,250519,258222,262359,277805,285859,299126,299128,342943,342979,347213,356217,369327,369330,398514,399770,400916,403161,404217,415070,448900,449912,450306,451199,451545,455964,456993,457006,457908,458825,458826,458827,458828,458830,458832,467216,467229,467415,468164,468169,469152,470119,479560,483754,493381]
```

**Comment by kevmo** [comment]
Eliminating final acceptance criteria - there is already a factory called `task`, and the one unique role that the `generic_task` factory fulfills (it is for AMA appeals, basically, whereas `task` is created with a LegacyAppeal) remains. The need to rename it is nebulous, so: Canceling that criteria, closing ticket.
