### ISSUE TITLE
Customer Effort Score (CES) 2.0

### ISSUE THREAD

**Issue by carodew** [department-of-veterans-affairs/caseflow#11692]
@carodew commented on [Wed Aug 07 2019](https://github.com/department-of-veterans-affairs/appeals-design-research/issues/1165)

## Goals
- [ ] Identify top priority user tasks that are essential to the user and business goals of Caseflow.
- [ ] Embed the CES survey within the Caseflow application, at the end of strategically selected key tasks. 
- [ ] Collect the data and target specific areas for further exploration and iteration. 

## Impact 

Allows us to gather better user experience metrics so that we can more accurately target pain points and successes in the current application. 

## Background

With the [CES survey 1.0](https://github.com/department-of-veterans-affairs/caseflow/issues/10542) we developed an MVP version of a customer effort score survey that can be sent via email. However, this metric can be improved (that is, made more specific to certain tasks and more accurate) by embedding it into the Caseflow application itself. The idea is users would be presented with this one-question survey immediately after completing a certain task, while the task is fresh in their minds, and specific to a certain user task, rather than the application as a whole. This gives us much better information in terms of knowing which areas of the user experience could be improved. 

---

@carodew commented on [Wed Aug 07 2019](https://github.com/department-of-veterans-affairs/appeals-design-research/issues/1165#issuecomment-519112562)

Note – this would likely become an `epic` should we choose to do it.

**Comment by alisan16** [comment]
Closing as we are no longer tracking CES, based on @FredAllen6608 's conversation with OIT
