### ISSUE TITLE
Build generic individual queue from config

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#11698]
As the final step for defining individual queue configurations on the back-end for generic queues (Caseflow users who are neither judges nor attorneys), we will generate the queue components for generic individual queues from the configuration returned from the back-end. We should be able to re-use much of [the work we did for organizational queues](https://github.com/department-of-veterans-affairs/caseflow/blob/99edafe333201710f276317da22d05bc66df5acd/client/app/queue/OrganizationQueue.jsx#L128) here.

For the time being we should rely on tasks in the redux store.

## 🚫 Blocked by
* [x] Return QueueConfig to front-end for individual queues #11697

## Acceptance criteria
* [ ] Generate queue components for generic individual queues from configuration

## PR phases
* [x] Update configuration back-end returns to front-end (#12472)
* [x] Load config into state on front-end (#12473)
* [ ] Build individual generic queues from config on front-end (#12499)

**Comment by lowellrex** [comment]
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
      1 | 
      2 | |
      3 | ||||||
      5 | |||||
      8 | 
```

Should have minimal to no user-facing impact. We shouldn't need new tests for this change, existing feature tests should cover it.

Estimating at 3. Possible 2 because we might be able to drop-in the work we used in `OrganizationQueue` wholesale and it just works. Possible 5 because tests might break in unexpected ways, since this is the final step it could reveal faulty assumptions made in earlier steps that snowball as we untangle them.
