### ISSUE TITLE
Split TaskPager apart

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#11733]
While working on [returning grouped counts of tasks to the front-end](https://github.com/department-of-veterans-affairs/caseflow/issues/11509), it became increasingly apparent that the `TaskPager` class was overloaded. Specifically, it is doing 4 different jobs:
• Paginated some set of tasks
• Sorting some set of tasks
• Filtering some set of tasks into a smaller set of tasks
• Fetching tasks for a given tab

This ticket exists to untangle these jobs from one another.

**Tasks for a given tab**
The logic for fetching tasks for a given tab could be offloaded to the `QueueTab` classes. Combining this with a factory could result in code that looks like the following sketch.

```ruby
tasks_for_tab = QueueTab.from_tab_name(tab_name_param).tasks_for(assignee)
```

**Sorting tasks**
Since we sort tasks on a given column it may make sense to create `QueueColumn` classes that encapsulate this logic. We could reuse those objects to help return the grouped task counts to the front-end as part of #11509.

## Acceptance criteria
* [x] Move logic for fetching tasks for a given tab out of `TaskPager` (#11735)
* [x] Move logic for sorting tasks out of `TaskPager` (#11750)
* [x] Move logic for filtering tasks out of `TaskPager` (#11816)
