### ISSUE TITLE
Motion to Vacate | Research and Testing with VLJs

### ISSUE THREAD

**Issue by geronimoramos** [department-of-veterans-affairs/caseflow#11812]
We have done a round of research/testing with VLJs and now we have to do another round to collect information on some unknowns and validation on our designs.

## To-Dos
- [x] Get discussion guide prepared with relevant designs and open questions
- [x] Decide on speaking with same VLJs or different, both?
- [x] Schedule sessions
- [x] Conduct sessions
- [x] Extract info from sessions
- [x] Organize and share insights

### Open Questions
- What are the key differences in Withdraw v. Dismiss? Are the ruling letters different?
- Clarify differences of the 2 types of Vacates, what the process will look like in carrying those 2 types out in Caseflow?
- 

### Prototype to test with
https://www.figma.com/proto/GCRmxv1kWxPgLV8ipgD5RJ/VLJ-Flow-with-Actual-Screens?node-id=0%3A229&viewport=103%2C231%2C0.09255273640155792&scaling=min-zoom

#### Note
- Bring in an engineer and LP and Jim for research with VLJ especially for Grant: 2 types of grants

#### Related 
- #11723 
- #11724

**Comment by geronimoramos** [comment]
Geronimo / Rutvi - Documentation day for this research on Sep 18th, 2019

**Comment by msj0nes** [comment]
@geronimoramos this ticket is from August . Can it be closed?
