### ISSUE TITLE
Motion to Vacate | Research and Testing with Lit Support

### ISSUE THREAD

**Issue by geronimoramos** [department-of-veterans-affairs/caseflow#11831]
We've done a few rounds of research/testing with the Lit Support Team to get the high-level overview and requirements for this Lit Support MTV flow. 

## To-Dos
 - [x] Get discussion guide prepared with relevant designs and open questions
 - [x] Schedule sessions
 - [ ] Conduct sessions
 - [x] Extract info from sessions
 - [ ] Organize and share insights

### Open Questions
- How frequently is the CAVC website updated?
- Tell us more about the process for Pulac-Cerullo jurisdiction checks. We know that if the appellants name shows up on the website, they send it to Lit Support and it goes on `HOLD` and then what? 
- Why are we only working on these 3 motion types and because this ticket #11721 needs to have Motions Attorneys be able to relabel mail items to the appropriate motion type or mail item type

**Comment by msj0nes** [comment]
@geronimoramos this ticket is from august 2019 , can it be closed?

**Comment by geronimoramos** [comment]
@msj0nes yes, this is done!
