### ISSUE TITLE
Add task action "Death Dismissal" to LegacyAppeals

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#12211]
Specifically for FNOD - Deceased veterans are being scheduled hearings (receiving letters, taking up hearing spots for other vets). As VACOLS users are no longer able to move cases out of caseflow with vacols, we need to give them this option within the caseflow application.
Selecting this action will change the case's location in VACOLS to location 66 and cancel all open tasks for judge to start working on dismissing the appeal. 

[Relevant slack words](https://dsva.slack.com/archives/CJL810329/p1568913385077700?thread_ts=1568912922.076400&cid=CJL810329).

## AC
- [x] Display "Death Dismissal" task action for legacy appeals with
  - [x] VACOLS location code of "CASEFLOW"
  - [x] A non nil value for `SFNOD` on the veteran's `CORRES` record
- [x] Selecting this action will confirm with the user that all open tasks will be cancelled and the appeal's location code will be updated to 66
- [x] Confirming this action
  - [x] Cancels all open tasks
  - [x] Updated the appeal's location code in VACOLS to 66

**Comment by hschallhorn** [comment]
@laurjpeterson Anything to add on this?

**Comment by laurjpeterson** [comment]
Looks good to me! Fixed minor wording in main entry.

**Comment by kevmo** [comment]
1 |
2 |
3 | |||||||||
5 | |||
8 |

3.  Straight-forward, but involves VACOLS, lending uncertainty and some 5 votes.

**Comment by hschallhorn** [comment]
When cancelling all tasks, ensure that we do not have situation where we leave zombie open tasks that may have been opened when a task is cancelled.

**Comment by lomky** [comment]
- Who should be able to do this? 
   - The Judge on the case. Not the Attorney.
 - When should the Judge be able to do this? Anytime the case is at the Judge or Attorney.
