### ISSUE TITLE
Create JudgeTeamRole objects in application

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#12481]
Follow-on ticket from #12420. That ticket created the tables and classes, this ticket exists to create those objects in the application code. 

## Acceptance criteria
* [x] Create `JudgeTeamLead` wherever we currently [create a "judge" for a `JudgeTeam`](https://github.com/department-of-veterans-affairs/caseflow/blob/c82d3f8e65ad7d5d079468ff3a79964bfbaddbdd/app/models/organizations/judge_team.rb#L8). (#12484)
    * Assume judge will be `JudgeTeamLead`
* [x] Whenever an attorney is added to a `JudgeTeam`, create a corresponding `DecisionDraftingAttorney` instance. (#12493)
    * Assume non-judges will be `DecisionDraftingAttorney`
* [x] Ensure `JudgeTeam`s have only one `User` with the `JudgeTeamLead` role. (#12497)
* [x] Ensure `JudgeTeamLead`s are always identified as admins in the associated `OrganizationsUser` model. (#12497)

Since we do not ever expect to find the application in the state described by these last two acceptance criteria (that is, we don't expect the application to ever have a `JudgeTeam` with anything other than a single `JudgeTeamLead`), consider implementing these acceptance criteria as [data integrity checks](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/jobs/data_integrity_checks_job.rb). Implementing these as data integrity checks will allow the application to continuing functioning while we investigate how the application ended up in this state.

**Comment by lomky** [comment]
Estimating while in flight at a 2

**Comment by yoomlam** [comment]
All tickets associated with Acceptance Criteria are complete.

**Comment by yoomlam** [comment]
All associated sub-tickets have been merged.
