### ISSUE TITLE
Determine what to do with children of cancelled tasks assigned to inactive users

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#12505]
Spun out of #12483.

[Some slack chatter.](https://dsva.slack.com/archives/CJL810329/p1572295303028100)

In some scenarios, when we "reassign" tasks of an inactive user, some tasks are merely cancelled to be reassigned manually by a judge, team admin, quality reviewer, bva dispatch team member, etc. On occasion these tasks will have children that become orphaned due to their parent being cancelled. In some scenarios, these children can be moved to their new parent. In other scenarios, these downstream children should be cancelled. 

This ticket exists to determine which path to take in which situation.

### AC
- [x] Plan to handle children of cancelled tasks is created
- [ ] Properly handling these children is specced out with another ticket(s) to do the work

**Comment by lomky** [comment]
Throwing a 2 at this after scoping it to planning out the work needed.

**Comment by araposo-tistatech** [comment]
@hschallhorn, 

Can you confirm the below are the only parent/child task associations we will run into in this case? 

**“PARENT TASK”, “CHILD TASK”**
[[“JudgeAssignTask”, “AttorneyTask”],
[“JudgeDispatchReturnTask”, “AttorneyDispatchReturnTask”],
[“BvaDispatchTask”, “JudgeDispatchReturnTask”],
[“QualityReviewTask”, “JudgeQualityReviewTask”],
[“JudgeDecisionReviewTask”, “AttorneyTask”],
[“JudgeDecisionReviewTask”, “AttorneyRewriteTask”],
[“JudgeQualityReviewTask”, “AttorneyQualityReviewTask”]]

**Comment by hschallhorn** [comment]
Here are the scenarios and the number of times thee scenario occurs
**A judge leaves the board and the following tasks are cancelled, leaving orphaned child tasks**
 - [ ] `JudgeAssignTask`s with child `ColocatedTask`s (257)
 - [ ] `JudgeQualityReviewTask`s with child `ColocatedTask`s (22)
 - [ ] `JudgeDispatchReturnTask`s with child `ColocatedTask`s (5)
 - [ ] `JudgeQualityReviewTask`s with child `AttorneyQualityReviewTask`s (86)
 - [ ] `JudgeDispatchReturnTask`s with child `AttorneyDispatchReturnTask`s (21)

**An attorney leaves the board and the following tasks are cancelled, leaving orphaned child tasks**
 - [ ] `AttorneyTask`s with child `ColocatedTask`s (2152)
 - [ ] `AttorneyRewriteTask`s with child `ColocatedTask`s (127)
 - [ ] `AttorneyQualityReviewTask`s with child `ColocatedTask`s (18)
 - [ ] `AttorneyDispatchReturnTask`s with child `ColocatedTask`s (5)

**A QualityReview team member leaves the board and the following tasks are cancelled, leaving orphaned child tasks**
 - [ ] `QualityReviewTask`s with child `JudgeQualityReviewTask`s (151)

**A judge leaves the board and the following tasks are cancelled, leaving orphaned child tasks**
 - [ ] `ChangeHearingDispositionTask`s with child `TranscriptionTask`s (1)
 - [ ] `ChangeHearingDispositionTask`s with child `EvidenceSubmissionWindowTask`s (1)

**A LitigationSupport team member leaves the board and the following tasks are cancelled, leaving orphaned child tasks**
 - [ ] `VacateMotionMailTask`s with child `PulacCerulloTask` task (1)

**Comment by hschallhorn** [comment]
**Suggestions**
1. Move the orphaned child tasks to the parent task
 - [ ] `JudgeQualityReviewTask`s child `ColocatedTask`s move to parent `QualityReviewTask`
 - [ ] `JudgeDispatchReturnTask`s with child `ColocatedTask`s  move to parent `DispatchTask`
 - [ ] `AttorneyTask`s with child `ColocatedTask`s  move to new `JudgeAssignTask`
 - [ ] `AttorneyRewriteTask`s with child `ColocatedTask`s  move to parent `JudgeDecisionReviewTask`
 - [ ] `AttorneyQualityReviewTask`s with child `ColocatedTask`s  move to parent `JudgeQualityReviewTask`
 - [ ] `AttorneyDispatchReturnTask`s with child `ColocatedTask`s  move to parent `JudgeDispatchReturnTask`
 - [ ] `ChangeHearingDispositionTask`s with child `TranscriptionTask`s  move to parent `HearinqTask`
 - [ ] `ChangeHearingDispositionTask`s with child `EvidenceSubmissionWindowTask`s  move to parent `HearinqTask`
 - [ ] `VacateMotionMailTask`s with child `PulacCerulloTask` task  move to parent `VacateMotionMailTask`

2. Cancel these tasks as new QR or dispatch tasks will be created for the judge or quality review team member
 - [ ] `JudgeQualityReviewTask`s with child `AttorneyQualityReviewTask`s
 - [ ] `JudgeDispatchReturnTask`s with child `AttorneyDispatchReturnTask`s
 - [ ] `QualityReviewTask`s with child `JudgeQualityReviewTask`s

3. Still pondering this one as the case moves back to the distribution pool. We don't want to move the admin action to the distribution tasks as that will block it from being distributed to a new judge
 - [ ] `JudgeAssignTask`s with child `ColocatedTask`s (257)

**Comment by araposo-tistatech** [comment]
@hschallhorn can you explain what you mean by the first option "Move the orphaned child tasks to the parent task"? My moving it to the parent task do you mean moving it to the user that has that parent task?

**Comment by hschallhorn** [comment]
Here is an example! 

**Currently**: Say an attorney leaves the board and there is a `AttorneyDispatchReturnTask` assigned to them that will now be cancelled and it has a downstream `OtherColocatedTask` (admin action). This would make the parent `JudgeDispatchReturnTask` "assigned" and able to be assigned to a different attorney, but leaves an open `OtherColocatedTask`. This could leave us with a colocated task that never gets completed before the appeal is dispatched.

**Proposed**: "Move the orphaned child tasks to the parent task" means we will make that `JudgeDispatchReturnTask` the parent of the previously orphaned `OtherColocatedTask` tasks. VLJ support an continue working this `OtherColocatedTask` and the judge can assign the a `AttorneyDispatchReturnTask` to a new attorney once the admin action is completed.

### Task trees
**BEFORE REASSIGN**
```ruby
Appeal 17635 (direct_review)                    STATUS    ASGN_TO
└── RootTask                                    on_hold   Bva
    └── BvaDispatchTask                         on_hold   BvaDispatch
        └── BvaDispatchTask                     on_hold   VACOWILLIW
            └── JudgeDispatchReturnTask         on_hold   VACOCARACA
                └── AttorneyDispatchReturnTask  on_hold   VACOPARKT
                    └── OtherColocatedTask      on_hold   Colocated
                        └── OtherColocatedTask  assigned  VACOAUSTIT1
```
**AFTER CANCELLING (CURRENT)**
```ruby
Appeal 17635 (direct_review)                    STATUS    ASGN_TO
└── RootTask                                    on_hold   Bva
    └── BvaDispatchTask                         on_hold   BvaDispatch
        └── BvaDispatchTask                     on_hold   VACOWILLIW
            └── JudgeDispatchReturnTask         assigned  VACOCARACA
                └── AttorneyDispatchReturnTask  cancelled VACOPARKT
                    └── OtherColocatedTask      on_hold   Colocated     <- Orphaned 
                        └── OtherColocatedTask  assigned  VACOAUSTIT1   <- tasks
```
**AFTER CANCELLING (PROPOSED)**
```ruby
Appeal 17635 (direct_review)                    STATUS    ASGN_TO
└── RootTask                                    on_hold   Bva
    └── BvaDispatchTask                         on_hold   BvaDispatch
        └── BvaDispatchTask                     on_hold   VACOWILLIW
            └── JudgeDispatchReturnTask         on_hold   VACOCARACA
                ├── AttorneyDispatchReturnTask  cancelled VACOPARKT
                └── OtherColocatedTask          on_hold   Colocated
                    └── OtherColocatedTask      assigned  VACOAUSTIT1
```

**Comment by araposo-tistatech** [comment]
@hschallhorn regrets, realized I did not add the Boards thoughts to this ticket. They agree with the first two suggestions and would like for the colocated tasks to remain active even if the cases is assigned back to distribution.

**Comment by araposo-tistatech** [comment]
@hschallhorn please let me know if further definition is needed here.

**Comment by hschallhorn** [comment]
> would like for the colocated tasks to remain active even if the cases is assigned back to distribution

The open question is where these should move to. If they remain where they are, the case could be dispatched without the work being completed. If the move to under the distribution task, they will block distribution.

**Comment by araposo-tistatech** [comment]
Sent email to the Board inquire where the colocated tasks should move to.

**Comment by araposo-tistatech** [comment]
What is the concern of having the colocated tasks block distribution? The Board feels this might be the better option since the attorney and/or VLJ would not be able to work the case until those are completed anyone, but they will confirm this with the DVCs.

**Comment by hschallhorn** [comment]
That is true! If that's what the board would like moving forward, that works for me! Happy to finally have a resolution for this

**Comment by hschallhorn** [comment]
**Suggestions**
1. Move the orphaned child tasks to the parent task
 - [ ] `JudgeQualityReviewTask`s child `ColocatedTask`s move to parent `QualityReviewTask`
 - [ ] `JudgeDispatchReturnTask`s with child `ColocatedTask`s  move to parent `DispatchTask`
 - [ ] `AttorneyTask`s with child `ColocatedTask`s  move to new `JudgeAssignTask`
 - [ ] `AttorneyRewriteTask`s with child `ColocatedTask`s  move to parent `JudgeDecisionReviewTask`
 - [ ] `AttorneyQualityReviewTask`s with child `ColocatedTask`s  move to parent `JudgeQualityReviewTask`
 - [ ] `AttorneyDispatchReturnTask`s with child `ColocatedTask`s  move to parent `JudgeDispatchReturnTask`
 - [ ] `ChangeHearingDispositionTask`s with child `TranscriptionTask`s  move to parent `HearinqTask`
 - [ ] `ChangeHearingDispositionTask`s with child `EvidenceSubmissionWindowTask`s  move to parent `HearinqTask`
 - [ ] `VacateMotionMailTask`s with child `PulacCerulloTask` task  move to parent `VacateMotionMailTask`

2. Cancel these tasks as new QR or dispatch tasks will be created for the judge or quality review team member
 - [ ] `JudgeQualityReviewTask`s with child `AttorneyQualityReviewTask`s
 - [ ] `JudgeDispatchReturnTask`s with child `AttorneyDispatchReturnTask`s
 - [ ] `QualityReviewTask`s with child `JudgeQualityReviewTask`s

3. Move to block new distribution task
 - [ ] `JudgeAssignTask`s with child `ColocatedTask`s (257)
