### ISSUE TITLE
Intake Appeals with Granted Substitute Appellants to Caseflow automatically

### ISSUE THREAD

**Issue by D-L-Ware** [department-of-veterans-affairs/caseflow#13131]
## Background/context
In the event that a Veteran dies during the pendency of a claim or appeal a surviving spouse, dependent child, or parent (in that order) are eligible to be substituted to pursue the claim or appeal to completion.  Legal they step into the shoes of the Veteran for the duration of the claim or appeal.  

VBA makes the initial determination about  a person qualifies as a substitute.  As such, if the Veteran dies during the pendency of an appeal (i.e. no decision had been issued prior to death), even if there is a pending request for substitution the Board must ~~return the appeal to VBA for this determination~~ dismiss the case.  ~~This is done through a remand.~~  Thereafter, the AOJ (agency of original jurisdiction) then addresses the substitution request. If ~~VBA~~ AOJ determines someone has substituted (granted) and there was an appeal that was dismissed due to the Veteran's death, they need to return the appeal to the Board without an NOD having been filed. The substitute would take the decedent's place (i.e. retain the original docket number) and the Board would re-adjudicate the appeal on the merits with the substitute as claimant. 

This represents a unique issues for Caseflow as all AMA appeals are initiated by the Board by a 10182 Notice of Disagreement (NOD) and are created as work items in Caseflow by going through the Caseflow Intake process.  In AMA, even in the event the Board remands an appeal to VBA if the Veteran wants to return that appeal to the Board later they have to file a new 10182 NOD.  

This is the one case where Caseflow needs to support the return of an appeal to the Board without an  NOD.

Typical scenario is: 
Veteran has appeal with Board
Veteran passes during the appeal
Board issues a decision (death dismissal)
Substitute has 1 year to submit the substitution request
RO either grants or denies the request - this is done by the field representative (RO contacts them and advises we granted the substitution request) 
In VACOLS a the Board creates a new appeal stream w/ the same Docket number and displaying the substitutes name as the appellant
 

## Goals
In the event a substitution occurs following a Veteran's death, a remanded appeal needs to be able to reenter the Board's inventory/workflow without the filing of a new NOD. 

(Out of Scope) Note, user also articulated a scenario in which the Board is notified of a Veteran's death but there is not appeal.  In this case there will be no remand from the Board on substitution, however, VBA still needs to be notified of the death.  User asked if Caseflow could assist with this, however, at this time, it is unclear if the best resolution to this issue is a Caseflow process or a business process out side of Caseflow.  Exploration of that issue should initially be part of this effort but depending on preliminary findings a separate Epic may be necessary.

## Success criteria
An appeal, in which substitution occurred after a death dismissal, can be entered & processed in Caseflow. 

## Stakeholders
The Board and VBA (specifically Pension and Fiduciary Services that I believe handle the substitution issues)

## Requirements/stories

- [ ] As a Board Field Representative I need to have access to Caseflow, so that when I receive notification that a substitution has been granted I can create a new appeal stream in Caseflow. 

- [ ] As a Board Field Representative, I need the ability to search for an appeal in Caseflow, so that I can locate the case that has been granted substitution. 

- [ ] As a Board Field Representative, I need the ability to create a new appeal stream via the old appeal when a substitution is granted on a case so that a new decision can be issued. 

- [ ] As a Board Field Representative, I need the ability to identify the substituted appellant on the case, so that the new decision is issued to the appropriate appellant. 

- [ ] As a Board Field Representative, when I create a new appeal stream, I need that appeal to be linked to the original docket number, so that when the docket number is searched both the original appeal and new appeal are presented. 

- [ ] As a Board Field Representative when I create a new appeal I need any tasks that were active on the previous appeal before the death dismissal was dispatched to be reopened for this new appeal, so that those tasks are completed prior to the new case being decided.

- [ ] User research, the Board has presented us with a problem "getting remanded appeals with no NOD back into inventory" but how to solve this needs to be looked into.

- [ ] Build solution 

- [ ] Test

- [ ] Launch solution

## Open questions
Do we need a human to be a gateway for these returned appeals or just automatically place them in inventory? We would need human intervention to add it into Caseflow as there is no automated process at this time for receiving the RO grant or denial at the Board. 

What is the solution for when the Board needs to notify VBA of a death Caseflow or business process? This is out of scope for this work.

What state should these appeals be in? Are we reopening to the previous state? 
We are "reopening" to a previous state. Meaning if there were any active tasks not yet completed before the death dismissal decision was issued we would need to reopen or create those tasks again. Essentially, the substitute appellant steps into the shoes of the veteran. 

We would need to know what was active before the death dismissal was issued. For example, if there was a hearing that had already been completed we would not need to reopen that task. 

In the hearings state would the substitute be granted a hearing as well? Yes. 

Who would intake these? Board Field Representative - not currently in Caseflow (within Litigation Support)

What happens if a death dismissal occurred before substitution? Which cases would fall under this Caseflow? This work is to capture substitutions after a death dismissal has occurred not before. 

So if original case had any priority status substitution would absorb the same priority status

Board to find out what occurs if substitution is obtained before case is dismissed <---- create new epic if this is not covered

### Business value
Currently, AMA appeals in which substitution occurred cannot be worked.  As such, building this functionality is not a matter of if but when.     

### Dependencies
This is a process between VBA and the Board any Caseflow functionality created my end up being dependent to some extent on VBMS and/or BGS.

**Comment by carodew** [comment]
Thanks @D-L-Ware! When this gets prioritized I'm happy to help define the research/design approach.

**Comment by araposo-tistatech** [comment]
Identified SMEs for this work: 
Angeline DeChiara - Angeline.DeChiara@va.gov
Jason George - Jason.George6@va.gov
Caroline Fleming - Caroline.Fleming@va.gov
Antoinette Ford - Antoinette.Ford@va.gov
Mike Sanford - Michael.Sanford3@va.gov
Mary Tang - Mary.Tang@va.gov

**Comment by NateMartinTista** [comment]
CASEFLOW-134

**Comment by NateMartinTista** [comment]
...and CASEFLOW-27?
