### ISSUE TITLE
[EPIC] View individual queues of other users

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#13237]
## Background/context
There have been multiple instances where users have requested to see the queues of other users
1. As a VLJ support admin, viewing the individual queues of other team members would eliminate the need for the employee to self-report the information in their queues
1. As a DVC, supervisor, or assistant, viewing the queue of another user will allow me to act on behalf of other judges

Currently, caseflow only supports viewing 
1. The current user's queue `/queue`
1. The queue of an organization `/queue/<organization_url>`
1. The "cases to assign" queue of a judge `/queue/<judge_id>/assign`
   **NOTE** while a user can navigate to the assign queue of a judge, they will be shown their own assign queue. This is due to the fact that we pull tasks assigned to the current user, not the user stipulated with <judge_id>.
1. The queues of attorneys on a judge's team `/queue/<judge_id>/assign/<attorney_id>`

## Goals
Specific users can view the queues of other individuals

|User can view|Queue of another user|
|---|---|
|Organization Admins|Members of the team they are an admin of|
|CaseMovement team members|Judge assign queue|
|CaseMovement team members|Judge decision queue|

## Stakeholders
Organization admins, DVCs and their assistants, and VLJ supervisors.

## Requirements/stories

- [x] Limit viewing of judge assign queues to judges (and their judge team admins behind `judge_admin_scm` feature flag)
- [x] `/queue/<judge_id>/assign` should show the assign queue of <judge_id>, not the current user (touches #12423)
- [x] Add judge assign page to judge team admin dropdowns (#13144, behind `judge_admin_scm` feature flag)
- [ ] Create new route for an individual queue `/queue/<user_id>`
- [ ] Limit viewing of another user's queue to admins of teams that user is on
- [ ] Refactor queue front end to accept a user_id
- [ ] Add individual team member queues to the dropdowns of team admins

## Open questions
- [ ] How should users be able to access these queues?
  Proposed: Update `user.selectable_organizations` to return links to these queues in their queue dropdown. 

## References/Resources

Reference `AssignedCasesPage` for implementation. I believe this is the only place we correct show the queue and tasks of a user other than the current user
