### ISSUE TITLE
Design audit of Caseflow and the design system

### ISSUE THREAD

**Issue by carodew** [department-of-veterans-affairs/caseflow#13323]
## Problem statement

The style guide is outdated and hasn’t been maintained. Patterns in the style guide don’t match what is in Caseflow, and the same pattern is handled differently in different areas of Caseflow. This makes maintenance and updates difficult and creates an inconsistent user experience.

It is difficult to prioritize work on the style guide against desire to ship new features. However, spending some time maintaining the style guide can help future features ship more quickly.

## What is out of scope?

Out of scope is implementing any updates to the style guide (yet!).

## What questions do we hope to answer? What are our learning goals?

- [ ] What design system updates should we prioritize first? 
- [ ] What UI patterns in Caseflow are most problematic for users? 
- [ ] What UI patterns in Caseflow are most problematic for designers and developers in Caseflow (maintainability and use?)

## Deliverables

- [ ] Ranked list of what design and content patterns should be addressed first (at least five components or patterns, target 7-10), plus documentation of prioritization criteria (rationale for this recommendation)
- [ ] Design / content audit - collection (for example, screenshots) of design and content patterns across the style guide and across Caseflow products. 
  - [ ] Identification of where there are discrepencies or inconsistencies in the patterns (for example, table sorting is handled differently in different parts of the Caseflow application, and isn't included in the style guide at all). 
- [ ] Findings around which components represent the biggest pain points for developers and designers working with them (any research here should be lightweight – think a workshop or async activity). 

## Activities 
- [ ] Design and content audit 
- [ ] Audit GitHub issues with label `project: design-style-guide`
- [ ] Lightweight research or workshop with engineers and designers to identify biggest pain points/needs (this should take no more than one week from start to finish) 
- [ ] Synthesis and recommendations 
- [ ] Present findings and recommendations to Caseflow team at Wisdom Wednesday and discuss next steps

### Phase 1: Design audit
- [ ] Get access to Caseflow prod 
- [ ] create the audit documentation: Document/capture all design styles/components within the style guide on one page (Mural or Figma) (1-2 days)
- [ ] Find examples of these styles/components in Caseflow prod, screen cap and add to the audit document (you will likely find different styles of the same component in different parts of the Caseflow app) (2-3 days, once you have access). Note where you found the pattern within the app. 
- [ ] Note in the audit document where there are discrepancies 
- [ ] Stretch goal: document UI elements and components that exist in production that are not part of the style guide.

### Phase 2: Styleguide issues
- [ ] Search for all GitHub issues labeled `Project: design-style-guide` – both open and closed issues
- [ ] Note on the audit document if any of the tickets address components or discrepancies found so far.  (1-3 days)

### Prioritization workshop 

- [ ] Write up a proposal for a workshop to have with the Caseflow team (include all disciplines but esp. engineering and design) that will identify what components are the hardest to work with and implement.
