### ISSUE TITLE
Queue: Adding New Contentions

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#13423]
## Background/context
Under law and regulations, a Veteran who served in Vietnam from January 9, 1962, to May 7, 1975 is presumed to have been exposed to herbicides. Furthermore, a particular set of medical conditions are presumed to be service connected for anyone who has been exposed to herbicide. Historically, the definition of "served in Vietnam" has been limited to Veterans who served on the landmass of Vietnam or its inland waterways, also know as brown water.

Last year both a court decision and bill passed by Congress expanded the presumption of exposure to herbicide during that time period to any Veteran who served within not more than 12 nautical miles from the coast of Vietnam, also know as blue water.

The goal of this project is to provide the Board for the Board of Veterans’ Appeals the ability to flag/mark Blue Water along with MST, Burn PIT, and CAVC contentions in Caseflow for congressional data capture purposes only. 

## Goals
Support the ability to add Blue Water, MST, Burn PIT, and CAVC as contentions in Case Flow

## Success criteria
Launch special interest/contention marking functionality without work stoppage bugs

## Stakeholders
Attorneys
Judges

## Requirements/stories

- [ ] [Legacy Appeals: Add special issues](https://github.com/department-of-veterans-affairs/caseflow/issues/13396)
- [ ] [Special Issues Page: Add Validation](https://github.com/department-of-veterans-affairs/caseflow/issues/13735)
- [ ] [AMA: Add Special Issues Page](https://github.com/department-of-veterans-affairs/caseflow/issues/13736)
- [ ] [Remove "(optional)" from special issues page for legacy appeals](https://github.com/department-of-veterans-affairs/caseflow/issues/9638)

## Open questions
What format will the data need to be supplied in for reporting team? Engineering to work with reporting team on this. 

## References/Resources
[Product Brief](https://docs.google.com/document/d/15izpJwUTYP7yE0SHrdLP1tsGmbLGdIOqpEOHDyLwqDo/edit#)

### Designs and workflows
Special Issues Page for judges & attorneys. Note judges will be able to see any selections made by the attorney (this functionality already exists). 

Legacy: 
![Legacy Appeals_Special Issues](https://user-images.githubusercontent.com/59883609/76990375-407b9e00-691e-11ea-99d5-59497f5b371b.png)

Legacy error if no option chosen: 
![Legacy Appeals_Special Issues_error if no option chosen](https://user-images.githubusercontent.com/59883609/76990434-54270480-691e-11ea-9613-fe8f9b27e114.png)

AMA (new page addition): 
![AMA Appeals_Special Issues_mockup](https://user-images.githubusercontent.com/59883609/76990469-60ab5d00-691e-11ea-946c-f417a2769604.png)

AMA error if no option chosen: 
![AMA Appeals_Special Issues_mockup_error if no option chosen](https://user-images.githubusercontent.com/59883609/76990501-6bfe8880-691e-11ea-803b-81abdc0b297b.png)

### Business value
Providing the BVA with the ability to capture data in Caseflow for congressional reporting purposes.

### Dependencies
None

**Comment by araposo-tistatech** [comment]
@carodew @geronimoramos Can we add the contentions mock-ups we spoke about to this ticket so I can run them by the board for approval. Once that is complete, the engineering team should be able to begin the work on this.

**Comment by carodew** [comment]
@araposo-tistatech I thought we discussed that we didn't need mock ups, since we thought we could just have the engineers put together a page that follows the format of the current "add special issues" page in the check out flow. Am I misunderstanding?

**Comment by araposo-tistatech** [comment]
@carodew yes, but I did prefer to have at least screenshots to provide to the board, before engineering begins the work. In any case, I may be able to mock something up myself so feel free to disregard. 

Thanks!

**Comment by carodew** [comment]
Gotcha – let me know if you need help.

**Comment by araposo-tistatech** [comment]
@hschallhorn Below are the VLJs who have authorized us to use their teams to pilot with: 

Laura Collins
Nate Doan
Margie Auer

Depending on how many attorneys each VLJ has on their team we may want to limit this. Can we easily pull how many attorneys are on each team?

**Comment by hschallhorn** [comment]
```ruby
names = ["LAURA COLLINS", "NATHANIEL DOAN", "MARJORIE AUER"]
judges = User.where(full_name: names)
judges.count
=> 3
judges.all?(&:judge_in_vacols?)
=> true
judges.map { |judge| JudgeTeam.for_judge(judge).attorneys.count }
=> [9, 7, 8]
pp judges.map { |judge| [judge.full_name, JudgeTeam.for_judge(judge).attorneys.map(&:full_name)] }.to_h
{"MARJORIE AUER"=>
  ["AMANDA PURCELL",
   "ESTHER KIM",
   "JOHN MIDDLETON",
   "ANDREW AHLBERG",
   "SHAUNA WATKINS",
   "KELLY GASTOUKIAN",
   "ADAM DOUGAN",
   "KELSEY LOVE",
   "MARTIN PETERS"],
 "LAURA COLLINS"=>
  ["MELISSA CARSTEN",
   "ALLEN KERPAN",
   "PAUL BAMETZREIDER",
   "ANTHONY HINES",
   "SARONE SOLOMON",
   "KATHRYN BRISTOR",
   "SAMANTHA CONTI"],
 "NATHANIEL DOAN"=>
  ["CLAIRE ROBINSON",
   "KELLYE THOMPSON",
   "ADRIAN JACKSON",
   "ASHLEY DEAN",
   "AMANDA GIBSON",
   "MARIANA MINAYA",
   "KRYSTAL WILSON",
   "KATHRYN BLEVINS"]}
```
24 attorneys in all

**Comment by araposo-tistatech** [comment]
First Response: 
Laura Collins - PAUL BAMETZREIDER & KATHRYN BRISTOR

Awaiting the remaining users

**Comment by araposo-tistatech** [comment]
Completed a walk through of the new additions with the pilot users. They are ready to begin the pilot session, let me know if 10am tomorrow works for you.

**Comment by araposo-tistatech** [comment]
epic was completed, closing
