### ISSUE TITLE
Tango team planning

### ISSUE THREAD

**Issue by chandracarney** [department-of-veterans-affairs/caseflow#13626]
This is an epic to track Tango's sprint goals.

## Emojis
⭐️ - New work
💅 - Design work
☘️- Bonus work (not committed)
✅- Did it!
↪️- Tickets carried over from before
👾 - Extra work pulled in
❌ - Decided not to do
🛑 - Blocked at the end of the sprint

**Comment by chandracarney** [comment]
# American Revolution sprint (Mar 9 - Mar 23) engineering priorities
- Batteam week of 3/16/20

## Priorities
### Virtual Hearings pilot readiness
1. ↪️Virtual Hearings incorrect time on email reminder
2. ↪️Update Pexip URL and theme ID
3. ↪️Run through end-to-end virtual hearings flow

### Gen2 virtual hearings pilot
1. ⭐️Observe first virtual hearing pilot users

### Rep and state of residence column
1. ↪️Add Pagination and PoA to Assign Hearings
2. ⭐️Display Veteran's state of residence on Schedule Veterans screen

## Bonus set
### Virtual hearings pilot
1. ⭐️Refresh page data after virtual hearing job is completed
2. ↪️Can't change a formerly virtual hearing back to virtual

**Comment by chandracarney** [comment]
# American Revolution sprint (Mar 9 - Mar 23) priorities
- Batteam week of 3/16/20

## Priorities
### Virtual Hearings pilot readiness
1. ↪️✅ Virtual Hearings incorrect time on email reminder
2. ↪️✅ Update Pexip URL and theme ID
3. ↪️ Run through end-to-end virtual hearings flow (#13609)
4. 👾✅ Resolve Pexip and credential issues for virtual hearings (#13763)
5. 👾✅ In virtual hearing emails sent to judges, show the hearing time in the central office timezone (#13732)
6. 👾✅ Make hearing times in virtual hearings emails consistent across templates (#13749)


### Gen2 virtual hearings pilot
1. ⭐️Observe first virtual hearing pilot users

### Rep and state of residence column
1. ↪️✅ Add Pagination and PoA to Assign Hearings
2. ⭐️✅ Display Veteran's state of residence on Schedule Veterans screen

## Bonus set
### Virtual hearings pilot
1. ⭐️ Refresh page data after virtual hearing job is completed
2. ↪️ Can't change a formerly virtual hearing back to virtual (#13328)

**Comment by chandracarney** [comment]
# __ sprint (April 7 - April _) priorities

## Priorities
### Gen2 virtual hearings pilot
1. ↪️ [in progress] Observe first virtual hearing pilot users (#13661)

### Virtual hearings work
1.↪️ Store information related to virtual hearing emails (#13751)
2.⭐️ Hearing Details layout updates (#13752)
3.⭐️ Create new non-admin Hearing Coordinator demo user (#13854)
4.↪️ [in progress] Switch already-scheduled Central Office hearing to Virtual hearing (#13804)
5.↪️ [in progress] Research: new hearing type of virtual (#13431)
6.⭐️Derive status of virtual hearing instead of using the status field (#13778)
7.⭐️Frontend changes to display info about virtual hearing emails sent (#13753)

## Bonus set
2. ↪️ Can't change a formerly virtual hearing back to virtual (#13328)

**Comment by chandracarney** [comment]
# Library of Congress Sprint 4/20/2020 - 5/1/2020
_Ferris on Batteam April 20-25_

## Priorities
### Gen2 virtual hearings pilot
1. [Design in progress] Observe first virtual hearing pilot users (#13661)

### Virtual hearings work
1.↪️ [in progress] Store information related to virtual hearing emails (#13751)
2.↪️[in review] Determine Veteran's Timezone from Address (#13889)
3.⭐️[in review] No validation when saving email on Hearing Details page (#13915)
4.⭐️Display of alerts after virtual hearing is switched back to video (#13944)
5.⭐️Frontend changes to display info about virtual hearing emails sent (#13753)
6. ⭐️Move hearings details state from Redux to React Context (#13868)
7. ⭐️Refactor how VirtualHearingModal is shown (#13869)
👾Use generation one format for virtual hearing URLs (#14053)
👾Technical Documentation of Virtual Hearing DB Schemas (#14067)
👾Change length of Pexip pin (#13856)


## Bonus set 
Document Hearing models and data flow (#10846)
Cannot read property 'disposition' of undefined (#13208)
Renaming Hearings Details Components (#13871)

**Comment by chandracarney** [comment]
# David Hunter Sprint 5/4/2020 - 5/15/2020

## Priorities
### Gen2 virtual hearings pilot improvements
1. 💅[Design in progress] Observe first virtual hearing pilot users (#13661)
2. Change length of Pexip pin (#13856)

### Virtual hearings tech improvements
2.⭐️❌ Move hearings details state from Redux to React Context (#13868)

## Virtual hearings (next use cases)
1.⭐️💅 [Design in progress] Switch already-scheduled Central Office hearing to Virtual hearing (#13804)
2.↪️ [in review] Determine Veteran's Timezone from Address (#13889)

## Hearings sentry alerts, tech improvements
↪️ Document Hearing models and data flow (#10846)
↪️ Cannot read property 'disposition' of undefined (#13208)

**Comment by chandracarney** [comment]
# Amelia Earhart Sprint 5/18/2020 - 5/29/2020
- Tomas on batteam 5/18/20 - 5/22/20

## Priorities

## Virtual hearings national rollout improvements

## Virtual hearings (next use cases)

## Hearings sentry alerts, tech improvements

## Other products (IDT, eFolder)

**Comment by chandracarney** [comment]
# March Against Fear Sprint 6/1/2020 - 6/14/2020

## Priorities

### Virtual hearings bugs/triage

### Virtual hearings (next use cases)
⭐️ Build out feature flag for Central Office-to-virtual conversions (#14387)
⭐️ Determine Veteran's Timezone from Address (#13889)
⭐️ Investigate new path for Convert to Virtual page (#14389)
⭐️ Add section cards, adjust layout and style of Hearing Details page (#14388)
⭐️ Create timezone dropdown component (#14420)
☘️⭐️ Build new Convert to Virtual page for Central Office hearings (#14421)
☘️⭐️ Store Appellant/Veteran and POA timezone in database (#14386)
↪️ [in progress] Ensure conditional logic can handle "virtual" type (#13957)
☘️ Research: compatibility with legacy hearings (#13956)

### Hearings sentry alerts, tech improvements
↪️🛑  [in progress] Hearing withdraw routing logic (#14129)
☘️🛑 Introduce granularity between VSOs and state / regional VA organization (#14297)
↪️ Collect and report all cases where an EvidenceSubmissionWindowTask was prematurely closed (#14082)
⭐️Unexpected error response from saving hearing causes TypeError (#14187)

### Other products (IDT, eFolder)
↪️ investigate failed DecisionDocument jobs (#14079)

**Comment by chandracarney** [comment]
# March Against Fear Sprint 6/1/2020 - 6/14/2020

## Priorities

### Virtual hearings bugs/triage/enhancements
⭐️ change the from address for virtual hearings emails (#14504)

### Virtual hearings (next use cases)
↪️ [in progress] Investigate new path for Convert to Virtual page (#14389)
⭐️ Create timezone dropdown component (#14420)
⭐️ Build new Convert to Virtual page for Central Office hearings (#14421)
↪️ Store Appellant/Veteran and POA timezone in database (#14386)
↪️ [in progress] Ensure conditional logic can handle "virtual" type (#13957)
☘️ [in progress] Research: new hearing type of virtual, compatibility with legacy hearings (#13956)

### Hearings sentry alerts, tech improvements
⭐️ Disallow Veterans to be matched cross-state lines for hearing scheduling (#14519)
↪️🛑 Introduce granularity between VSOs and state / regional VA organization (#14297)
↪️🛑 Hearing withdraw routing logic (#14129)
⭐️ Set up report for days waiting in scheduling queue(s) (#14301)
↪️ Collect and report all cases where an EvidenceSubmissionWindowTask was prematurely closed (#14082)

### Other products (IDT, eFolder)
↪️ investigate failed DecisionDocument jobs (#14079)

**Comment by chandracarney** [comment]
# Thurgood Marshall 6/29/2020 - 
- batteam week of 6/29

## Priorities

### Virtual hearings bugs/triage/enhancements

### Virtual hearings (next use cases)
⭐️ Build new Convert to Virtual page for Central Office hearings (#14421)
↪️ [in review] Store Appellant/Veteran and POA timezone in database (#14386)
↪️ [in progress] Ensure conditional logic can handle "virtual" type (#13957)
☘️🛑  Research: new hearing type of virtual, compatibility with legacy hearings (#13956)

### Hearings sentry alerts, tech improvements
⭐️ Make the DocketRangeJob idempotent and schedule it to run at the end of each month (#14455)
⭐️ Disallow Veterans to be matched cross-state lines for hearing scheduling (#14519)
↪️ Introduce granularity between VSOs and state / regional VA organization (#14297)
↪️🛑 Hearing withdraw routing logic (#14129)
↪️ Set up report for days waiting in scheduling queue(s) (#14301)
↪️ Collect and report all cases where an EvidenceSubmissionWindowTask was prematurely closed (#14082)

### Other products (IDT, eFolder)
↪️ investigate failed DecisionDocument jobs (#14079)

**Comment by chandracarney** [comment]
# Sea of Tranquility sprint 7/13/20 - 7/16/20
- batteam week of 7/20

## Priorities

### Virtual hearings bugs/triage/enhancements

### Virtual hearings (next use cases)
☘️🛑  Research: new hearing type of virtual, compatibility with legacy hearings (#13956)

### Hearings sentry alerts, tech improvements
↪️ Introduce granularity between VSOs and state / regional VA organization (#14297)
↪️🛑 Hearing withdraw routing logic (#14129)

### Other products (IDT, eFolder)

**Comment by chandracarney** [comment]
# Voting Rights Act sprint 7/27/20 - 8/9/20
- batteam week of 8/3

## Priorities

### Virtual hearings bugs/triage/enhancements
Geo-matching rate limiting:


### Virtual hearings (next use cases)
- [ ] ⭐️  Investigate increase in hearing schedule days/rooms (#14769)
- [ ] ↪️ End-to-end test Central-to-virtual flow (#14643)
  - UAT was down, blocking us from completing last sprint
  - There will be some new work coming out of end-to-end testing:
- [ ] Hearing time displays incorrectly when converting central to virtual (#14779)

☘️🛑 Research: new hearing type of virtual, compatibility with legacy hearings (#13956)
⭐️ Fix issue on assign hearings page where multiple dockets with the same date get highlighted simultaneously (#14673)

### Hearings sentry alerts, tech improvements
- [ ] ↪️🛑 Introduce granularity between VSOs and state / regional VA organization (#14297)
  - The Branch needs to define requirements
- [ ] ↪️🛑 Hearing withdraw routing logic (#14129)
- [ ] ⭐️💅 Redesign Withdraw Scheduled Hearing workflow and copy (#14145)

### Other products (IDT, eFolder)

**Comment by lund5000** [comment]
# Edith Sampson Sprint (8/24/20 – 9/4/20)

## Priorities

### Launch full-page flow and conversion of Central Office to virtual
[ ] ⭐️ Can't reselect "no timezone" option on hearing details page (#14989)
[ ] ⭐️ Email notification history does not display new email sent events after changing a hearing to Virtual (#14988)
[ ] ⭐️ (#14990)
[ ] ⭐️ (#14991)
[ ] ⭐️ (#14992)

### Schedule directly to virtual
[ ] ↪️ (#14894)
[ ] ⭐️ Refactor AssignHearingModal to ScheduleVeteran wrapper (#15029)

### Convert unscheduled hearing type to virtual
[ ] ⭐️ On the case details page, change the label for appeal type from "TYPE" to "APPEAL STREAM TYPE" (#15020)
[ ] ⭐️ At the top of the case details page, display the hearing type (#15021)

### Hearing task routing enhancements
[ ] ☘️ Introduce granularity between VSOs and state / regional VA organization #14297

**Comment by lund5000** [comment]
# PI5-S3 (9/8 – 9/18) _tentative_

## Convert Travel Board hearing to virtual or video
- [ ] Convert unscheduled Travel Board hearing to virtual (#15053)

## Initiate hearings as virtual
- [ ] Editable RO field on Schedule Veterans page (#15060)

## Hearing task routing enhancements
- [ ] TBD

**Comment by lund5000** [comment]
# PI5-S4 (9/21 – 10/2) _tentative_

## Convert Travel Board hearing to virtual or video
- [ ] Convert unscheduled Travel Board hearing to video (#15073)
- [ ] Missing email alert when converting to virtual (#15056)
- [ ] Identify hearing request type in scheduling queue (#15058)
- [ ] Identify former Travel Board hearings in scheduling queue (#15059)

**Comment by lund5000** [comment]
# PI5-S5: TBD (10/4 – 10/16)

## Epic: Convert Travel Board hearings to virtual (#14857)
- [ ] **Missing email alert when converting to virtual (#15056)**
    - Story: As a hearing coordinator, I need to know when the Veteran doesn't have an email in VBMS as I’m converting a hearing to virtual so I can fix that before scheduling.
- [ ] **Editable RO for virtual hearings (#15060)**
    - Story: As a Hearing Coordinator, I want to be able to select a different Regional Office when I'm scheduling a virtual hearing because sometimes I receive high-priority scheduling requests and I need access to any available docket day space.
- [ ] **Spike: Investigate filtering by hearing type (#15203)**
    - Story: As a hearing coordinator, I want to filter the lists of veterans waiting to be scheduled by their requested hearing type, so I can prioritize and schedule them more quickly and in the right order.

## Defects
- [ ] **The blue "scheduling" alert is never replaced by a green "scheduled" alert after scheduling a hearing straight to virtual (#15362)**
- [ ] **A ChangeHearingRequestTypeTask is created for dispatched legacy appeals (#15363)**
    - Visiting the Case Details page of a dispatched legacy appeal with a Travel Board hearing gives the user the option to convert the hearing request to virtual. This could lead to hearings inappropriately being scheduled for dispatched appeals.

**Comment by lund5000** [comment]
# PI5-S6: Dizzy Gillespie Sprint (10/19 – 10/30)

## Epic: Convert Travel Board hearings to virtual (#14857)
- [ ] **Move legacy appeals to CASEFLOW location only when conversion from Travel Board to virtual has been completed (#15427)**
- [ ] **Show converted Travel Board hearings in RO queue immediately (#15426)**
    - Story: As a hearing coordinator, I want hearings that I convert from Travel Board to virtual to show up in the RO queues (more or less) immediately so I can more quickly shift to building dockets.

## Epic: Hearing task routing enhancements (#14393)
- [ ] **Research: Introduce granularity between VSOs and state / regional VA organization (#14297)**

**Comment by lund5000** [comment]
# PI5-S8: TBN (11/16 – 11/25)


Issue key | Summary | Epic Link
-- | -- | --
[CASEFLOW-337](https://vajira.max.gov/browse/CASEFLOW-337) | Give attorneys access to hearing worksheets |  
[CASEFLOW-268](https://vajira.max.gov/browse/CASEFLOW-268) | Test vc.va.gov link generation | [Migrate hearing links to vc.va.gov](https://vajira.max.gov/browse/CASEFLOW-239)
[CASEFLOW-262](https://vajira.max.gov/browse/CASEFLOW-262) | Defect: Veteran notification sent with odd time |  
[CASEFLOW-227](https://vajira.max.gov/browse/CASEFLOW-227) | Research: Existing build schedule functionality | [Bulk build virtual-only docket days](https://vajira.max.gov/browse/CASEFLOW-130)
[CASEFLOW-223](https://vajira.max.gov/browse/CASEFLOW-223) | Research: National virtual queue feasibility | [National Virtual-Only Queue and Docket Days](https://vajira.max.gov/browse/CASEFLOW-48)
