### ISSUE TITLE
Trigger receipt of completed IHPs to Attorneys & VLJs

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#13700]
## Background/context
At this time IHP writing POAs automatically receive IHP tasks for appellants in the following scenarios: 

- When the veteran's 90 day window for evidence submission is complete. 
- Post intake for direct docket AMA cases
- Any time Caseflow identifies a new representative for an appellant and they are an IHP writing POA

When the task is assigned to a VSO organization, any member of that VSO may assign it to another user, complete, or cancel the task. When assigned to a VSO member, they can reassign the task, place it on hold, complete, or cancel the task. Any admin of the VSO organization can reassign any task assigned to that VSO's members. 

If an IHP task is not automatically assigned to an IHP writing POA then the VLJ and/or Attorney have the ability to add an admin action on the case requesting an IHP task be completed. These tasks are routed to the VLJ Support team. The VLJ Support team then routes a 3230 via email to the POA on the case and awaits completion. VLJ Support is notified of the completion of IHP tasks on legacy cases via a report they pull in VACOLS against location 902. Once aware of what IHPs are ready for review and upload, the VLJ Support team then locates that POAs file via a shared drive. For AMA cases there is no report available so they check the shared drive once a day. This process typically takes 2-3 hrs/day per VLJ Support employee. 

In all cases (automated & non-automated) VLJs, and Attorneys do not receive any immediate notification or indication when the IHP task is completed which causes delays in case movement.

## Goals
Attorneys and VLJs, are notified of a completed IHP task via an indicator, receipt, or notification. 

## Acceptance criteria 
- [ ] VLJ and/or attorney is able to immediately identify when a POA has completed their IHP task via either a notification, receipt, or indicator

## Success criteria
- [ ] Decreased time between completion of IHP and Attorneys/VLJs picking the case back up

## Stakeholders
VLJ
Attorneys

## Requirements/stories

- [ ] User Story: As a VLJ Support Staff member, I want to see added context or an identifier on the task column of my queue page, so that I can identify when an IHP task has been completed. #15404
- [ ] User Story: As a VLJ and or Attorney, I want to see added context or an identifier on the days waiting column of my queue page, so that I can identify when an IHP task has been completed. #15405 

## Open questions
~~What should the notification/indicator look like?~~

### Designs and workflows
[Link to Mural](https://app.mural.co/t/workqueue2001/m/workqueue2001/1595518321333/a3929ce45595dca9177fe2adfd3cb3d6e3203fbd) workflow
[Link to designs](https://www.figma.com/file/awxxww4bQNzgr4wP4vdh8Y/IHP-Attorney-and-Support?node-id=0%3A1) in Figma

**Comment by pshahVA** [comment]
Category | Metric | Applicable? | Approx Impact | Notes
-- | -- | -- | -- | --
Reach | Veterans Impacted (annually) |   |   |  
Users   Impacted |   |   |  
Technical   Complexity | Level of effort |   | Medium |  
Alignment to Goals and ability to measure success | Increase adoption of caseflow?   (estimated increase in # of users) |   |   |  
Support   more appeal types? (estimated increase in # appeals) |   |   |  
Increase   timeliness of claims? | x |   | Caseflow users will know when an   IHP is completed
Increase   system ease of use? | x |   |  
Better   Veteran experience? | x |   | Process claims faster
Increase   accuracy of appeals? |   |   |  
Timeliness | Increase speed of legacy   inventory processing? | x |   |  
Increase   speed of decision processing? (Which docket/lane) | x |   |  
Task   time (how long does the task take today, how much faster could it be?) | x |   |  
Cost of Inaction | Is there a political impact if   we don’t do this? |   |   |  
Number   of Veterans or claims impacted is low, but the damage is high. |   |   | Veterans should handle NOD with   tact and caution.
Damage   to VA reputation. |   |   |  
VACOLS | Does this deprecate a feature in   VACOLS? |   |   |
