### ISSUE TITLE
Store information related to virtual hearing emails

### ISSUE THREAD

**Issue by chandracarney** [department-of-veterans-affairs/caseflow#13751]
### Description
To display information about virtual hearing emails to Veterans and their PoAs, and to triage in bat team, write a tech spec for backend changes in order to create new table to:
- Store email type, email subject line, and/or preview
- The initial hearing time included in the sent email

### Acceptance criteria
- [x] write a tech spec for backend changes ... #13907
- [x] implement schema changes ... #14005
- [ ] save email events to database ... #14027
- [ ] Check data is successfully saved in production

### Background/context/resources
This work has been broken out from Display more info about sent Virtual Hearings emails (#13370), which was based on usability testing with Hearing Coordinators (#12960)
