### ISSUE TITLE
Create a Content Style Guide for Caseflow

### ISSUE THREAD

**Issue by carodew** [department-of-veterans-affairs/caseflow#13834]
@lakohl commented on [Sun Jul 01 2018](https://github.com/department-of-veterans-affairs/appeals-team/issues/925)

## Develop and apply guidance for content within Caseflow 

**Create a Plan of Work**
- [x] Review the needs outlined below and identify any additional work required to define and implement a Caseflow Content Strategy
- [x] Create a plan and schedule for tackling the items below + any additional work required
- [ ] Create Github tickets for copy and content updates for Product Owners, Designers, Support, and Training to review and for developers to implement.
- [ ] Share Caseflow Content Strategy, glossary, and examples of updates made in a presentation to the wider Caseflow team

**Content Strategy**
- [x] Develop guidelines for a Caseflow Content Strategy principles https://github.com/department-of-veterans-affairs/appeals-design-research/issues/1104 
- [x] Create examples of Dos and Don’ts from: 1) copy within a UI, 2) a Caseflow error message, 3) a Support message, 4) Training Materials
- [ ] Add a Content Strategy (Communication) section to Caseflow Commons
- [ ] Provide guidance on how to apply and add to Caseflow Content Style Guide
- [x] AMA letters & content review/crosscheck [#917](https://github.com/department-of-veterans-affairs/appeals-design-research/issues/917)

**Terminology**
- [ ] Develop a glossary of terms commonly used in the VA Appeals process and throughout Caseflow
- [ ] Define each of these terms
- [ ] Review the glossary with the Design team
- [ ] Add the glossary to Caseflow Commons

**Content Audit**
- [ ] Review existing Caseflow copy and labels using [caseflowdemo](http://www.caseflowdemo.com/help) See https://github.com/department-of-veterans-affairs/appeals-design-research/issues/1036 
- [ ] Meet with Design/Product Owners of each Caseflow product to understand how they are using terminology within their application
- [ ] Perform a content audit of Caseflow products in order to better align them with each other. Determine where:
  - language is inconsistently applied, e.g. different terms are being used to refer to the same thing
  - tone and position of address is inconsistent
  - message copy can be improved and made to be more consistent
- [ ] Share findings and recommendations with the Design team (Determine the best means to do this)

**Support Team**
- [ ] Work with the Support team to understand the different types of messages they send out to users
- [x] Review examples of past/existing Support messages and provide guidance for future messaging
- [ ] Work with the Support team to update copy for the 5-10 most common Support messages
- [ ] Work with the Support team to create template messages for Caseflow Status messaging

**Training**
- [ ] Review existing Caseflow training materials
- [ ] Make recommendations for updates to training materials based on Caseflow Content Strategy guidelines
- [ ]  In conjunction with the Training team, ensure that the Training Materials are updated to reflect copy updates to Caseflow products and the latest glossary language

---

@lakohl commented on [Sun Jul 01 2018](https://github.com/department-of-veterans-affairs/appeals-team/issues/925#issuecomment-401628694)

@amiklik I made this issue as a way to explain Caseflow's current content needs and to get you started on a plan of attack. Let me know your thoughts. Feel welcome to edit, add to, and re-order the information above and to break it into smaller tickets.

---

@lakohl commented on [Wed Jul 18 2018](https://github.com/department-of-veterans-affairs/appeals-team/issues/925#issuecomment-406012921)

@amiklik, @annienguyenUSDS has created a separate issue for AMA content: https://github.com/department-of-veterans-affairs/appeals-design-research/issues/917

---

@lakohl commented on [Tue Jul 31 2018](https://github.com/department-of-veterans-affairs/appeals-team/issues/925#issuecomment-406062263)

For the Content Audit, here are some of the types of content that could benefit from consistent labels and/or consistent display of content:

- A unique number assigned to a Veteran/claim file e.g. veteran id, VBMS ID, c-file number, claim number
- The entire collection of claims-related documents for a single Veteran e.g. claims folder, efolder, c-file, case file
- A VA Regional Office (generic and specific)
- An issue description
- Appeal/case details
- EP/ End Product / work order
