### ISSUE TITLE
Handling contested claimants

### ISSUE THREAD

**Issue by carodew** [department-of-veterans-affairs/caseflow#13839]
@abbyraskinUSDS commented on [Thu Sep 20 2018](https://github.com/department-of-veterans-affairs/appeals-team/issues/995)

[Placeholder]

Putting a sierra tag as a placeholder, since this will likely need to be tracked during intake, but we can figure out who/how later

Talked to Emily and Rachel

## Scenario
- There are different scenarios. Often, there are two widows claiming the benefits... 
- Apportionment = attorney/vet have agreement to share benefits
- Can happen before or after the NOD
- Claims for apportionment will already be flagged by VBA. 
- Surviving spouse + apportionment are the most common.

## At intake
- Claimant is not the Veteran -> relationship = surviving spouse?
- Do we have a way to identify apportionment cases in BGS/VBMS?
- Provide hints about keywords w/ the issues?

## But 
- Could be survivor that isn't a contested claim

- We should define a set of rules for the Intake team

## TODO
- Asking Pension about the circumstances under which "Survivor benefit (Pension)" is a Contested Claim

## Notes
Contested Claims, Apportionment issues are ALWAYS contested claims
- prevent these non rating issues in HLR and SC

---

@abbyraskinUSDS commented on [Thu Sep 20 2018](https://github.com/department-of-veterans-affairs/appeals-team/issues/995#issuecomment-423321706)

- Apportionment has a specific form you have to fill out.

---

@abbyraskinUSDS commented on [Thu Sep 20 2018](https://github.com/department-of-veterans-affairs/appeals-team/issues/995#issuecomment-423322075)

- Need full list of possible issues that could be contested, if those are on the appeal, validate that it's contested, notify...??

---

@shanear commented on [Fri Nov 16 2018](https://github.com/department-of-veterans-affairs/appeals-team/issues/995#issuecomment-439429008)

Info from Jennifer Williams:
 
> We know contested claims issues should be ineligible for HLR, but should they also always be ineligible for Supplemental Claim?

Yes

> What about Remand/DTA error supplemental claims?|

They are not ineligible for this category as they will go to the Board for review and if they remand we will need to correct the actions.  So we will have Remand EPs established and worked. 
 
> How was the information for the contesting claimant found when intaking legacy appeals? Where did a CA look for that information?

They check the dependent tab.  Most contested claims are filed by dependents or individuals who are saying they are a dependent such as two wives vying for the same benefit.  Also Attorney fees are contested claims and that would be the POA tab to see if the person is the POA.  So they check the systems and the eFolder.

---

@shanear commented on [Fri Nov 16 2018](https://github.com/department-of-veterans-affairs/appeals-team/issues/995#issuecomment-439479728)

This list was confirmed:

Always contested claims
Apportionment
Contested Claims (other than apportionment)

Sometimes contested claims
*there are no categories that are sometimes contested claims

Never contested claims
Incarceration Adjustments
Audit Error Worksheet (DFAS)
Active Duty Adjustments
Drill Pay Adjustments
Character of discharge determinations
Income/net worth (pension)
Dependent child - Adopted
Dependent child - Stepchild
Dependent child - Biological
Dependency Spouse - Common law marriage
Dependency Spouse - Inference of marriage
Dependency Spouse - Deemed valid marriage
Military Retired Pay
Lack of Qualifying Service
Other non-rated

---

@marvokdolor-gov commented on [Sat Nov 17 2018](https://github.com/department-of-veterans-affairs/appeals-team/issues/995#issuecomment-439645791)

Questions for AMO 11/29 written up [here](https://github.com/department-of-veterans-affairs/appeals-design-research/issues/1069)

---

@marvokdolor-gov commented on [Mon Nov 26 2018](https://github.com/department-of-veterans-affairs/appeals-team/issues/995#issuecomment-441698266)

Morning @shanear! Thanks for the answers above. A couple of clarifying questions to Jennifer please: 
1. What types of claims are "Contested Claims (other than apportionment)"? 
2. Where/how can we find contesting claimant information e.g. addresses?

Not sure if these need to wait until Th, an email might be easier? 
In either case, I've added them to [the AMO ticket](https://github.com/department-of-veterans-affairs/appeals-design-research/issues/1069)

---

@shanear commented on [Mon Nov 26 2018](https://github.com/department-of-veterans-affairs/appeals-team/issues/995#issuecomment-441730667)

@marvokdolor-gov will ask about 1.

2. was answered earlier:

> They check the dependent tab. Most contested claims are filed by dependents or individuals who are saying they are a dependent such as two wives vying for the same benefit. Also Attorney fees are contested claims and that would be the POA tab to see if the person is the POA. So they check the systems and the eFolder.

---

@marvokdolor-gov commented on [Mon Nov 26 2018](https://github.com/department-of-veterans-affairs/appeals-team/issues/995#issuecomment-441740292)

Thanks Shane.
On 2. some noob follow-ups please: what will happen for AMA Appeals where there's no dependent or POA tabs to check? 
The answer refers to checking "systems" - would this be VBMS?

---

@shanear commented on [Mon Nov 26 2018](https://github.com/department-of-veterans-affairs/appeals-team/issues/995#issuecomment-441741108)

> On 2. some noob follow-ups please: what will happen for AMA Appeals where there's no dependent or POA tabs to check?
> The answer refers to checking "systems" - would this be VBMS?

Yeah in VBMS. It'd be pretty likely that the contesting claimant would be in the dependent tab in VBMS because they would have submitted a claim (entered in VBMS). I guess if they aren't there that's why they check the eFolder

---

@marvokdolor-gov commented on [Mon Nov 26 2018](https://github.com/department-of-veterans-affairs/appeals-team/issues/995#issuecomment-441759655)

Ah...didn't realize there are also "tabs" in VBMS, thought those were solely a VACOLS feature.
Thank you kindly!

---

@shanear commented on [Wed Nov 28 2018](https://github.com/department-of-veterans-affairs/appeals-team/issues/995#issuecomment-442667564)

It looks like there may be some other categories where contesting claimants are relevant in non-comp business lines. May need to follow up on that.

---

@marvokdolor-gov commented on [Mon Dec 03 2018](https://github.com/department-of-veterans-affairs/appeals-team/issues/995#issuecomment-442961445)

@shanear would that be follow-up with Jennifer ~Lawrence~ Williams? What can I do to help?

---

@shanear commented on [Thu Nov 29 2018](https://github.com/department-of-veterans-affairs/appeals-team/issues/995#issuecomment-443055170)

I'll ask in follow up emails with the non-comp business lines

---

@marvokdolor-gov commented on [Fri Dec 07 2018](https://github.com/department-of-veterans-affairs/appeals-team/issues/995#issuecomment-445263262)

### Reference documents from: [General Information on Contested Claims](https://vaww.vrm.km.va.gov/system/templates/selfservice/va_kanew/help/agent/locale/en-US/portal/554400000001034/content/554400000014298/M21-1-Part-III-Subpart-vi-Chapter-6-Section-A-General-Information-on-Contested-Claims?query=contested%20claims).

_You need to be logged into the VA Network with access to SharePoint for the link above to work._

**Note:** Holtz pointed out that these document VBA business process and not the law precisely. See [Slack Thread](https://dsva.slack.com/archives/C6E41RE92/p1544191899180800). If you're feeling ambitious here are [some CFR links](https://www.ecfr.gov/cgi-bin/searchECFR?ob=r&idno=&q1=simultaneously+contested+claim&r=&SID=7ad5c81bb1f9d732fe56599b840a19e8&mc=true) to dive into.

[General Information on Contested Claims.pdf](https://github.com/department-of-veterans-affairs/appeals-design-research/files/2657744/General.Information.on.Contested.Claims.pdf)
[Payment of Attorney or Agent Fees.pdf](https://github.com/department-of-veterans-affairs/appeals-design-research/files/2657742/Payment.of.Attorney.or.Agent.Fees.pdf)
[Apportionment Process.pdf](https://github.com/department-of-veterans-affairs/appeals-design-research/files/2657743/Apportionment.Process.pdf)
[Authorizing and Notifying Claimants of a Decision on a Contested Claim.pdf](https://github.com/department-of-veterans-affairs/appeals-design-research/files/2657761/Authorizing.and.Notifying.Claimants.of.a.Decision.on.a.Contested.Claim.pdf)

---

@allyceh commented on [Thu Dec 13 2018](https://github.com/department-of-veterans-affairs/appeals-team/issues/995#issuecomment-447124000)

@marvokdolor-gov Added notes from our meeting with Ivy and cleaned up a bit.

### Notes from meeting with Ivy on 12-11 (Allyce)
Legacy contested claims process

- RO inputs information about claim being contested. Pop up appears when the case is activated at the Board. 
  - Goes into contested box in VACOLS and double check info.
  - Sees who is contesting, if they have a rep. 
  - Pop up prompts Intake to check the contested box in VACOLS and verify the information is correct and reps are correct and generate the letter. 
- When activating case and after review, Intake send letters to both parties to notify them. 
- Sometimes info is already there at activation.
- Sometimes, information is put in the address tab. Makes it seem like the veteran is deceased. Wrong workflow! For notices of death, need to remove address. RO does this. 
  - Ivy’s team fixes this. If they don’t fix this, the letters don’t print or generate right. They also might have different POAs, so the issues don’t match. 
- Types of contested claims: DIC claim (two widows asking for death benefits claim), attorney fee claim (veteran gets another rep and didn’t get paid for work done). Usually compensation claim isn’t contested. 
  - Apportionment is biggest one.  Education is also contested. Two children fighting for education benefits. 
  - Other, child, widow. 
- Everyone has to be at hearing at same time. 
- Deceased date in VBMS lets people know that claim isn't contested, and veteran is deceased. 
- Claim must go through the same procedure that other claims go through. THATs why information is in VACOLS. Contested claimant submits NOD to the board. Nothing on NOD to indicate that claim is contested. 

What Ivy's team needs to know that a RAMP/AMA claim is contested:
- Put in the RAMP decision that the claim is contested? In VMBS? Ivy thinks there’s nothing in VBMS to identify a contested claim at the moment
  - "The contested claim info MUST be in VBMS since it won't be entered by the RO for AMA appeals. Otherwise, we won't know..."
  - This is our open question

Other info needs: 
- VSO needs to know who they are working with because they’re writing the IHP for either the veteran or the person who is contesting. 
  - Currently, no field for two contested (three) claimants. Normally one contests. 
  - No room to put contested claimants rep into VBMS. 

How do BVA staff know that a claim is contested if it's not in VACOLS?
- Sometimes, attorneys or Intake staff notice in veteran's e-folder that there's correspondence that VA is sending to someone aside from the veteran… then, they know it’s a contested claim. 
- If attorney sees there is a contested claim after the fact, they send it to colocated to generate the notification letters. 

Example of attorney fees contested claim: 
- After going to CAVC, veteran can choose another rep. After court, get a different VSO rep. Then attorney wants to contest claim
  - File a form 9 to contest attorney fees. This is always a separate appeal. 
  - There’s a contested attorney fee and claim for an attorney fee. Depends how the attorney filed it. If he filed a claim, it’s his appeal. If he appeals from us from CAVC, contested for attorney fee.  Form 9 initiates an appeal. 

Data in a contested claim: 
- Veteran ID: always the same for contested claimants and veterans. But, still the veteran’s number. 
  - VACOLS provides all appeal numbers for a veteran. If one appeal is contested and one isn’t, you could see in the appeal. Docket number for different appeals is created. Docket number created when the widow or the veteran files the form 9. 

Follow ups: 
- Ivy says to go to the address tab and get a screenshot. We'll see a block that says other, child, and widow. That’s where the RO might put contested claim inforamtion, which is wrong. This is actually where you put the widow or child if it’s THEIR appeal and the veteran is deceased. 

### Notes from meeting with Ivy on 12-11 (Marvo)

-Two separate letters are sent to the two parties. This is to ensure no PII (address information) is shared with the other party.
- Sometimes the RO doesn't realize that the Veteran is still alive.
  - there's a screen on the Address Tab where they mistakenly put the Contesting Claimant address and replace the Veteran's address.
 - BVA Intake will catch this during Case Review

Only one Contested Claim per Appeal
- DIC: Dependency and Indemnity Compensation or Dependency Indemnity Claims; in this case Veteran has passed away
- Attorney Fees: 2nd most common Contested Claim; tends to have come from CAVC Counsel wants to be paid for going to the Court. There are also "regular claims" for Attorney Fees.
  - There could be a Contested Attorney Fee Claim (this is the one that comes from CAVC) | there could be a Attorney Fee Claim that's Appealed. Why does it depend on the Form 9? This is going to be a good question to ask Josh about.
- Apportionment: that's the one that mostly Contested Claim
  - Type most common - Education
- In some cases it's not a Contested Claim it's a Substitution - if there's not contesting claimants.

Question for LRP - how will the Board be able to identify a Contested Claim?

Important for Intake to know:
- what is the address of each Contested Claimant?
- ensuring the right POA is identified for each Claimant
- One edge case is when there's two Contested Claimants in addition to the Veteran. In that case Ivy adds additional notes to include both Contested Claimants information.

- Sometimes it looks like a letter is in the wrong Veteran's folder, but it turns out to be a Contesting Claimant.
- Attorneys tend to be the ones to discover that there's a Contesting Claimant since it can slip through the cracks. They then send it to VLJ

- Claim number doesn't change from appeal to appeal, but docket numbers are different for each appeal.

- TODO: Get a snapshot of the Address Tab, which is only for deceased Veterans. It should be under the Contested block if the Veteran is alive

---

@marvokdolor-gov commented on [Mon Dec 17 2018](https://github.com/department-of-veterans-affairs/appeals-team/issues/995#issuecomment-447853937)

@allyceh I've added my Josh and Rachel notes here (and below) and removed them from the mural.

## Contested Claims with Josh Freeman 12/13/2018 (Marvo)

Contested Claims is what VACOLS does the worst.
It doesn't flag things like Apportionment that are always Contested Claims.

First problem with this:
- no attempt to show that there is another person that needs to be informed

Second - the way VACOLS enters Addresses:
- there's a single root address for an Appeal. It they add an Address, they end up over-writing the address with the Contesting Claimant's Address. It over-writes the Rep addresses as well.
Individual person's information is entered before you get to select that it's Contested. This is

Contested Claims can be multiple cross-appeals:
- Battle of the Widows.
- VA can only recognize one surviving-spouse.
- Sometimes one surviving spouse is the appellant on their own appeal AND appellee on the other surviving spouse's appeals
- DIC (Dependents Indemnity Compensation, Ch13)

Spousal benefit is separate from child benefits. Recognition of additional children increases the total but not proportionally so it decreases how much each person gets.

VACOLS has a Contested Claims field that multiple claimants can be added to.

Certain notices have to go out at the same time to all contested claimants:
- hearing
- docketing
- decisions
- this is complicated with colocated VSOs: VBMS is getting updated to allow for multiple VSOs for one claim file; this won't impact historic appeals

There are a lot of additional steps for the BVA intake team to take and check

#### What's needed by Intake and Hearing Coordinators need
- Names and addresses of all parties and their POAs.
- VACOLS doesn't have additional data that can be surfaced.

### AMA advantage
- ROs tend to mess up the notification requirements quite often e.g. routinely fail to notify the contested claimants
- If there's a due process problem with CCs it is always prejudicial since someone has to lose.

Different types of CCs: 
- Apportionment (always a contested claim)
- Attorneys Fees (always a contested claim)
- only sometime is this Surviving Spouse includes DIC 

Historically VACOLS has Apportionment; Insurance has a CC; Attorney Fees; Loan Guaranty (LGY) can also have CC (this is an edge case)

Josh would expect someone at the Board (Intake) to be creating the flags and looking for Contested Claims.
Why? Because of NOD requirement at the Board.

There should be language in the decisions that indicates the individual is a contesting claimant.
The party to a simultaneously "contested claim". The other contesting claimant; appellant; there's a heading for multiple appellants; there's also appellee. Sometimes they're not captioned i.e. they're not included on the front page and headers, but they are referenced in the document itself.

---

@marvokdolor-gov commented on [Mon Dec 17 2018](https://github.com/department-of-veterans-affairs/appeals-team/issues/995#issuecomment-447854171)

## Contested Claims with Rachel Sauter 12/13/2018 (Marvo)

Contested Claims can't go through HLR and SC, so they can only come to the Board after the AOJ Decision.

What are the AMA implications?
- can become contested at different stages:
  - one way it was a CC when the NOD was filed
  - sometimes one party is already receiving a benefit and someone else wants some (or all) of the benefit
- they both go to the 'highest' level of appeal chosen by any of the Contesting Claimant. Note: Direct Review is the lowest, Evidence Submission is the middle, and Hearing is the highest

VA has to help people as much as possible. In the case of contesting claimants, VA tries to get the parties on the same level of knowledge/information, as much as possible. Example a Veteran against a Rep - who might be someone with a law degree.

Board accepts evidence from whoever gives it.

Second party responds - how do they know to respond?
 - Board receives NOD from contesting party and notifies the second party.
 - the response time from the second party from the time they get notified via the Board is: 30 days
    - this response is categorized as - "correspondence"
- both parties receive the docketing letter (this is a follow-up to the original docketing)

**Question**: who should 
1. re-intake a contested claim for the first party when the second claimant asks for a different lane? 
2. send out new docketing letters?

How would Intake staff know that a claim is being contested?
- the person filling out the NOD is not the same person who received the decision;
- the Veteran's Claim File Number would lead to the Veteran/the person receiving the benefit

In some cases there could be an original claim that is a contested claim - Apportionment.

With legacy there are many layers of adjudication before it comes to the Board, so there are more checks. Some CCs still fall through the cracks.

A common Privacy violation is giving the parties each other's addresses.
 - this is something that IDT has to account for

### Next Steps
Emily and Josh are people to talk to for ironing out details as we move forward.

---

@shanear commented on [Mon Dec 17 2018](https://github.com/department-of-veterans-affairs/appeals-team/issues/995#issuecomment-448050527)

> It doesn't flag things like Apportionment that are always Contested Claims.

This is a good start for us to do 🙂 

---

@marvokdolor-gov commented on [Fri Dec 21 2018](https://github.com/department-of-veterans-affairs/appeals-team/issues/995#issuecomment-449490238)

### Next Steps

- [ ] Allyce: touch base with Carola on developing application location and alert copy for:
1. Always Contest Claims
 2. Sometimes Contested Claims
- [ ] Marvo: schedule time to walk through both short-term (alerts) and medium-term (flow in mural) plans with Emily (LRP) and BVA Intake Detailee (an attorney TBD). Questions for them (and Ivy):
    - [ ] How should we identify and deal with "sometimes" Contested Claims?
    - [ ] When a dependent is created in VBMS - is there a name **and** address?

### Raw notes (Marvo)
What's the percentage of Contested Claims at the Board? ChrisG might know. Nicholas' rough guess is less than 1%.
How will Contested Claim data get into Caseflow?
We might need a prompt to ask whether or not a Claim is Contested.
- [ ] Screenshot of VBMS Dependents Tab
Can VBMS support adding a POA to a Dependent?
If something is "Always a Contested Claim":
- bring up a new modal with initial claimant so you the person currently receiving the benefit and the contesting claimant who's submitting the form

Concern: not enough time to build this by Feb 14. Back-up plan: could perhaps pull information from VBMS to Caseflow.
- 1st phase: Apportionment + Attorney Fees
- 2nd phase: Add more options
- note that Participant IDs are tied to individuals while Claim IDs are shared
- we want to pull dependent information from VBMS if it's there
- Queue will be building Contested Claims into Case Details so this design can be shared with Carola.

**MVP**
- pull up list of issues
- select Contesting Claimant from a list of Dependents in VBMS
- we'll have to work with LRP and BVA Intake Attorney Detailee re: AMA and how this will work
- BVA Intake team will have to manually copy and paste name and address since we don't have a letter generator yet

---

@marvokdolor-gov commented on [Thu Jan 03 2019](https://github.com/department-of-veterans-affairs/appeals-team/issues/995#issuecomment-451202335)

### Questions:
- process changes with AMA
- what's the expected role of the attorney who will be in Intake; they'll be an LRP person.
   - they should be in place by Feb 1
   - one function is to field tricky cases
   - e.g. Judge calls from a Hearing and says that both people aren't there. This would be before the attorney looks at the file.

Cases to flag these three are identified as Contested Claim by **Issue**:

1. Attorney Fees Withholding
2. Apportionment
3. Insurance Claim with special docket number (RH prefix most commonly)

#### These are sometimes contested claims based on the issue:
- DIC case - should go to the Intake Attorney for them to take a look at.
- Rating Decision - one person is getting the benefit.
- NOD (should have been identified beforehand at the AOJ) - another person is filing for the benefit.
VBA does not identify this as a Contested Claim - hence the
- child-support payments
- Person filing the NOD is not the person receiving the payments.
1. Apportionment 2. Attorney Fees with Withholding 3. Two or more widows

#### Intake Detailee
- should have a flow chart that will be created by LRP

#### VBMS Letter Generation
- What's the status of this? LRP will follow up with Nick U and Patrick

#### IDT
- We'll need a new Rights Notice for Contested Claims to be included in IDT
- LRP might be working with Dave McLenachen (AMO)
- Emily following up with them

#### In Summary: These cases are going to be Special-Handled

Action Items (LRP)
- Flowchart- Emily will build
- Rights Notice - check in McLenachen
- VBMS Letter Generation - check in with Nick U

Next Steps for Caseflow:
- [ ] Marvo: Add Contested Claims to Mail Routing Rule: i.e. to Legal Detailee, check with LP
- [ ] Marvo: Follow-up with LRP on their AIs

---

@shanear commented on [Tue Jan 29 2019](https://github.com/department-of-veterans-affairs/appeals-team/issues/995#issuecomment-458751612)

Do yall know what you need us to do here?

---

@marvokdolor-gov commented on [Tue Jan 29 2019](https://github.com/department-of-veterans-affairs/appeals-team/issues/995#issuecomment-458753074)

Hey @shanear i think this ticket is the next step: https://github.com/department-of-veterans-affairs/caseflow/issues/8660

---

@marvokdolor-gov commented on [Tue Jan 29 2019](https://github.com/department-of-veterans-affairs/appeals-team/issues/995#issuecomment-458753599)

Also, this MURAL outlines the steps beyond that: https://app.mural.co/t/workqueue2001/m/workqueue2001/1542655242638/5629820b4b2c34a158c9dd7abb78137d0f9b8b74
Carola worked with Allyce on the flows.

**Comment by carodew** [comment]
@msj0nes just a heads up that I moved this over to the Caseflow repo to keep all the tickets in the same place.

**Comment by msj0nes** [comment]
Closing. This ticket is duplicate of [#995](https://github.com/department-of-veterans-affairs/appeals-team/issues/995) already referenced in [Contested Claims - Attorney fees](https://github.com/department-of-veterans-affairs/caseflow/issues/13505) work.
