### ISSUE TITLE
Create individual virtual hearing docket days

### ISSUE THREAD

**Issue by chandracarney** [department-of-veterans-affairs/caseflow#13975]
## User story
As a schedule building Hearing Management Branch team member, I need the ability to create and view hearing docket days that are virtual-only so that Hearing Coordinators can fill them with Veterans who have opted in to virtual.

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: [TBD individual virtual dockets]
- [ ] This feature should be accessible to the following user groups: Hearing Management Branch user with ability to create hearing days
- [ ] Include screenshot(s) in the Github issue if there are front-end changes

## Release notes
Virtual-only hearing days are 

### Out of scope
Building the year's hearing schedule with virtual-only days. This work will be captured in #13435

### Designs
See #12825

### Background/context
In order to overcome hearing room capacity issues, virtual-only docket days can be created individually (manually) - not associated with RO to allow for VLJs to hold virtual-only hearing days, increasing hearing capacity. 

### Related work
Just before fiscal year 2021 (FY21) the Baord identified areas to increase capacity, which has been worked on in #14880
