### ISSUE TITLE
Remove tracking mail org tasks

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#14069]
### Description
We currently create a mail task assigned to the mail team for every mail task that is created. These tasks are not handled by the mail team and will have no available actions, yet they still appear in the mail team's queue. We should stop creating these "tracking" tasks as the mail team uses numbers from their queue for reporting purposes. We also should get out of the practice of having tasks appear in queues that will never be actionable by that queue's user or member of the queue's organization.

### Replicate in Dev
1. Search for any case and add some mail tasks to it
![ezgif-3-84a5b85d1756](https://user-images.githubusercontent.com/45575454/80024947-d66e8f80-84ad-11ea-911c-a92f3352a34d.gif)
2. This creates 4 tasks assigned to the mail team, each with their own child tasks assigned to the org that will actually handle them
```ruby
Appeal.find_by(uuid: "6dda45f7-2527-454c-8ea8-4eab051a7c93").treee(:status, :ASGN_TO)
Appeal 407 (direct_review)                      STATUS   ASGN_TO
└── RootTask                                    on_hold  Bva
    ├── DistributionTask                        on_hold  Bva
    │   ├── FoiaRequestMailTask                 on_hold  MailTeam
    │   │   └── FoiaRequestMailTask             assigned PrivacyTeam
    │   └── ExtensionRequestMailTask            on_hold  MailTeam
    │       └── ExtensionRequestMailTask        on_hold  Colocated
    │           └── ExtensionRequestMailTask    assigned CSS_ID1
    ├── ClearAndUnmistakeableErrorMailTask      on_hold  MailTeam
    │   └── ClearAndUnmistakeableErrorMailTask  assigned LitigationSupport
    └── DeathCertificateMailTask                on_hold  MailTeam
        └── DeathCertificateMailTask            on_hold  Colocated
            └── DeathCertificateMailTask        assigned BVALSPORER
```
3. These appear in the mail team's "Assigned" (or "On hold" if the team does round robin assigning) tabs even though they are not assigned to any mail team members.
![Screen Shot 2020-04-22 at 3 28 29 PM](https://user-images.githubusercontent.com/45575454/80025292-6280b700-84ae-11ea-9d25-2e3d58c448c5.png)
![Screen Shot 2020-04-22 at 3 28 37 PM](https://user-images.githubusercontent.com/45575454/80025288-614f8a00-84ae-11ea-8247-c4daf88c439b.png)

### Background
According to comments https://github.com/department-of-veterans-affairs/caseflow/blob/b50dedadfff96281a394ee2355d2691e8ab43f9b/app/models/tasks/mail_task.rb#L46 and the original PR #7404, this was done to track that the mail team created this task?

[Slack Chatter](https://dsva.slack.com/archives/CHX8FMP28/p1581621426322900)

Currently, when a user creates any mail tasks, caseflow creates 2 tasks
1. That mail task type, [assigned to the mail team](https://github.com/department-of-veterans-affairs/caseflow/blob/b50dedadfff96281a394ee2355d2691e8ab43f9b/app/models/tasks/mail_task.rb#L46-L51)
1. That mail task type, [assigned to the default org assignee, with the mail team task as its parent](https://github.com/department-of-veterans-affairs/caseflow/blob/b50dedadfff96281a394ee2355d2691e8ab43f9b/app/models/tasks/mail_task.rb#L55-L65)

The same thing occurs when we change mail task types
1. New mail task type, [assigned to the mail team](https://github.com/department-of-veterans-affairs/caseflow/blob/b50dedadfff96281a394ee2355d2691e8ab43f9b/app/models/tasks/mail_task.rb#L99-L104)
1. New mail task type, [assigned to the default org assignee, with the mail team task as its parent](https://github.com/department-of-veterans-affairs/caseflow/blob/b50dedadfff96281a394ee2355d2691e8ab43f9b/app/models/tasks/mail_task.rb#L106-L112)

## AC
- [ ] Changing a mail task type that is not assigned to the mail team does not create a "grandparent" mail org task
- [ ] Creating a mail task that is not assigned to the mail team does not create a "grandparent" mail org task

**BEFORE**
```ruby
Appeal 20083 (hearing)                 STATUS      ASGN_TO
└── RootTask                           on_hold     Bva
    └── StatusInquiryMailTask          on_hold     MailTeam
        └── StatusInquiryMailTask      on_hold     LitigationSupport
            └── StatusInquiryMailTask  assigned    VACOJAGADL
``` 
**AFTER**
```ruby
Appeal 20083 (hearing)                 STATUS      ASGN_TO
└── RootTask                           on_hold     Bva
    └── StatusInquiryMailTask          on_hold     LitigationSupport
        └── StatusInquiryMailTask      assigned    VACOJAGADL
``` 
- [ ] Tasks in production are cleaned up

**BEFORE**
```ruby
Appeal 20083 (hearing)                 STATUS      ASGN_TO
└── RootTask                           on_hold     Bva
    └── StatusInquiryMailTask          on_hold     MailTeam
        └── StatusInquiryMailTask      on_hold     LitigationSupport
            └── StatusInquiryMailTask  assigned    VACOJAGADL
``` 
**AFTER**
```ruby
Appeal 20083 (hearing)                 STATUS      ASGN_TO
└── RootTask                           on_hold     Bva
    └── StatusInquiryMailTask          cancelled   MailTeam
    └── StatusInquiryMailTask          on_hold     LitigationSupport
        └── StatusInquiryMailTask      assigned    VACOJAGADL
```

**Comment by hschallhorn** [comment]
@araposo-tistatech Finished writing this up!

**Comment by yoomlam** [comment]
https://github.com/department-of-veterans-affairs/appeals-team/blob/master/Project%20Folders/Tasks/tasktrees/descr/tasks-overview.md#mailtasks

**Comment by ajspotts** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | 
3 | |||||||||
5 | |||
8 | 
```

Update the correct Organization task's parent to root first before cancelling the parent MailTask.



#### Why 3?
- Updating production data
- Need to ensure users can still change task types of mail tasks without messing up the task tree
- Will need to update other instances where the code expects this "grandparent" mail team mail task

#### Why 5?
- Same as first reasoning in Why 3
- Quantity of work; code changes and prod data updates

**Comment by araposo-tistatech** [comment]
Sent request to Board for approval on this ticket. Moving to Define until approval is received.
