### ISSUE TITLE
Hearing task routing enhancements

### ISSUE THREAD

**Issue by chandracarney** [department-of-veterans-affairs/caseflow#14393]
## Background/context
[Requirements-gathering doc](https://docs.google.com/document/d/1kcnud1_ZdtVDUujLInp-W8PuZwQafZFZLjbKaOZNSp0/edit?usp=sharing)

Define and map out difference in `Hearings Management` and `Hearing Admin` queues queues, tasks within those hearing queues, and correct routing of tasks for the Hearing Management Branch's queues. 

`Hearing Admin`tasks
- ChangeHearingDispositionTask
- HearingRelatedMailTask
- ReturnedUndeliverableCorrespondenceMailTask
- PowerOfAttorneyRelatedMailTask
- AddressChangeMailTask

`Hearings Management`tasks
- ScheduleHearingColocatedTask
- NoShowHearingTask
- HearingAdminActionVerifyAddressTask
- HearingAdminActionOtherTask
- HearingAdminActionForeignVeteranCaseTask
- HearingAdminActionIncarceratedVeteranTask
- HearingAdminActionMissingFormsTask
- HearingAdminActionVerifyPoaTask
- HearingRelatedMailTask
- Task
- HearingAdminActionFoiaPrivacyRequestTask
- EvidenceSubmissionWindowTask
- TimedHoldTask
- HearingAdminActionContestedClaimantTask

## Goals
- Remove extraneous tasks that are sent to either admin queue in error
  - Understand if each task should exist
- Automatically move tasks, when possible, after determined timeframe
- Revise routing for tasks, when incorrect
  - Understand where tasks should route
- Define tasks and the reasoning behind existing routing

## Success criteria
- [ ] Merge `Hearing Admin` and `Hearings Management` queues
- [ ] Automatically route no-shows, withdraw requests, cancelations, and postponements to the correct VACOLS locations and/or Caseflow teams
- [x] Ensure important instructions/notes are preserved for ScheduleHearing tasks

## Stakeholders
Hearing Branch Chief, Deputy Hearing Branch Chief, and DVC

## Routing Requirements
If the appeal is Legacy and being withdrawn, postponed, or canceled, assign it to the locations as defined, and outlined, in #14297.

### Out of scope routing needs
Withdrawing appeal in full, or an Appellant has passed away. [Much less common and only needed much further down the road if there is some nuanced introduction with differing types of hearing withdraw to clear a hearing entry or ScheduleHearingTask.]:
- Location 66 in VACOLS for immediate dismissal action

## Open questions
- Why are there two queues for the Hearing Management Branch (`HearingAdmin` and `HearingsManagement`)?
  - They should be combined. Don't have clarity on historical reasoning.
- What are the tasks that get assigned to each queue?
  - [see main description]
- Why this process for schedule hearing tasks?
  - [MailTask_Organization Description](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/Project%20Folders/Tasks/tasktrees/descr/MailTask_Organization.md)
  - [Historical information on why routing was changed on admin actions](https://github.com/department-of-veterans-affairs/caseflow/issues/11113#issuecomment-512934636), causing `ScheduleHearingColocatedTask` to be sent to `HearingsManagement`: Change routing of admin actions #11113

### Business value
- Decrease external systems used by Hearing Branch Caseflow users, thereby increasing speed of use and increasing speed of timely appeals/hearing processing
- Decrease, or remove, administrative action needed for different types of tasks

### Dependencies
Caseflow Queue to be involved in the work, where needed.

### Related issues
#12653
