### ISSUE TITLE
Build new Convert to Virtual page for Central Office hearings

### ISSUE THREAD

**Issue by chandracarney** [department-of-veterans-affairs/caseflow#14421]
## User or job story
User story: As a Hearing Coordinator, I need to use a Convert to Virtual page, so that I can schedule Central Office hearings to virtual.

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: #14387
- [ ] This feature should be accessible to the following user groups: Hearing Coordinators
- [ ] Include screenshot(s) in the Github issue

## Detailed AC

- [ ] When the user opens the Hearing Type dropdown on a Central Office hearing and selects virtual, the Convert to Virtual Hearing page opens
  - [ ] If the user has other unsaved changes on the Hearing Details page, the browser default "unsaved changes" window appears
- [ ] The Convert to Virtual Hearing page displays the following info / form fields:
  - [ ] Hearing Date - read-only
  - [ ] (virtual) Hearing Time dropdown with help text (see #14420)
      - [ ] time increments match current state (i.e. every 30 or 15 minutes depending on whether #14295 is implemented) (see #14420)
      - [ ] timezone is Eastern time (see #14420)
  - [ ] Veteran / Appellant name and mailing address - read-only
  - [ ] Veteran / Appellant Timezone dropdown with help text (see #14420)
      - [ ] required field (error message if left blank: `Veteran / Appellant Timezone is required`)
      - [ ] field is pre-populated based on Caseflow's calculation of the timezone based on veteran / appellant's address; if Caseflow cannot calculate, field is blank
      - [ ] option values format is: `Timezone (time of hearing in selected timezone, calculated based on Hearing Time selection)`
       - [ ] option value list order: Board regional office timezones at the top (starting with Eastern and moving west, with Puerto Rico last), with all possible timezones below separated by a divider line ([direct link to design](https://www.figma.com/file/V87TZArfdurCGJiEjQ73ES/Virtual-Hearings?node-id=5649%3A19450))
       - [ ] `Open Question: Is it possible to adjust the height of (these or all?) open dropdowns so that all/most Board regional office timezones display without scrolling? May not be feasible depending on the number of RO timezones`
  -  [ ] Veteran / Appellant Email with help text
      - [ ] required field (no change to current state / error message)
      - [ ] pre-populated (no change to current state)
  - [ ] Power of Attorney (POA) type label, name, and address - read-only
      - [ ] note the various POA types/labels: Attorney or Service Organization
      - [ ] `Open Question: for some Service Organizations, a person's name, in addition to service org name, displays on the Daily Docket but not on Case Details. Is this name being pulled from VACOLS or VBMS? Should we try to display it here?`
      - [ ] if no POA, display message ([direct link to design](https://www.figma.com/file/V87TZArfdurCGJiEjQ73ES/Virtual-Hearings?node-id=5649%3A19281))
  - [ ] POA / Representative Timezone dropdown with help text (see #14420)
      - [ ] optional, but validate that field is not blank if a POA / Representative Email is entered (error message if left blank: `Timezone is required to send email notifications`)
      - [ ] field is pre-populated based on Caseflow's calculation of the timezone based on POA's address; if Caseflow cannot calculate, field is blank
      - [ ] display and formatting of option values matches Veteran / Appellant Timezone field
  - [ ] POA / Representative Email with help text
      - [ ] optional
      - [ ] pre-populated (no change to current state)
  - [ ] VLJ dropdown
      - [ ] optional
  - [ ] VLJ Email - read-only, based on dropdown selection; if blank, display `None`
- [ ] On pressing the Convert to Virtual Hearing button, the async jobs to create the conference and send emails begin, and the user is taken back to Hearing Details where the In Progress and and Success states/alerts display as appropriate
  - [ ] No changes to Hearing Details current state alert messaging or form field disabled states, _except_ :
      - [ ] that the new Timezone fields are also disabled during the in progress state
      - [ ] the POA Timezone field is disabled if the POA email field is blank ([direct link to design](https://www.figma.com/file/V87TZArfdurCGJiEjQ73ES/Virtual-Hearings?node-id=5671%3A0)))

### Update virtual (formerly-Central) hearing emails and/or timezones
([Figma link to start of flow](https://www.figma.com/file/V87TZArfdurCGJiEjQ73ES/Virtual-Hearings?node-id=5649%3A22954))
In general, when a user edits **either** the timezone **or** the email field on Hearing Details, a confirm modal subsequently displays **both** timezone **and** email. Specifically:

- [ ] When the veteran/appellant Timezone and/or email is edited (and is not blank since they're required fields), and the user presses the Save button, a modal displays ([link to design](https://www.figma.com/file/V87TZArfdurCGJiEjQ73ES/Virtual-Hearings?node-id=5649%3A23656)):
  - [ ] Veteran Email - read-only
  - [ ] Veteran Hearing Time - read-only
    - [ ] formatted as h:mm am/pm (hearing time in selected timezone) + timezone label
- [ ] When the POA/Representative Timezone and/or email is edited and the user presses the Save button, a modal displays ([link to design](https://www.figma.com/file/V87TZArfdurCGJiEjQ73ES/Virtual-Hearings?node-id=5649%3A24009)):
    - [ ] POA / Representative Email - read-only
    - [ ] POA / Representative Hearing Time - read-only
      - [ ] formatted as h:mm am/pm (hearing time in selected timezone) + timezone label
    - [Note that we don't currently handle deleting a previously-entered POA email - see issue #13945]
- [ ] When both the veteran/appellant and POA/Representative timezone and/or email are edited, a modal displaying info for both is displayed ([link to design](https://www.figma.com/file/V87TZArfdurCGJiEjQ73ES/Virtual-Hearings?node-id=5649%3A23286))
- [ ] On pressing the Update Virtual Hearing button, the async job to send emails begin, and the In Progress and and Success states/alerts display as appropriate
  - No changes to current state alert messaging (with variations for one or multiple participants) or form field disabled states, _except_ that the new Timezone fields are also disabled during the in progress state 

### Convert virtual hearing back to Central Office hearing ([Figma link to start of flow](https://www.figma.com/file/V87TZArfdurCGJiEjQ73ES/Virtual-Hearings?node-id=5649%3A20946))
- [ ] When the user opens the Hearing Type dropdown on a virtual hearing and selects Central, the Convert to Central Office Hearing page opens
  - [ ] If the user has other unsaved changes on the Hearing Details page, the browser default "unsaved changes" window appears
- The Convert to Central Office Hearing page displays the following info / form fields:
  - [ ] Hearing Date - read-only
  - [ ] Hearing Time - same radio field that appears for Central/Video hearings on the Daily Docket
  - [ ] Veteran/Appellant name, mailing address, and email - read-only
  - [ ] Power of Attorney type label, POA name and/or service organization name, mailing address, email - read-only
     - [ ] if POA info is blank, display message ([direct link to design variation](https://www.figma.com/file/V87TZArfdurCGJiEjQ73ES/Virtual-Hearings?node-id=5649%3A21459))
- [ ] On pressing the Convert to Central Office Hearing button, the async job to send emails begin, and the In Progress and and Success states/alerts display as appropriate
  - [ ] No changes to current state alert messaging or form field disabled states

### Out of scope
- Timezone dropdown (see #14420)

### Designs
([Figma link to start of flow](https://www.figma.com/file/V87TZArfdurCGJiEjQ73ES/Virtual-Hearings?node-id=5649%3A18611))

## Release notes
Central to virtual now available when scheduling hearings.

### Technical notes

- testing
  - event listeners will need to be different
  - forms will be different
  - all of the different states for POA
