### ISSUE TITLE
CAVC Remand Design and Research: Phase 1 and 2

### ISSUE THREAD

**Issue by geronimoramos** [department-of-veterans-affairs/caseflow#14611]
### Week 1

- [x] Design ux workflows mid to high fidelity
- [x] While collecting internal feedback
- [x] Reach out to Lit Support to schedule check-in and testing for next week

### Week 2
- [x] Continue designs on intake setup and activating core remand flow
- [x] Validate with Lit support stakeholders

## Phase 1: Intake

**Scope:** 

Finding the relevant case in Caseflow based on the information from email and the CAVC website

**Stories:** 

As a lit support user: 

- When I have reviewed all of the relevant information in my email and the CAVC website, I want to jump into Caseflow so I can carry out the necessary processes whether it be a Remand, Reversal, or Death Dismissal.
- I want to find and pull up the relevant case in Caseflow

**Estimated design timeline:** 

- 1 week

## Phase 2: Intake - Reversal

**Scope:** 

Complete a reversal based on CAVC website 

**Stories:** 

[Still developing stories, clarify difference between reversal and remand] 

- As a lit support user, I need to mark whether this is a "Point of Law" or "Straight Reversal", so I can complete the next task
- As a lit support user, when I have indicated a "Point of Law" reversal and have the case follow the Remand path [unclear]
- As a lit support user, when I have indicated a "Straight Reversal" I want to [unclear]
- [Happens outside of Caseflow, consider having a reminder or check-list] As a lit support user, I want to download all the pertinent documents on the court order from the CAVC website, so that I can upload them to VBMS to ensure that the documents are present there and accessible.

**Estimated discovery research and design timeline:** 

- 2 week
## Problem statement

The CAVC system and BVA systems don't speak with one another which creates a heavy reliance on manual processing. When CAVC has completed a court order, the system triggers an email to be sent to a Litigation Support user's inbox. From there, the manual processing begins which includes:

- Having to navigate the CAVC website to find the court order, review the details, and download pertinent documents
- Then the Litigation Support user must locate the appeals decision the court order is associated with and work off that accordingly

## Existing design and content

[Design working file
](https://www.figma.com/file/8noUqRbvCJzdpwkSNCb8lZ/CAVC-Remand-Designs?node-id=0%3A1)
