### ISSUE TITLE
Schedule enhancements for FY21 | Allow single-day dockets without room assignment

### ISSUE THREAD

**Issue by chandracarney** [department-of-veterans-affairs/caseflow#14880]
## Description
Expand hearing room and day capacity for FY21 schedules to be built, and expanded upon as needs arise. 

The Board would like to allow single-day dockets without room assignments in order to build:
- AMA-only dockets (thus also filling existing dockets with legacy) in order for AVLJs and others to hear AMA-only cases
- One-off dockets for extra capacity to alleviate COVID-19 strain

The Board would like to expand standard scheduling capacity by:
- Adding 5 more hearing rooms
- Making the time slots consistent by standardizing to 12 across ROs
- Expanding Central Office to have 5 business days instead of 4

Investigate what work needs to be done to remove or introduce new requirements, and work towards these goals.

## Acceptance criteria
- [x] Investigate constraints surrounding building single-day dockets #14614
- [x] Investigate adding room and day capacity for FY21 schedule #14769
- [x] Add 5 hearing rooms to schedule #14772
- [x] Make the time slots consistent / standardize to 12 across ROs #14772
- [x] Make Central Office slots 10 across the board #14772
- [ ] Allow individual days with hearing room “none” to schedule Veterans

## Related work
#13975
