### ISSUE TITLE
Trigger receipt of completed IHPs (VLJ support notification)

### ISSUE THREAD

**Issue by mbaenatan** [department-of-veterans-affairs/caseflow#14909]
## Background/context
At this time IHP writing POAs automatically receive IHP tasks for appellants in the following scenarios: 

- When the veteran's 90 day window for evidence submission is complete. 
- Post intake for direct docket AMA cases
- Any time Caseflow identifies a new representative for an appellant and they are an IHP writing POA

When the task is assigned to a VSO organization, any member of that VSO may assign it to another user, complete, or cancel the task. When assigned to a VSO member, they can reassign the task, place it on hold, complete, or cancel the task. Any admin of the VSO organization can reassign any task assigned to that VSO's members. 

If an IHP task is not automatically assigned to an IHP writing POA then the VLJ and/or Attorney have the ability to add an admin action on the case requesting an IHP task be completed. These tasks are routed to the VLJ Support team. The VLJ Support team then routes a 3230 via email to the POA on the case and awaits completion. VLJ Support is notified of the completion of IHP tasks on legacy cases via a report they pull in VACOLS against location 902. Once aware of what IHPs are ready for review and upload, the VLJ Support team then locates that POAs file via a shared drive. For AMA cases there is no report available so they check the shared drive once a day. This process typically takes 2-3 hrs/day per VLJ Support employee. 

In all cases (automated & non-automated) VLJ Support does not receive any immediate notification or indication when the IHP task is completed which causes delays in case movement.

## Goals
VLJ Support is notified of a completed IHP task via an indicator, receipt, or notification. 

## Acceptance criteria 
- [ ] VLJ Support is able to immediately identify when a POA has completed their IHP task via either a notification, receipt, or indicator

## Success criteria
- [ ] Time between requesting an IHP task and completing the task is decreased (baseline stats not yet identified so target will be added at a later date) 

## Stakeholders
VLJ Support

## Requirements/stories

- [ ] User Story: As an Attorney and/or VLJ I need to be notified immediately when the VLJ Support team completes the IHP task on a case I am working on so that I can continue working the case. #13800 
- [ ] User Story: As a VLJ support staff member I need to be able to see a notification or indicator when an IHP task is completed by a VSO so that I can audit the document and ensure it is complete for a judge/attorney to review. #14909 

### Designs and workflows
[Link to Mural](https://app.mural.co/t/workqueue2001/m/workqueue2001/1595518321333/a3929ce45595dca9177fe2adfd3cb3d6e3203fbd) workflow
[Link to designs](https://www.figma.com/file/awxxww4bQNzgr4wP4vdh8Y/IHP-Attorney-and-Support?node-id=0%3A1) in Figma

**Comment by araposo-tistatech** [comment]
@RyanRoyUX are we to use the same designs provided in the attorney ticket as this one for VLJ Support?
