### ISSUE TITLE
Intake | UI Improvements 

### ISSUE THREAD

**Issue by mbaenatan** [department-of-veterans-affairs/caseflow#14919]
### UI improvements for Intake 

- [x] Show legacy opt-in selection on add issues page table (small) [#15006](https://app.zenhub.com/workspaces/foxtrot-5f075a9e28abd0001de67d7b/issues/department-of-veterans-affairs/caseflow/15006)

- [ ] Add a “back” button on “Add Issues” page to avoid having users “Cancel intake” to make a correction: #11779 (medium) 

- [x] Styling on invalid date error in non-rating issue modal should be consistent with style guide for in-line errors (small) [#15007](https://app.zenhub.com/workspaces/foxtrot-5f075a9e28abd0001de67d7b/issues/department-of-veterans-affairs/caseflow/15007)

- [ ] Unidentified issue alert styling and confirmation page styling. 1) Unidentified issue displays in all red text and doesn’t direct user to any action that can unblock them. 2) Confirmation page has no hierarchy (medium-large)

- [x]  Explore design options for styling trashcan on Edit page (small) [#15008](https://app.zenhub.com/workspaces/foxtrot-5f075a9e28abd0001de67d7b/issues/department-of-veterans-affairs/caseflow/15008)

- [ ] Rethink drop down since “Remove issue” is the only option on Edit page (medium) 

- [ ] Styling on Remove Issues Modal does not match current style guide (small-medium) 

- [ ] Change “N/A” change to “No” or other for SOC/SSOC option (small-medium) 

- [ ] Show description instead of contention text on Confirmation page (medium) 

- [ ] Review intake page spacing ticket [#14488](https://github.com/department-of-veterans-affairs/caseflow/issues/14488) (small-medium)

**Comment by mbaenatan** [comment]
[Google doc](https://docs.google.com/document/d/1S0KfsjNqinCm9b0SNBfFghm_8XtkIZVNHnQ3UtY-p9c/edit) for more detailed notes and screenshot

**Comment by mbaenatan** [comment]
@rutvigupta-design created the 3 small UI cards from the list above and added them to design backlog at the top of the list. Will create separate cards for small-medium items when we have bandwidth.
