### ISSUE TITLE
CAVC Remand: Update ama priority order to include CAVC remands

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#14959]
## User or job story
User story: As a VLJ, when I request more cases, the cases I receive need to include CAVC Remand cases the Litigation Support team has completed the intake for, so that I can process a decision for these cases. 

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: CAVC_Remand
- [ ] This feature should be accessible to the following user groups: VLJ
- [ ] CAVC Remands are included in priority logic (#1: AOD + CAVC, #2: AOD, #3: CAVC, #4: everything else)
  - [ ] In our priority push job (#14958)
  - [ ] When selecting priority cases on requested distributions
  - [ ] Default ordering of tasks in queue
  - [ ] Which tasks to pull for bulk task assignment
- [ ] Would like to be able to pare this down into a small number of scopes or methods to reuse.

### Background/context

This ticket is to ensure CAVC Remands that are in-taken through Litigation Support are included in the Case Orders logic, no other changes to the logic should be made. 

### Technical notes

Latest update made to the logic: https://github.com/department-of-veterans-affairs/caseflow/issues/14542

**Comment by hschallhorn** [comment]
Closing as captured by 
- [ ] existing ticket [CAVC Remand: Update Auto-Distribution Criteria for Priority Cases](https://github.com/department-of-veterans-affairs/caseflow/issues/14958#) #14958
- [ ] New ticket [Confirm default ordering of tasks prioritizes ama cavc remands](https://github.com/department-of-veterans-affairs/caseflow/issues/15308#)#15308
