### ISSUE TITLE
Intake | Docket Change | Ability to open tasks 

### ISSUE THREAD

**Issue by mbaenatan** [department-of-veterans-affairs/caseflow#15100]
## User or job story
As a BVA Attorney at the Office of the Clerk of the Board, I need a way to manually open any tasks that are relevant to the newly selected docket type so that I can move the appeal forward.

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: `docket_change`
- [ ] This feature should be accessible to the following user groups: `clerk of the board`
- [ ] Once a user has added in information about the docket switch (date, type of grant, docket type), they should see the Add/Remove tasks screen
- [ ] The progress bar should be on the second step (please see the designs below)
- [ ] The user should see which docket they are switch from and to (For e.g: You are switching from Hearing to Direct Review.) at the top – this should be body text and bolded. 
- [ ] The user should see which docket they are switch from and to (For e.g: You are switching from Hearing to Direct Review.) at the top – this should be body text and bolded. 
- [ ] Below that, the user should see instructions – copy is in the designs below
- [ ] The user should be able to click "Add task" and see the expanded add task section (see the design below)
- [ ] The list of tasks should be the existing admin action options
- [ ] "Remove task" should delete the task and collapse the add task section
- [ ] The user should be able to add multiple tasks
- [ ] Selecting back will take the user back to the Review Request page
- [ ] Taking action on this page is NOT required - the "continue" button should be active
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Add Jest tests
- [ ] Add Storybook stories (might make sense to have separate story for the add task subcomponent)
- [ ] Update documentation: [link]

### Out of scope

Submission to backend

### Designs

**Add Task button**
![Remove Tasks](https://user-images.githubusercontent.com/51714306/97455601-063b9b80-1906-11eb-9eb3-09fa9cff847d.png)

**Add task section**
![21  Switch Dockets_ Add a task](https://user-images.githubusercontent.com/51714306/97455612-09cf2280-1906-11eb-9d0c-90a45c44dff1.png)

**Task dropdown**
![21 1 Switch Dockets_ Add task dropdown](https://user-images.githubusercontent.com/51714306/97455622-0b004f80-1906-11eb-916e-e9efd9f6b0c5.png)

**Add multiple tasks**
![21 2 Switch Dockets_ Add another task](https://user-images.githubusercontent.com/51714306/97455627-0cca1300-1906-11eb-937b-2db49036100f.png)

### Background/context

This builds on #15099

### Technical notes
- We should already have the list of existing tasks in Redux store

### Other notes
- Should the determination of tasks to automatically open/close be out of scope?
- Verify w/ @rutvigupta-design any need for validating the possible new tasks to be added vis a vis the tasks that already exist or are being removed

**Comment by jcq** [comment]
Tasks that will be automatically created:

- Direct Review — `DistributionTask`
- Evidence Submission — `DistributionTask`, `EvidenceSubmissionWindowTask`
- Hearing — `DistributionTask`, `HearingTask`
