### ISSUE TITLE
Support AMA CAVC Remands JMR/JMPR

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#15219]
## Background/context
After a decision has been drafted at the Board and the appellant believes the Board erred in it's decision, the appellant has the option to appeal that decision with the United States Court of Appeals for Veterans Claims (CAVC). CAVC then reviews the Board's decision. CAVC's review is based on the record before the agency and arguments of the parties, which are presented in written brief. CAVC does not review new evidence. 

When a case is remanded by CAVC for a JMR or JMPR it means the VA has made errors in its decision that require remand (for the case to be sent back to the Board) and correction. 

At this time Caseflow is unable to support opening a new appeal stream for these remanded cases from CAVC. The focus of this epic is to build functionality that will provide the Litigation Support Team the ability to open and route JMR & JMPR CAVC Remands to VLJs for decision.

## Goals
- Litigation Support is able to initiate a CAVC Remand for JMR & JMPR mandates on AMA cases. 
- Judge teams are able to process decisions for JMR & JMPR mandates on AMA cases. 

## Success criteria

- AMA CAVC JMR & JMPRs are no longer processed in VACOLS 
- AMA CAVC JMR & JMPRs are processed & dispatched via Caseflow queue

## Stakeholders

- VLJ
- Attorneys
- Litigation Support
- Mail Team

## Acceptance Criteria
- [ ] Litigation Support is able to start and process Joint Motion for Remand (JMR) and Joint Motion for Partial Remand (JMPR) CAVC Remands
- [ ] Litigation Support is able to input CAVC data into Caseflow 
- [ ] Litigation Support is able to complete their 90 day letter task in Caseflow
- [ ] Litigation Support is able to add admin actions to the case
- [ ] JMR & JMPR CAVC Remands are distributed to VLJs via the Auto-Distribution Priority Job 
- [ ] JMR & JMPR CAVC Remands are prioritized in the Case Ordering Logic

**Comment by araposo-tistatech** [comment]
moved to Jira, closing
