### ISSUE TITLE
Support AMA CAVC Remands MDR

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#15221]
## Background/context

In some cases a CAVC Remand will be received by the Board without a mandate. These decisions are called Memorandum Decision on Remand. When the Board receives this type of CAVC decision the remand needs to be entered into Caseflow, but be placed on hold for typically 90 days or until the mandate is received. 

## Goals

Litigation Support is able to initiate CAVC Remand for MDRs. 
Judge teams are able to process decisions for MDRs. 

## Success criteria

AMA CAVC MDRs are no longer processed in VACOLS
AMA CAVC MDRs are processed & dispatched via Caseflow Queue

## Stakeholders

CAVC Litigation Support

## Requirements/stories

- [ ] As a CAVC Litigation Support user I need the ability to identify an MDR was received on the CAVC Remand entry form so that I can initiate the MDR process. #15384

- [ ] As a CAVC Litigation Support user when the MDR radio button is selected all the issues presented on the entry form are deselected as the issues may not have been provided by CAVC at this point. #15385

- [ ] As a CAVC Litigation Support user when the MDR radio button is selected I need the judgement and mandate date to be removed from the CAVC entry form as I would not yet have this information for MDRs. #15386

- [ ] As a CAVC Litigation Support user when I complete the CAVC entry form for a CAVC Remand MDR I need a new appeal stream to be created & linked to the Boards previous decision docket number so that a new decision could be issued. #15387

- [ ] As a CAVC Litigation Support user, I need the MDR data input on the entry form to be stored and retrievable, so that I can view this information while processing the case at a later date. #15388

- [ ] As a CAVC Litigation Support user, I need a new task type to be created for MDR CAVC Remands, so that the task can be placed on hold until I need to continue processing the case. #15389

- [ ] As a CAVC Litigation Support user, I need to be able to input additional information into Caseflow after mandate is received on an MDR, so that a 90 day letter can be sent. #15390

### Designs and workflows
https://whimsical.com/VyXzGFZxWmr3mg7Fzy9Tvi

### Dependencies
#15219

**Comment by araposo-tistatech** [comment]
moved to Jira, closing
