### ISSUE TITLE
IHP Tasks & POA Updates Automation 

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#15247]
## Background/context

This epic aims to capture POA updates in Caseflow more frequently as well as create new IHP tasks for Board VSO changes. At the Board IHP writing POAs are given the opportunity to prepare a new IHP when a POA change occurs. This means if there is an active IHP task for the former POA that task needs to be cancelled and a new task needs to be created and assigned to the new POA. If an IHP task was completed by the former POA that IHP becomes void and a new IHP task needs to be created for the new POA. 

## Goals

To automate the process of requesting a new IHP when POA changes occur on an appeal as well as ensure POA updates are being captured in Caseflow within a reasonable time frame. 

## Acceptance criteria
- [ ] Caseflow captures POA changes in VBMS within a reasonable time frame (possibly daily)
- [ ] If POA changes occur Caseflow automates the closing of active IHP tasks and opens a new task for the new POA

## Success criteria

- [ ] If POA changes occur Caseflow automates the closing of active IHP tasks and opens a new task for the new POA
- [ ] Caseflow captures POA changes in VBMS within a reasonable time frame (possibly daily)

## Stakeholders

VLJ
Attorneys
VLJ Support

## Requirements/stories

- [ ] Job Story: When a POA is updated in VBMS, Caseflow needs to be updated daily, so that IHP tasks are routed to the correct POA on a case. #14974
- [ ] Job Story: When a POA is updated in VBMS any open IHP tasks with the old POA needs to be closed and a new IHP task needs to be sent to the new POA on the case, that way there is no delay in opening and completing IHP tasks for the case. #14975
- [ ] Job Story: When a POA is updated in VBMS in some cases a new IHP task needs to be created and sent to the POA even if an IHP task has been completed on the case. #15023
