### ISSUE TITLE
Intake | Docket Change | Docket switch recommendation

### ISSUE THREAD

**Issue by mbaenatan** [department-of-veterans-affairs/caseflow#15331]
## User or job story
As a BVA Attorney with the Office of the Clerk of the Board, I want to be able to add and send a docket switch recommendation to a judge so that they can review and rule on it.

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: `docket_change`
- [ ] This feature should be accessible to the following user groups: `ClerkOfTheBoard` organization
- [ ] When a user selects "Send to judge" in their action-dropdown, this screen is triggered
- [ ] Please refer to the attached designs for the front-end components
- [ ] The hyperlink field should be required
- [ ] If the case is assigned to a judge (who is NOT a judge_user in the Office of the Clerk of the Board org), default to displaying that assigned VLJ's name in the "Assign to judge" field 
- [ ] ~If the case is NOT assigned to a judge (who is NOT a judge_user in the Office of the Clerk of the Board org), default to displaying a judge_user in the Office of the Clerk of the Board org's name~ Updated - leave with no judge selected if there is no assigned judge, and a COTB user will select one
- [ ] The "Submit" button should be inactive until all fields are filled
- [ ] Add Jest test
- [ ] Add Storybook story
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: [link]

### Out of scope

Moved to another eng ticket ( #15420 ):
- [ ] Submitting this form should trigger an API request to create a `DocketSwitchRulingTask` assigned to the judge
- [ ] The `instructions` field for the `DocketSwitchRulingTask` should be populated with properly formatted text (please see the third design)

### Designs

**Blank screen design**
![10  Switch Dockets_ Send to Judge](https://user-images.githubusercontent.com/51714306/94729993-29cfee00-0328-11eb-8b02-c073c092c4dc.png)

**Example of active "Submit" button once information is entered**
![10  Switch Dockets_ Send to Judge - Filled](https://user-images.githubusercontent.com/51714306/94729867-f4c39b80-0327-11eb-964f-739b50c0ed14.png)

**Task Instructions that a VLJ would receive once a user has submitted**
Note: Please bold what is indicated, it's okay to have the text overflow (not necessary to break after each piece of content)
![Screen Shot 2020-10-09 at 2.30.28 PM.png](https://images.zenhubusercontent.com/5d07e8c541e1974be7393f74/060645c6-0784-4115-9a5c-4a74741b2c4a)

### Background/context
This is giving OCB users the ability to send their recommendation to a VLJ so they can rule on the docket switch.

### Technical notes
- #15341 created stub route for this. Place the container component that wraps this view as a child of the appropriate route.
- This is analogous to the `ReviewMotionToVacateView` (and children) in the MTV flow. You should be able to use similar logic for populating the `SearchableDropdown` for judges.
- This seems like a good opportunity to adopt form management/validation libraries. It's not strictly necessary, but would be a good bonus. Ask @jcq for more info on this.

### Resources/other links

[Figma file](https://www.figma.com/proto/8vchXpD64DehW7tCYUOSD6/Docket-Change_July-2020?node-id=560%3A1859&viewport=594%2C-438%2C0.32505378127098083&scaling=min-zoom)
[End-to-end Mural](https://app.mural.co/t/workqueue2001/m/workqueue2001/1601042285247/0e921ee1c3286b3cc4ecaeb5298399b71d51bbe0)

**Comment by rutvigupta-design** [comment]
@jcq added in a screenshot for the VLJ task instructions - let me know if there's anywhere else the design needs to be added/referenced.
