### ISSUE TITLE
Confirmation page | Update emoji styling

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#1566]
As a case worker I would like to know when I finish my assigned cases for the day. I would like to receive a congratulatory message when all my cases have been completed.

## AC
1. Verify that the emojis appear in the correct order (add pic): Flex biceps, Laptop, flag
1. Verify that the Emojis are above `Way to go!` text 
1. Verify that Way to go! is in`h2`
1. Verify that the Emojis and End product has been created line are 15px apart
1. Verify that the copy shown before the emojis reads: 

## Current:
<img width="595" alt="emojis" src="https://cloud.githubusercontent.com/assets/4975959/25015000/03486b48-2048-11e7-8c0c-8bea78e0c578.png">

## New mock

![image](https://cloud.githubusercontent.com/assets/13420618/25662830/eff3983c-2fe3-11e7-95aa-993e086ae944.png)

**Comment by lakohl** [comment]
We need to use the right emojis and put them in the right order. They could also be bigger!

**Comment by Sjones352** [comment]
### Tasks to do
- [ ] Verify that the emojis appear in the correct order (add pic): Flex biceps, Laptop, flag
- [ ] Verify that the Emojis are above `Way to go!` text 
- [ ] Verify that Way to go! is in`h2`
- [ ] Verify that the Emojis and End product has been created line are 30px apart
- [ ] Verify that the copy shown before the emojis reads: 

<img width="727" alt="screen shot 2017-04-25 at 8 22 38 am" src="https://cloud.githubusercontent.com/assets/23080951/25385028/8956a848-2990-11e7-82bd-512c4c57114f.png">

**Comment by astewarttistatech** [comment]
Blocked due to Dispatch acting wonky.

**Comment by kierachell** [comment]
- Emojis are way smaller than the mocks
- Not sure what AC #4 refers to?
<img width="880" alt="screen shot 2017-05-02 at 7 34 52 pm" src="https://cloud.githubusercontent.com/assets/18075411/25643596/a324e83c-2f6e-11e7-98fa-6c5fc3001cc7.png">

**Comment by Sjones352** [comment]
@kierachell the Emojis are small because we failed to get the free svgs to actually use big emojis. @gnakm maybe I should change `Way to go!` to maybe an h4 and then it would match with the emojis.
@gnakm having svgs would be helpful coz this issue also calls for emojis
https://github.com/department-of-veterans-affairs/caseflow/issues/1562

**Comment by Sjones352** [comment]
@kierachell after speaking to Gina, please see the updated AC and hopefully it resolves this issue.

**Comment by kierachell** [comment]
**PASSED**
<img width="690" alt="screen shot 2017-05-04 at 11 01 06 am" src="https://cloud.githubusercontent.com/assets/18075411/25710019/fc3c2b6a-30b8-11e7-9774-f463019a0e05.png">
