### ISSUE TITLE
Docket Switch | Fix Multiple Issues

### ISSUE THREAD

**Issue by jcq** [department-of-veterans-affairs/caseflow#15733]
## Description
This compiles a few issues that have been noticed when running through the Docket Switch flow.

## Acceptance criteria
- [ ] Ensure `DocketSwitchMailTask` can only be created if `docket_switch` feature toggle is enabled
- [ ] Ensure attorney list gets properly populated in `DocketSwitchRulingContainer`
- [ ] Ensure Docket Switch Task Flow gets updated properly upon denial

## Technical notes

`DocketSwitchMailTask` should likely be modified like so:
```rb
def allow_creation?(user)
  ClerkOfTheBoard.singleton.user_has_access?(user) && FeatureToggle.enabled?(:docket_switch, user: user)
end
```

---

`DocketSwitchRulingContainer` is currently using code that expects the list of attorneys and the selected/previous attorney to come from the backend as part of the data in the task. That hasn't been set up, however. 

Instead, why don't we pull this stuff from other items existing in the Redux store...? It seems there is already an array of attorneys in the store at `queue.attorneys.data`. And the pre-selected attorney ID should be the same as the `assignedBy.id` on the current `DocketSwitchRulingTask` (also already in Redux).

### Task Flow
After a `DocketSwitch` object with a `denied` disposition is created by an attorney, the `DocketSwitchDeniedTask` gets closed with a status of `completed`. Currently the `DocketSwitchRulingTask` assigned to a judge gets updated with a status of `assigned` while the `DocketSwitchMailTasks`, one assigned to organization and one assigned to user, both have a status of `on_hold`.
