### ISSUE TITLE
Refactor Intake Form Review Components

### ISSUE THREAD

**Issue by meckila** [department-of-veterans-affairs/caseflow#16309]
## Background/context
A [production issue](https://dsva.slack.com/archives/C54QCEHAL/p1621448135033600) revealed that when a user goes down the path of choosing an unlisted claimant could successfully intake without a receipt date. Validation doesn’t immediately occur on the form page, but on submission to the backend. It occurs when submitting to the backend via 3 different functions. 

## Goals
We can simplify the intake review pages by moving validation to the frontend: using a validation schema for each form type. 

Additionally, there are 5 separate components for the forms with duplicate fields. We consolidate them into one form and use conditional logic for which fields to render. This allows for the addition of future validation and prevents intaking without required or invalid fields.

### Roadmap
- [x] [16291](https://github.com/department-of-veterans-affairs/caseflow/pull/16291) - Individual review pages now define - and export their own yup schema and parent review component  imports schemas depending on type, use react hook form
- [x] Remove custom frontend validation for appeal form in on submit action
- [x] Create json mapping of form fields for review page 
- [x] #16316 Use schemas to map the form fields for each form via form generator
   - [x] #16316 - Replace appeal intake form page [Nik]
   - [x] #16316 - Replace higher level review form page [Nik]
   - [x] #16317 - Replace supplemental claim page [Nik]
   - [x] #16318 - Replace RAMP election form page [Meckila]
   - [x] #16319 - Replace RAMP refiling form page [Nik]
- [ ] Remove Redux from form state and button state management
  - [ ] Remove redux from SelectClaimantConnected and  use form values in place of intake data state
  - [ ] Set requestStatus.submitReview

## Success criteria
- An intake user can intake each of the 5 intake forms with no change to user experience
- Switch which submit function is called based on the form type

## Requirements/stories
- Each of the 5 forms can be intaken
- AMA date validation passes

## Open questions
How to remove use of Redux tracking form state?

## References/Resources
[Yup Documentation](https://github.com/jquense/yup) 
[Caseflow Form management](https://github.com/department-of-veterans-affairs/caseflow/wiki/Frontend-Form-Management)

### Business value
Prevent intaking forms with missing required fields or fields that do not pass validation
