### ISSUE TITLE
Add Google Analytics in Reader

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1974]
### Tasks
- Figure out what we're already tracking, if anything, in GA
- Set up tracking for specific page elements.

### Questions to consider:
- How often are users searching (# of searches per case)? What are they entering into search?
- How are they using categories? Are they ever selecting multiple categories, and what combination(s)?
- How are they using the category filters? What combination of category filters is most common?
- Comments: character count, # per page/per doc
- Read/unread ratio
- How are they using the issue tag filters? How many tags are they including in a filter?
- Common user paths (Documents list > inside a document > back to documents, etc.)
- Average time spent within an entire case and within different document types (note: we won't have a sense of active/inactive time spent in GA)
- How long are people spending on the Documents List page? How long are they spending in documents?
- Tracking specific user selections:
   - Expand all button
    - Back to all documents button
    - "Hide menu" button
    - Send feedback 
    - Help
    - Search 
    - Arrows within document 
    - Zoom 
    - Doc Type link in viewer
    - Reader logo

Draft of broader analytics strategy documented [here!](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Reader/Product%20and%20Launch%20Documents/Reader%20Analytics.md)

**Comment by abbyraskin** [comment]
Note: we need to investigate which of these have already been added into GA

**Comment by NickHeiner** [comment]
We did [some investigation](https://dsva.slack.com/archives/C4N3QTLT1/p1495566664380276). 

Google Analytics is enabled for all of Caseflow, but it's not working in Firefox. So if our users are on Firefox, GA will not show up for them.

**Comment by abbyraskin** [comment]
Note: now that we're using Chrome instead of Firefox, we should check what's enabled/tracked.

**Comment by NickHeiner** [comment]
I don't see any GA hits for Reader today. Odd.

[Analytics Caseflow All Web Site Data Overview 20170601-20170601.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/1046129/Analytics.Caseflow.All.Web.Site.Data.Overview.20170601-20170601.pdf)

**Comment by abbyraskin** [comment]
@tejans24 is this blocked?

**Comment by tejans24** [comment]
There are a few problems that need to be solved for this issue:
- [ ] Url in Google Analytics needs to be corrected
- [ ] Google Analytics Id needs to be fetched from an environment variable in Caseflow
- [ ] Google analytics accounts need to be created for different environments
- [ ] Update deployment configuration to include the GA id's based on the environment in the Appeals-deployment repository.
- [ ] Update the method that in application.erb that is sending incorrect url information to GA
- [ ] Update code to support React-router urls to work with Google Analytics.

**Comment by shanear** [comment]
this was completed by https://github.com/department-of-veterans-affairs/caseflow/pull/2578
