### ISSUE TITLE
Style guide | Survey action items

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2353]
### Summary
Marian and I reviewed the results from the Style Guide Feedback Survey, debriefed on our findings and put together some next step action items

### TODO
- [ ] Instructions on how to update Style guide (Gina/Marian)
- [ ] Adding a section with sketch file and icon (Gina)
- [ ] Make announcements on slack channels 
- [ ] Engineering perspective - Add more documentation of use cases (Marian)
	- Where it's being used? 
- [ ] Demo for updates (Gina/Marian)
- [x] Demo to Vetsdotgov team (Marian)

**Comment by mmlumba** [comment]
`Don't show`
^ ...not sure if that was supposed to start a sentence

**Comment by mmlumba** [comment]
@gnakm What do you think about closing this issue? It seems like some of these can be separate tickets:
* Engineering perspective - Add more documentation of use cases (Marian)
* Adding a section with sketch file and icon (Gina)
* Instructions on how to update Style guide (Gina/Marian)

And some of these are ongoing responsibilities that should be added to some doc somewhere:
* Demo for updates (Gina/Marian)
* Make announcements on slack channels

**Comment by gnakm** [comment]
yeah let's do that!
