### ISSUE TITLE
EPIC:  Decision Review:  Ability to review and discern a result for an appeal case

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#404]
As a Caseworker, I would like the ability to view case information and designate the next steps results for a final decision case and manage retrieval of the next item in the queue so that I start the process of dispatching an appeal case item.

**Acceptance Criteria**
- [ ] Ability to view veteran’s case information requiring the review of a final decision, such Veteran Name, Case ID, etc.  #405 
- [ ] Ability to review Decision form. #405 
- [ ] Ability to designate the review results for an appeal #406
- [ ] Ability to quickly retrieve the next item in the queue.  #421 
- [ ] Ability to cancel the processing of the current case.  #415 , #419 , #410 
- [ ] Ability to receive notification of successful or unsuccessful submission of review results. #420 , #422

**Comment by nikitarockz** [comment]
Moving item to PM board.
