### ISSUE TITLE
Decision Review: Show Decision PDF and information

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#405]
As a Caseworker, I want to be able to view and verify the latest VBMS .pdf decision document along with pertinent veteran information that has been uploaded to VBMS so that I can determine the next steps for the appeal case.

### Acceptance Criteria
1. Verify that on the Decision Review page, the following appeal information is displayed:  Veteran Last Name, Veteran First Name, Case ID. (Refer to mockup for layout details)
1. Verify that on the Decision Review page, the appeal information (Veteran Name and ID) is display only and cannot be edited.
1. Verify that a pdf version of the Decision document is displayed for viewing only.
1. Verify that on the Decision Review page, there is a "Create End Product" button. 
1. Verify that there is a “Send to RO” link on the Decision Review page. 
1. Verify that there is a "Cancel" link on the Decision Review page.

### Mockup
![405 - decision review page](https://cloud.githubusercontent.com/assets/23063044/20578700/8f889860-b196-11e6-84aa-eeab78a7f0e8.PNG)

### Technical notes
- The document to grab will be based on the decision date being within +/- 1 day of the recorded decision in VACOLS.
- The decision date will have a specific VBMS document type. We'll need to obtain this exact type #.
- The decision document should be pulled from the efolder matching the veteran's VBMS id.

### Sub-Tasks

- [ ] Set up infrastructure for pulling individual document by type number.
- [ ] Build UI for page
- [ ] QA Discovery and scripting.

**Comment by joofsh** [comment]
@nikitarockz Are there designs that go with this ticket? Want to make sure it visually matches the way you & lara expect

**Comment by nikitarockz** [comment]
Yes, there are designs and should be attached soon.  Sorry, we gotta he story done before designs being updated.



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by nikitarockz** [comment]
@mdbenjam I have updated.  Sorry for the delay.

**Comment by mdbenjam** [comment]
@nikitarockz 

Two questions on this ticket:
- Regarding requirement 1, is this referring to the information at the top of the page?
- Regarding requirement 4, what happens if the decision date in VACOLS is more than 1 day from the date of the uploaded document?

**Comment by nikitarockz** [comment]
@mdbenjam  I added an 8th verification option that displays a message when there is no signed decision available.

**Comment by mdbenjam** [comment]
@shanear @nikitarockz @lakohl @joofsh @sharonwarner @abbyraskin @cmgiven 

I wanted to summarize our conversation, and propose a way forward. Please comment with any corrections or thoughts.

A single eFolder can have multiple appeals. Currently we use the decision date to correlate which VACOLS appeal this decision goes with. In some (~1% of) cases there are multiple decisions for one veteran within the same 24 hour period.

Cases:

- There are no decisions
  - Possibility 1: The decision hasn't been uploaded yet, but will be
  - Possibility 2: The decision is stuck somewhere, and needs nudging
  - Possibility 3: The date in VACOLS or VBMS was fat-fingered
- There is one decision:
  - Great!
- There are multiple decisions
  - I propose we show them both

We need to sort out how to deal with the no decision case for the MVP. It seems as though there are three possibilities.

1. Escape Hatch: When a user picks a task that cannot be completed with caseflow, we display a screen that says to complete it as they normally would, and to mark it as complete when they finish.
2. Wait for Fix: Create a new task type "WaitingForDecision" that we create when the decision dates aren't aligned. Every night, we try to turn these tasks into CEST-ing tasks. We surface these tasks to managers so they can follow up on them, if they don't appear after a certain amount of time.
3. VACOLS Version: Display the unsigned decision that is attached in VACOLS rather than the VBMS document.
4. Digital Signing: Wait for the implementation of digital signing decisions. Once we control that aspect, these problems go away.

Solution 2, requires a lot of engineering that will (hopefully soon) be removed. Solution 3, might work, but means there is no pressure on dispatch to actually upload the documents. I think solution 1 is our best near term solution as we wait for solution 4 to become available.

Thoughts?

**Comment by lakohl** [comment]
I agree. For the MVP I would vote for solution 1.  It could be useful to build in i
a way of keeping track of these case numbers that require manual processing- both to keep tabs on the frequency of these events and to check back later to see if those cases were actually processed.

**Comment by abbyraskin** [comment]
@mdbenjam my only concern with solution 1 is that this will be almost always be true. When we visited Dispatch at BVA, they were generally at least 2 days (and up to 10 days) behind on scanning/uploading. Presumably this lag varies based on workload, and we visited during a particularly low workload period. AMC, on the other hand, is often working closer to schedule (meaning: they're able to process cases within 1-2 days from the point they are dispatched to them by BVA).

**Comment by mdbenjam** [comment]
@abbyraskin So does that mean they're almost always working off the document attached in VACOLS?

**Comment by KHarshawat** [comment]
I think the no-decision case might be moot because we shouldn't show the users any appeals that we haven't detected a decision for in VBMS. This should be part of the queue logic.

**Comment by abbyraskin** [comment]
@mdbenjam i think there's often/usually no signed decision in VBMS at the point they go to establish the EP.

i don't have exact stats on how they proceed, but there seems to be some internal disagreement about whether they're "supposed" to move ahead with processing if the signed decision has not yet been uploaded. I think some folks feel more comfortable waiting for the signed decision (a scenario where folks are holding onto, and potentially losing track of, cases) while others go ahead and work from the unsigned VACOLS copy. of the two cases i observed Bill CEST, both were missing a signed decision in VBMS.

from the manager's perspective, they're allowed/encouraged to process cases using the unsigned document.

**Comment by KHarshawat** [comment]
If there are multiple decisions, rather than previewing both decisions I'd recommend we show the names of both files as links and let the user click into each one to determine which is correct (or perhaps expand and collapse the preview for each potential decision)

**Comment by mdbenjam** [comment]
@KHarshawat The problem with enforcing a "you cannot work on a decision until it is scanned" workflow, is that I think we will lose cases. If a decision doesn't get scanned for a month, we have no way of surfacing this to a manager. No one will know to track down this case. I think we need some flow here until we control the uploading of decisions.

**Comment by KHarshawat** [comment]
@mdbenjam makes sense. I'm still comfortable with solution 1 then, even if it'll happen quite regularly at first. Basically note that the decision wasn't found in VBMS, ask the user to check the unsigned decision how they normally would (which may mean manually finding the decision from VACOLS), the proceeding to the EP creation form or re-routing form. If for some reason the decision doesn't look correct or can't be found, the user can cancel out of it and explain to their manager why.

**Comment by shanear** [comment]
@mdbenjam we were discussing a way of automatically rechecking for decisions for 3 days (using tasks under the hood). Then, if no decision is found after that, we'd add them to a work queue that could be dealt with by an admin.

**Comment by shanear** [comment]
@KHarshawat @mdbenjam An MVP could be to leave out them manual work queue for now, and just have a dumb table report of all appeals waiting for a decision.

**Comment by joofsh** [comment]
We should be _very_ careful with adding escape hatches. This leads to data integrity issues and is exactly why our job implementing this feature is challenging to begin with. 

Based on what @abbyraskin has said, Option 3 most closely aligns with the current process & is approved/encouraged by the AMC managers. I fail to see any value in showing the actual PDF document, especially if the VACOLS document can more dependably and easily found. Solution 3 solves the most edge cases and minimizes technical complexity.

Is there some upside to showing the PDF decision that I'm missing?

**Comment by abbyraskin** [comment]
At the very least, I'd like to get a BVA attorney's legal perspective before we default to unsigned decisions.

I'm concerned we'd essentially encourage a broken business practice. There *shouldn't* be a delay between dispatching a decision and scanning/uploading the document to VBMS. AMC is using FTP as a workaround, and coaches are inclined to support this practice because it affects how they measure output. 

Another thought in the meantime...what if we automatically recheck for decisions for 3 days, and if there's still no signed documented found in VBMS, we add them to the work queue on day 4 with a pseudo escape hatch (I like @KHarshawat's handling - it mostly still keeps them tracked and using Caseflow). This would prevent users from always seeing the "no signed document" message, but also allow them to use Caseflow (along with VACOLS) if the unsigned document isn't uploaded yet. 

We could also consider just showing the unsigned document at this point, but with some sort of notice that it is unsigned.

**Comment by mdbenjam** [comment]
JD and I had another long talk about this, and we have a lot more thoughts. I'm going to try and capture it all here.

JD has me very worried about escape hatches now. The concern is that we would be responsible for tasks that are out of our control to verify. One general pattern we came up with to address this issue is forking workable vs non-workable cases. For example, in the nightly job where we gather all the tasks to complete the next day, we could add further logic to only add appeals that have a valid decision in VBMS. The remainder of the appeals would be thrown into a CSV and given to AMC. AMC could have a few employees move to our new system to handle tasks in the "new workflow" and the remaining employees could work on the "legacy workflow."

The advantage with this system, is it absolves us from being responsible for edge case tasks. Anything that doesn't fit our idea of what an appeal looks like is given to an employee to resolve. In this particular case if we could get AMC more in sync with dispatch, most cases would be workable through our system, and a select few would continue in the legacy workflow.

To help decide which of these options to take, I think we need to answer the following questions:

- Is using the unsigned decision attached to VACOLS okay? 
  - If so, then we should just use this in all cases.
- What is the timeline on e-signed decisions?

**Comment by KHarshawat** [comment]
Timeline for e-signed decisions is quite soon since they've been piloting it for several weeks now. Nicholas can chime in with more. The biggest issue is whether the e-signed decisions are actually getting uploaded to the eFolder right now. Once we work on the workflows for the teams involved (judges,co-located staff, and dispatch branch) we can guarantee that signed decisions will be uploaded promptly but I'm not sure how quickly that's happening now with the eSign pilot.

**Comment by abbyraskin** [comment]
I will loop around with Nicholas (who is traveling today) and report back.

**Comment by lakohl** [comment]
This is obvious, but I just realized that if we use the decision in VACOLS it most likely will not be a .pdf. file. Will we need to convert it into one in order to display it in Caseflow Dispatch?

**Comment by KHarshawat** [comment]
Yeah, I'm not super keen on using the VACOLS decision. It's not desirable long term and is kind of a hack.

**Comment by astewarttistatech** [comment]
@nikitarockz AC needs some changing. Let me know when finished. Thanks.

**Comment by nikitarockz** [comment]
@astewarttistatech  I updated the ACs as discussed.  Left AC#4, we just have to add data to table to validate this one.  

AC Changes
- Removed the last AC regarding message for no decision found
- Removed AC referencing Email RO link (not shown in mockup)

**Comment by nikitarockz** [comment]
I updated the ACs.  I move the AC referencing the +/- decision to the technical note section which at this time is more relevant there than as an acceptance criteria.

**Comment by astewarttistatech** [comment]
**PASSED**

Please see attached.
<img width="579" alt="screen shot 2016-12-02 at 2 36 46 pm" src="https://cloud.githubusercontent.com/assets/23038505/20847588/ca7b219c-b89c-11e6-9b1f-13d57db64cda.png">
