### ISSUE TITLE
Create Background Job to import Tasks

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/caseflow#426]
Create a background job that will nightly check for full and partial grants and create establish claim tasks for them.

Prerequisites:
- [x] Manually install and associate a redis instance for dev, UAT and prod (devops task) https://github.com/department-of-veterans-affairs/appeals-deployment/issues/136
- [x] Add redis support in code to caseflow #313 
- [x] Add support for background jobs to Caseflow (via sidekiq) (https://github.com/department-of-veterans-affairs/appeals-deployment/issues/197)

background job PR: https://github.com/department-of-veterans-affairs/caseflow-certification/pull/432

**Comment by orischwartz** [comment]
(updated root comment with links to related issues)

**Comment by joofsh** [comment]
@astewarttistatech fyi I don't think this needs QA efforts. It's completely disabled atm

**Comment by shanear** [comment]
@joofsh I'd like to test this out in UAT on some real data. Do we have a good way of doing that?

**Comment by joofsh** [comment]
@shanear You should be able to manually trigger the background job from the UAT console `CreateEstablishClaimTasksJob.perform_now`. This would fetch any real appeals that are full/partial grants and create tasks for them. Just be aware that the side effects of testing this are:

- It will create Appeal db rows for those appeals (not a big deal imo)
- It will create new tasks EstablishClaim tasks that would potentially become complete directly in VBMS. So we may want to delete the created tasks after testing?

As far as "real" data, I have no idea what sort of data is on UAT. Similar to your de-certify method, we may have to invest time into setting up an appeal on UAT that is ready for an End Product. Let me know if there's any way I can assist you with that

**Comment by shanear** [comment]
@joofsh Sounds good, i'll just run the job from the console. We will be using VBMS UAT too (that's why i say "real" data), so it's ok if we create claims there. Also I think we'll want a script to create an appeal that's ready for claims establishment, I can work on that.

For now though, we should test that it makes tasks for any appeals that are ready for Claims Establishment now on UAT.

@cmgiven could you do a quick scan to see what appeals on UAT are ready to Establish Claim? I'll run the script and verify that that many tasks are created.

**Comment by cmgiven** [comment]
It should find 443 remands/partial grants ready for cesting. Note that I haven't checked whether EPs exist for these in VBMS UAT, so this is just what it should find on the VACOLS side.

It shouldn't find any full grants, as UAT doesn't include anything decided within the last three days (or even the last three-ish years).

**Comment by shanear** [comment]
There was a bug in the full_grant job. Me and @joofsh discussed. Move it on over to validation when it's ready
