### ISSUE TITLE
Co-located table | Establish table for co-located users

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#6077]
When a co-located team member is planning what to work on, they need to see all tasks assigned to them in one place and the types of tasks, so they can prioritize what to work on.

## AC
- Establish the table component that will be used in each of the tabs (New, Pending action, On hold) in the designs. 
- Verify the table contains the following columns:
   - Case details
   - Task
   - Type(s)
   - Docket number
   - Days waiting (definition here: https://github.com/department-of-veterans-affairs/caseflow/issues/5888)
   - Veteran documents
- Verify the link in the Veteran documents column navigates the user to the correct Veteran claims folder in Reader

## Out of scope
- Implementing the tabs
   - https://github.com/department-of-veterans-affairs/caseflow/issues/6078 Colocated New Tab
   - https://github.com/department-of-veterans-affairs/caseflow/issues/6079 Colocated Pending Action Tab
   - https://github.com/department-of-veterans-affairs/caseflow/issues/6080 Colocated On Hold Tab

##### New Tab
![colocated-table-new-tab-single-actions-768](https://user-images.githubusercontent.com/31224257/43283661-80eb7dae-90e7-11e8-9f71-01abb998f958.png)

##### New Tab with Tooltips
![colocated-table-new-tab-single-actions-wtooltips-768](https://user-images.githubusercontent.com/31224257/43283662-81092944-90e7-11e8-95ca-4bbfcc7a9cd1.png)

## Open Question
- @sneha-pai - should the column be `Days waiting` like it is for attorneys and judges, or `Total days waiting`?

**Comment by mkhandekar** [comment]
I've updated the link to the design under "mocks" in the original issue.

**Comment by evankroske** [comment]
## Implementation Plan
- [ ] Load the user's colocated tasks into the store. Estimate: 2 days.
- [ ] Add a page component for colocated admins.
- [ ] Add a table with the admin's tasks.
- [ ] Code review. Estimate: 2 days.
