### ISSUE TITLE
Co-located table | Pending action tab

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#6079]
As a co-located user, I want to distinguish which cases and tasks are are pending action to come off of hold, so I can potentially reduce the amount of time a Veteran is waiting for a decision.

When an admin action's hold is up, co-located team members want to be alerted, so they can continue working on the case ASAP and move the appeal along in the process.

## AC
- Establish the 'Pending action' tab
- Verify that cases come to the Pending action tab when:
   - Their hold time has completed (days on hold = hold time)
   - New documents have been added to that Veteran's eFolder (#5593)

### User Stories
- When an admin action's hold is up, co-located team members want to be alerted, so they can continue working on the case ASAP and move the appeal along in the process.

### Mocks
https://app.mural.co/t/workqueue2001/m/workqueue2001/1533518524532/52ce941ed69a8a4887b2f6d778e00a4c3597c284

<details><summary>Out of date mock</summary>
![colocated-table-pending-action-tab-768](https://user-images.githubusercontent.com/31224257/43294059-7e8bf330-910b-11e8-8e19-8c384e0f231e.png)
</details>

**Comment by evankroske** [comment]
## Implementation Plan
- [ ] Add selector for pending tasks: 1 hour.
- [ ] Add tab. Estimate: 1 hour.
- [ ] Add column "Total Days Waiting". Estimate: 1 hour.
- [ ] Add a test. Esimate: 1 hour.
- [ ] Get PR approved. Estimate: 1 day.

- Total estimate: 1.5 days.

**Comment by evankroske** [comment]
@mkhandekar , I've got a question about the "Total Days Waiting" column. When a case appears on the pending tab because it has new documents, what should be shown in the column?

**Comment by mkhandekar** [comment]
Answer to Evan's question is: "#A of #"B . (A = number of overdue days, B = number of total days waiting)

See [slack conversation](https://dsva.slack.com/archives/C6E41RE92/p1535035633000200) for context.
