### ISSUE TITLE
Case details | Task information

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#6081]
When a co-located admin support user begins working on an admin action assigned by an attorney, they need to see the instructions that the attorney wrote, so they can interpret what needs to be done and complete the task correctly. 

## AC
- Verify the Case snapshot section of Case details includes a `Task` section
- Verify the Task information is the instructions that the attorney submitted when assigning the admin action
- Verify the `From:` field is the attorney who assigned the case

## Mocks
https://va-gov.invisionapp.com/share/J7KWANGRED5#/screens/302777517

## Related
- Allowing co-located to view multiple admin actions in the task section of Case snapshot - https://github.com/department-of-veterans-affairs/caseflow/issues/6015 cc: @mkhandekar

**Comment by evankroske** [comment]
## Implementation Plan
- [ ] Add task assignment information and instructions to CaseSnapshot. Estimate: 2 hours.
- [ ] Add a test for the new information. Estimate: 2 hours.
- [ ] Get PR approved. Estimate: 1 day.

- Total estimate: 1.5 days.
