### ISSUE TITLE
Case details | Actions | Place hold

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#6082]
As a co-located admin support user, I need to be able to place a case on hold and explain why. Many administrative actions require co-located support to send correspondence to Veterans and their POA and wait to hear back. Placing a case on hold gives the Veteran time to respond, and sets the foundation for the system to prompt co-located to check back on the case after a given amount of time. 

## AC
- Verify there is a drop down in the Actions column of case details that has the option to `Place hold`
- Verify that when the user selects `Place hold` they are taken to the beginning of the on hold flow

## Mocks
https://va-gov.invisionapp.com/share/J7KWANGRED5#/screens/302777517

**Comment by evankroske** [comment]
## Implementation Plan
- [ ] Add an actions dropdown for colocated admins. Estimate: 1 hour.
- [ ] Add a blank page to mark the start of the place-on-hold flow. Estimate: 2 hours.
- [ ] Add a test for the new dropdown. Estimate: 2 hours.
- [ ] Get PR approved. Estimate: 1 day.

- Total estimate: 2 days.
