### ISSUE TITLE
Co-located | Place hold screen

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#6083]
As a co-located user, I want to specify the amount of time I place a case on hold and explain why it's on hold, so I can move onto other ready tasks, get notified when my case is finished with its hold, and provide information as to why it's on hold to other Board employees that may access this case.

## AC
- Establish page to place a case on hold and design according to mocks
- Create dropdown for the user to specify the number of days on hold. Include the below time spans:
   - 15 days (what are y'alls thoughts on adding this shorter time span just in case? we could test if users select it, and it could prompt users to check on cases more frequently)
   - 30 days
   - 45 days
   - 60 days 
   - 90 days
   - 120 days
   - Custom
- If the user selects Custom, verify they can type in a custom amount of days
- Verify there is a text box for the user to describe a reason for the hold
- Verify when the user clicks `Place hold` they are taken back to their table, their `On hold` tab

#### Place on hold (default screen)
![colocated_places_case_on_hold-mvp](https://user-images.githubusercontent.com/31224257/43609600-7d2851de-9672-11e8-9cf9-b4e14a8d1cc4.png)

#### When 'Custom' is selected
![colocated_places_case_on_hold-custom](https://user-images.githubusercontent.com/31224257/43609455-0e7cb69e-9672-11e8-9e7d-ca2749390091.png)

#### If the user enters an invalid number or character
![colocated_places_case_on_hold-custom-error](https://user-images.githubusercontent.com/31224257/43609533-48a0b6b8-9672-11e8-88a3-7fa75055d09c.png)

## Open questions
@sneha-pai - are we going to include a textbox for co-located users to include information about the hold? if so, could you add mocks for that?

**Comment by evankroske** [comment]
## Implementation Plan
- [ ] Add case information to "Place task on hold". 1 hour.
- [ ] Add preset hold dropdown that stores the selected duration in the state. Estimate: 3 hours.
- [ ] Add custom duration box that stores the selected duration in the state. Estimate: 2 hours.
- [ ] Add place-on-hold button and connect it to the backend. 2 hours.
- [ ] Add error handling and messaging. Estimate: 3 hours.
- [ ] Add cancel button. Estimate: 1 hour.
- [ ] Add tests. Estimate: 1 day.
- [ ] Get PR approved. Estimate: 2 days.

- Total estimate: 5 days.

**Comment by laurjpeterson** [comment]
@dannysellers - what is the level of effort to add a notes field for the reason why a case was put on hold? I don't see it in caseflowdemo (I know we discussed removing the scope of co-located adding notes when they assign cases back to the attorney)

see designs here - https://app.mural.co/t/workqueue2001/m/workqueue2001/1533518524532/52ce941ed69a8a4887b2f6d778e00a4c3597c284
