### ISSUE TITLE
Epic 1 | Slotting Veterans | Regional office and alternate hearing location schedules

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#6575]
As a hearing coordinator, I want to be able to assign veterans to my Regional Office and associated hearing locations so I can easily manage the schedule of all my locations and send veterans to their closest locations. 

### Acceptance Criteria 
- [ ] Verify that there is an easy way to display alternate hearing locations associated with a Regional Office 
- [ ] Verify that there is an ability to add or delete alternate hearing locations (potential admin functionality split this out) - out  of scope. 
- [ ] Verify that there is a way to move veterans into a slot at the associated alternate hearing location 
- [ ] Verify that there is a way o delete slotted veterans at the alternate hearing location 
- [ ] Verify that there is a way to confirm all slotted veterans in the associated alternate hearing location
- [ ] Verify that there is a way to view the schedule by alternate hearing location once slotted

### Open questions 
- [ ] What is the best way to show the alternate hearing location schedule? In one meta view like we have now or slotted by individual RO 
- [ ] What does adding and deleting alternate hearing locations look like? From a data base perspective how are we updating? Any effects on the UI? 
- [ ] Once confirmed and there is a mistake, how do we undo?
   - Make them go to the schedule? 
   - An undo that persists for a little bit after? 
- [ ] Pros and cons of bulk assigning to the schedule 

### Related Issues
#6597 Epic 1 - Slotting Veterans
