### ISSUE TITLE
CO and Video Release |Epic Case Details | Confirmation Banner

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#6576]
As a hearing coordinator, I need a way to confirm the veterans I slotted into the schedule at an individual level.

### Acceptance criteria
- [ ] Verify that when a user assigns a Veteran in Case Details, the following confirmation banner with the following copy appears: 
  - Title: You have assigned [Veteran Name] [Hearing Type] on [Date]
  - Body: You have successfully assigned this veteran to a [hearing type] hearing. You can assign another veteran by going back to the Assign table or by using the link below to view the daily docket for that day. 
- [ ] Verify that the "Back to assigning hearings" option in the action is changed to View Hearing Day. 
- [ ] If the user clicks the view hearing day in the actions sections, it should pull up the corresponding Daily Docket in a _new tab_

### Mocks
![ticket slotting dropdown confirmation](https://user-images.githubusercontent.com/23316107/46484128-2223f000-c7c7-11e8-9c65-263e004dc990.png)

### Related Issues
#6575 - Epic 1 : Slotting Veterans
#6874 - Base Case Details

**Comment by Chingujo** [comment]
@oscarAtNava 

The only thing we are keeping about this ticket is the confirmation banner copy
