### ISSUE TITLE
Epic 2 |  Viewing the schedule | Editing functionality 

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#6592]
As a hearing coordinator, I need to be able to view the confirmed schedule and make any additional edits, deletions, or changes based on Veteran updates or revert any mistakes. 

### Acceptance Criteria 
- [ ] Verify that there is a schedule view that lists all the scheduled veterans for that regional office
- [ ] Verify that there is the ability to edit the schedule with the following capability: 
     - The time and date
     - Alternate hearing location 
- [ ] Verify that there is a notice that the edit has been confirmed
- [ ] Verify that there is a ability to remove a veteran from the schedule  
- [ ] Verify that once removed it replaces the veteran back into the potential list of Veterans to be scheduled

### Open questions
- Note that you can't edit a date and time unless there is an open hearing day. We can just remove them and put them into the master list or show suggested list if time permits. 
- same for alternate hearing location 

** how much can a h.c edit the schedule? 

### Related issues
#6593 Epic 2 : Viewing the schedule
