### ISSUE TITLE
Epic 2 | Viewing the schedule | Ability to put something on hold

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#6593]
As a hearing coordinator, I want to be able to keep track of all the postponed hearings so I can manage them in an efficient way and follow up as necessary instead of waiting until the day of the next hearing. 

### Acceptance criteria 
- [ ] Verify that there is a way to postpone or put a hearing on hold in the schedule 
- [ ] Verify that there is a way to keep track of these postponements in the UI
- [ ] Verify that there is a way to return a postponement back to active or remove them 

### Related issues
#6592 Viewing the schedule

**Comment by Chingujo** [comment]
don't worry about it - later

**Comment by MeredithStewart** [comment]
New epic replaces this one: https://github.com/department-of-veterans-affairs/caseflow/issues/8618
