### ISSUE TITLE
Video and CO Release | Epic - Viewing the schedule | Additional hearing information

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#6594]
As a hearing coordinator, I need to know additional information in the view schedule page to accurately be able to edit and coordinate my hearings. 

### Acceptance criteria 
- [ ] Verify that the schedule view shows the alternate hearing location
- [ ] Verify that there is hearing coordinator information from RO and Board side
- [ ] Verify that there is a notes field that hearing coordinators can use to update any pertinent information. 

### Open Questions
- [ ] If we design and add this information can this replace their daily docket? 

### Related issues
#6598 Epic 2 - Viewing the schedule

**Comment by MeredithStewart** [comment]
@Chingujo -- For this one, "Verify that there is hearing coordinator information from RO and Board side," we know they do not put this information in VACOLS today - they have it outside in spreadsheets. I'm not sure I'd prioritize that functionality, but I'm curious to what you're thinking on the matter!
