### ISSUE TITLE
Video and CO Release | Epic 2  Case Details - Base Page

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#6874]
As a hearing coordinator, I want to be able to see detailed information about a Veteran as part of the hearings review process, such as checking the form 9. 

### Acceptance Criteria
- [ ] Verify that clicking on a Veteran Name in the table takes you to the case details page
- [ ] Verify that the header of this page is Veteran Name | View Veterans Document | View assign hearings (see mock)
- [ ] Verify the following information in the snap shot area of the Case Details (see mock)
  - About the Case: 
    - Type
    - Docket 
    - Hearing Type
  - Veteran Address
  - Action with a dropdown called Select: 
    - This Action bar has three states depending on how the user enters this case detail view. 
    - Via the table, the dropdown should show "Assign Hearing" 
    - If a veteran has been scheduled, then the action should show "View Hearing Date" 
- [ ] Verify that the link next to the Veteran ID is "Assign Hearings"
- [ ]  Verify that the rest of the Case Details shows the way it is in Queue (see mock)
   - [ ] Verify in the hearings section the following logic: 
      - All prior hearings with a disposition are shown 
      - When a hearing is scheduled it shows with a null disposition to signify that it is the most current hearing

### Notes
- [ ] How are queue handling user permissions? Should we mimic this?

### Mocks
**Default**
![assign hearing co default 1](https://user-images.githubusercontent.com/23316107/45828665-1f090a00-bcc7-11e8-9a8a-9833fbe45f63.png)

** Dropdown Expanded**
![assign hearing dropdown](https://user-images.githubusercontent.com/23316107/45828768-5d9ec480-bcc7-11e8-9c18-c4fdd5dd3f05.png)

** Hearings area in case details**
![assign hearing co default 1](https://user-images.githubusercontent.com/23316107/45828946-c38b4c00-bcc7-11e8-9a23-92e6b68655f1.png)

## Notes
Please see

**Comment by oscarAtNava** [comment]
@Chingujo The veteran address is in the 'About the Veteran' section of the Case Details page. I do not think we should duplicate the address in the Task section. What is displayed there is the task information.

**Comment by Chingujo** [comment]
@oscarAtNava 

Agreed =D. Was an older mock
