### ISSUE TITLE
Video and CO Release | Epic Table view | Header Area

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#6876]
As a central office hearing coordinator, I need to know the tasks I need to be doing on this page, the "docket" I am viewing, and the current docket date quickly. 

### Acceptance Criteria
- [x] Verify that the title of the page is "Assign Hearings" 
- [x] Verify that there is a link called "View Hearing Schedule" 
  - This should eventually take you to the view hearing schedule page 
- [x] Verify that there is a dropdown called Hearing Location that is defaulted to Central 
   - All the regional offices will be present here BUT _no alternate hearing locations_
   - The regional office displayed should be in alphabetical from A to Z from the selected RO. For example if Houston, when you click it should not start from the beginning of the list. 

### Mocks 
![assign hearings_video dropdown expanded](https://user-images.githubusercontent.com/23316107/45564432-66eae580-b81e-11e8-802d-7a8b2dbdde90.png)

### Related Issues
#6597 Epic 1 Table View

**Comment by Chingujo** [comment]
@sharonwarner @MeredithStewart 

Made the mock to accurately reflect the searchable dropdown, which will be important as we add other special RO Codes

**Comment by MeredithStewart** [comment]
I'm not sure what the user story would be for an all category in the assign hearings table. I don't have concerns with the two states for the searchable dropdown.
