### ISSUE TITLE
Release 1 CO | Epic - Table view | Navigate from schedule

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#6904]
As a hearing coordinator, I need to be able to switch to the assign veterans view from the schedule to start slotting veterans. 

### Acceptance Criteria 
- [ ] Verify that there is a primary button called "Assign Hearing"  next to the title of the page
- [ ] Verify that clicking this button takes you to the Assign Veterans table
- [ ] Verify that there is instructional text with the following copy: 
  - You can use the “Assign Hearings” button above to slot veterans into the schedule. The table below also shows days that are scheduled and clicking on a specific day will take you to the “Daily Docket.

### Mocks
![minimal download schedule assign button](https://user-images.githubusercontent.com/23316107/45374046-fa25e000-b5be-11e8-93bd-bd1d8c7e7b46.png)

### Related Issues
#6597 Epic 1 Table View

**Comment by laurjpeterson** [comment]
Perhaps we can close this one too! @Chingujo

**Comment by jimruggiero** [comment]
@nicholer and @pshahVA The last person to touch this one was LP last July wondering if this could be closed. Can you confirm that this should be closed at this time?

**Comment by nicholer** [comment]
Closing - this work was completed.
