### ISSUE TITLE
Video and CO Release | Epic - Table View | Switch to assign hearings from schedule

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#6905]
As a hearing coordinator, I need to be able to switch to the assign veterans view from the schedule to start slotting veterans. 

### Acceptance Criteria 
- [ ] Verify that there is a primary button called "Assign Hearing"  next to the title of the page
- [ ] Verify that clicking this button takes you to the Assign Veterans table
- [ ] Verify that there is instructional text with the following copy: 
  - You can use the “Assign Hearings” button above to slot veterans into the schedule. The table below also shows days that are scheduled and clicking on a specific day will take you to the “Daily Docket.

### Mocks
![minimal download schedule assign button](https://user-images.githubusercontent.com/23316107/45374958-9fda4e80-b5c1-11e8-9472-68fb86ebfbac.png)

### Related Issues
#6597 Epic 1 Table View

**Comment by oscarAtNava** [comment]
Completed with 5954.
