### ISSUE TITLE
Co Release | Epic 2  Case Details - Actions | Assign Hearing 

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#6926]
As a central office hearing coordinator, I need to be able to assign a veteran to hearing day and location to the overall schedule in a user friendly way. 

#### Central Office
- [ ] Verify that when the user selects Assign Hearings the following options are present 
   - Hearing location: Should always be Washington D.C. (do not include a change option)
   - Date: Defaults to the date that was selected in the Assign Table - include a change option
   - Time: radio buttons with either 9:00 am or 1:00 pm
- [ ] Verify that when the user clicks assign a confirmation banner comes up with the following: 
   - Title: You have successfully assigned [Veteran Name] to [Date] 
   - Body: To view or make changes please click the "View hearing schedule" link below
- [ ] Verify that clicking on that view hearing schedule takes them to the schedule page

#### Video 
- [ ] Verify that when the user selects Assign Hearings the following options are present 
   - Hearing location: Defaults to the RO selected in the Assign Table with a change option
   - Date: Defaults to the date that was selected in the Assign Table - include a change option
   - Time: radio buttons with either 8:00 am or 12:00 pm
[ ] Verify that when the user clicks assign a confirmation banner comes up with the following: 
   - Title: You have successfully assigned [Veteran Name] to [Date] 
   - Body: To view or make changes please click the "View hearing schedule" link below
- [ ] Verify that clicking on that view hearing schedule takes them to the schedule view

### Change logic for Video Hearings 
- [ ] Verify that if the user changes the RO, then the date automatically turns into a drop down
   - The dropdown should now include the non- availability days for the newly selected RO 
- [ ] Verify that if the user keeps the RO and clicks change next to the date, it shows them the save non-availability as the ones in the Assign Tables date selector

### Mocks 
**Central Office**
![assign hearing co selected default](https://user-images.githubusercontent.com/23316107/45436955-f27b3f80-b681-11e8-9d68-64f5d5122c73.png)

**Central Office Change Date**
![assign hearing co change date](https://user-images.githubusercontent.com/23316107/45437263-7c2b0d00-b682-11e8-9d4a-c29beea04a67.png)

**Confirmation (True for Video and CO)
![ticket slotting dropdown confirmation](https://user-images.githubusercontent.com/23316107/45437499-e6dc4880-b682-11e8-9de1-58ed7ac79f4f.png)

### Open questions
- [ ] Where should the user be sent after the hearing is confirmed to be schedule
  - If we take them to the schedule, they have to search for that day
   - If we take them to the hearing docket, they have to have a way to quickly go to the assign hearing page
    - We can show no link until resolved

**Comment by laurjpeterson** [comment]
@Chingujo I think this one is done too! Feel free to close if so

**Comment by jimruggiero** [comment]
@nicholer @pshahVA Can you confirm if this work is already done? If not, can you update this epic with what work remains?

**Comment by nicholer** [comment]
Closing - this work was completed.
