### ISSUE TITLE
Video and CO Release | Epic 2  Case Details - Assign Hearing

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#7072]
As a hearing coordinator, I need to be able to assign a hearing to a specific slot in the schedule. 

### Acceptance Criteria
- [ ] Verify that when a user clicks the Assign Hearings in the action drop down the following populates for central office: 
   - Hearing location: Washington D.C. Change
       - If the user change it shows the dropdown of RO's. If selected, it will automatically turn the date
         field into a dropdown matching that RO's non availability days
   - Date: Defaults to the one selected in the table and a link text for change 
       - Clicking change renders a dropdown that shows exactly the same availability as the dates on the table 
        - The dates are in the following format: Day Date (2 open slots)
    - Time: 9:00 am or 1:00 pm options
- [ ] Verify the same exact behavior for Video hearings with the following exceptions: 
    - Hearing Location: Defaults to the selected RO 
     - Time: 8:00 am and 12:00 pm
- [ ] Verify that there is a button called Assign and when clicked confirms the veteran into the schedule

**Comment by mdbenjam** [comment]
One pattern we've been using is to make the actions dropdown options open up either a modal or new page, instead of putting the options right in the task area of case details.
