### ISSUE TITLE
Video and CO Release | Epic Daily Docket | Default View

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#7073]
As a hearing coordinator, I need to able to see all the veterans that are scheduled for a hearing that day. 

### Acceptance Criteria
- [x] Verify that the title is Daily Docket ( Day Date)
- [x] Verify that underneath the title there is a "back to schedule" link underneath the title
- [x] Verify that in the far right we have the following fields: 
 - VLJ: (not in hearing prep)
 - Coordinator: ( not in hearing prep) 
-  Hearing Type (in hearing prep)
  - This is a newer field in VACOLS that Jed added
- [x] Verify that we are using the Hearing Prep docket table with the following modifications to the date
   - Remove the check boxes next to the number
   - The Actions tab has the following: 
     - Hearing location (with a change link at the bottom) 
     - Hearing Day as a dropdown 
     - Disposition as a Drop down

### Mocks
**Video Default**
![daily docket default](https://user-images.githubusercontent.com/23316107/45948874-b623d980-bfc7-11e8-8131-9687c34eeb71.png)

#Related Issues
#6873 Epic Daily Docket
