### ISSUE TITLE
Video and CO Release | Epic Daily Docket | Editing and Dispositions

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#7075]
As a hearing coordinator, I want to be able to edit the hearing location, date, and disposition of a Veterans slot to account for re-schedules. 

### Acceptance Criteria
- [ ] Verify the user can change the "RO" 
   - If the user changes the RO, then the Date changes to the match that non availability for the RO
    - Verify this is a searchable dropdown 
   - The save button appears
   - Before the user can Save they must select a a new hearing day and disposition 
- [ ] Verify the user can just change the date
    - The dates for that RO matches that non availability and they must select a disposition for changing 
- [ ] Verify that the disposition matches the one in VACOLS except the P thing

### Mocks
**Default view**
![daily docket 1](https://user-images.githubusercontent.com/23316107/45831641-eae51780-bccd-11e8-9351-24f3bd4ee4e4.png)

**Save**
![daily docket 1_video save](https://user-images.githubusercontent.com/23316107/45948798-70671100-bfc7-11e8-8896-3779d532b7ce.png)

**RO Change**
_Regardless of what is changed - RO, date, or time, they need to select a disposition and put in notes why_

![daily docket 2](https://user-images.githubusercontent.com/23316107/45949148-d56f3680-bfc8-11e8-9026-3767e5d40d60.png)

### Related issues
#6873 Daily Docket Epic
