### ISSUE TITLE
Video and CO Hearing | Epic Daily Docket | Confirmation

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#7076]
As a hearing coordinator, I need to be able to acknowledge that changes to the daily docket were made successfully. 

### Acceptance Criteria
- [ ] When a user changes the day of a Veteran 
 - Title: You have successfully changed [Veteran's Name] hearing date to [Date]
 - Body: To view or edit your recent changes you can use the “View hearing day" link below. You can also view a history of your changes at the bottom of thed daily docket. 

- [ ] When a user changes the RO and Day
- Title: You have successfully changed [Veteran's Name]'s hearing to [Regional office] on [date]
- Body: To view or edit your recent changes you can use the “View hearing day" link below. You can also view a history of your changes at the bottom of thed daily docket. 

- [ ] Verify that "finalized and confirmed" changes show under a "Previously Scheduled" section at the bottom of the Daily Docket. 
 - The requirement is that we need a way too store changed and revisions

### Mock 
![daily docket confirmation](https://user-images.githubusercontent.com/23316107/45949830-516a7e00-bfcb-11e8-88cd-2544ff69da71.png)

### Related Issues
#6873 Video and CO Epic Daily Docket
