### ISSUE TITLE
CO and Video Release | Epic Table | RO has no up and coming hearing days

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#7332]
As a hearing coordinator, I need to know when an RO has no up and coming hearing days so I don't schedule one on accident or can resolve as necessary. 

### Acceptance Criteria 
- [ ] Verify that there is an error message for when an RO. has no up and coming hearing days but available slots. 
- [ ] Verify that the date selector on the right and the tabs are disabled
- [ ] Verify that there is a gray box in the table section (see mock)
- [ ] Verify the following body error copy appears 
    - Title: The [ Name ] Regional Office has no up and coming hearing days
  - Body: Please verify that this hearing has up and coming hearing days in the current schedule

### Mocks
![error messaging v](https://user-images.githubusercontent.com/23316107/46751994-1bdfb900-cc8a-11e8-8df7-4199eca5b361.png)
