### ISSUE TITLE
CO Release | Epic - daily docket | Postponement logic

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#7485]
As a hearing coordinator, I can only edit the hearing location and date when the disposition is a postponement. When I change the hearing date/location, it should automatically select postponement as a disposition so I don't make a mistake and risk the appeal getting lost. 

### Acceptance Criteria 
- [x] Verify that the disposition select is now the first choice a user has
- [x] Verify that the default is Select disposition
- [x] Verify that the hearing location and date are non editable in the default
- [ ] Verify that when the disposition is selected it comes in the following order:
    - Clear disposition (when a user wants to go back to no disposition before saving)
    - HZ line
    - Held
   - Postponement
   - No show
   - Cancellation
- [x] Verify that the hearing location and date turns changebale dropdowns ONLY when posponement is selected
### Mocks

_Default state_
![screen shot 2018-10-22 at 12 43 13 pm](https://user-images.githubusercontent.com/23316107/47305628-11151480-d5f8-11e8-971e-b26fc26e87cd.png)

_Disposition Drop down selected_
![screen shot 2018-10-22 at 12 46 24 pm](https://user-images.githubusercontent.com/23316107/47305755-808b0400-d5f8-11e8-8579-c31a69fb086b.png)

_All non postponement
![screen shot 2018-10-22 at 12 45 14 pm](https://user-images.githubusercontent.com/23316107/47305712-59343700-d5f8-11e8-8cde-dd9ca4b7a250.png)
 disposition_

_When postponement hearing location/date becomes editable_
![screen shot 2018-10-22 at 12 45 45 pm](https://user-images.githubusercontent.com/23316107/47305729-694c1680-d5f8-11e8-82e4-2cc9abb2157b.png)

**Comment by MeredithStewart** [comment]
@Chingujo -- If there's no hard lock, can they proceed in the UI with selecting a new location/new hearing day and cancel?

**Comment by MeredithStewart** [comment]
![disposition for daily docket](https://user-images.githubusercontent.com/36775274/47368961-aa076680-d6b0-11e8-82a1-8408da0fd397.jpg)
