### ISSUE TITLE
Privacy/FOIA rollout

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#7635]
## Functionality in scope
- ~~FOIA~~ Privacy team queue
   - New, Assigned, Completed
- Privacy individuals have an individual queue
  - Tabs
  - Table
  - Case details

## Proposed scope
1. Co-located can send FOIA tasks to FOIA queue - legacy and AMA
1. Mail team can send FOIA mail tasks to FOIA queue - AMA

## To do
- [x] Add FOIA organization row
- [x] Meet with Meg Peak, match people to FOIA organization - 11/8
- [x] Demo org queues to Meg Peak and team - Planning for 11/20 at 1100hrs.
- [x] Email Heather Gogola with a "no earlier than" date - MD
- [x] Deciding users, making sure they have access to Reader - Planning on Meg, Jessie and LaToya. MD waiting on names to submit them for Reader access as of 11/9. 
- [x] Deck for training - MD
- [x] Conducting training - MD and Will
- [x] Change routing logic for legacy Privacy/FOIA tasks to go to the Privacy queue from co-located
- [x] Introduce routing logic for AMA Privacy tasks to go to the Privacy queue from co-located
---
- [ ] Roll out to entire Privacy Team
  - [ ] This will need to be preceded by: 
    - [ ] Get the go-ahead from Privacy Team leadership and give Heather a heads up.
    - [ ] Refresher training to Privacy Team

**Comment by marvokdolor-gov** [comment]
## Notes from 11/8 Meeting
**Attendees:** Meg Peak, Jessie Retan, Heather Gogola, LP, MD, Will

Notes will also be incorporated into [Privacy/FOIA MURAL](https://app.mural.co/t/workqueue2001/m/workqueue2001/1504901325346/e588275d39e19a7a57bb7ad5d86dbbfc6e01eabe)

### Current Work Flow
- FOIA Mail Task
- No cases are assigned to Meg; they're put into abeyance.
    - Meg deletes the Mail Tab and enters it into FOIA Express.
- FOIA does not stop adjudication but Privacy Act does
- Meg, Jessie, and a new person (to be named) makes this distinction between Board work (VACOLS/Caseflow) in FOIA Express.
- Meg and Jessie do **not** currently have Reader access (captured in To do list above).
- They have 20 days to work both FOIA and Privacy
- Once they have completed their task they grant an extension to allow the requesting party time to review the documents
- [ ] Meg suggests checking with management re: Automatic letter that grants this extension
- VACOLS has a buttons to [generate letter] and you choose the letter you need
    - before VACOLS had this functionality used to reuse saved Word docs
    - this [generate letter] functionality is future functionality either in Caseflow or elsewhere
- Request: could colocated have a pop-up regarding whether or not an extension is also requested? Key is to ensure Privacy team only gets Extension Requests related to Privacy/FOIA.
- Privacy is Meg, Jessie, detailee, + 5 staff + 1 new staff
- Number of Privacy tasks per week: 100-200
- They use eFolder Express for almost all of these
- The entire team has access to eFolder Express
- Concern about reports re: what was done

### Goal: Pilot with a small group
- only tasks coming in from Colocated to start: Meg, Jessie, LaToya
- then when we add mail, rollout to entire Privacy team
- [ ] We will be monitoring how many tasks come from colocated
- in the meantime we're going to be developing a few more things; confirm some VACOLSy things e.g. is it ok to replicate what we're done with colocated in terms of using a "Caseflow" location
- Best day for training is Tuesdays - so we've picked 11/20 (captured above) to train the entire team

**Comment by marvokdolor-gov** [comment]
Good morning @lowellrex!

There are a couple of engineering tasks above that I wanted to ask you about please?

- [ ] Change routing logic for legacy Privacy/FOIA tasks to go to the Privacy queue from co-located
- [ ] Introduce routing logic for AMA Privacy tasks to go to the Privacy queue from co-located

Should I pull these out into separate tickets, or are they already part of you team's plans for this sprint?

**Comment by marvokdolor-gov** [comment]
## Notes from Privacy Team Caseflow Training
Deck:
[DS Privacy staff training - November 2018.pptx](https://github.com/department-of-veterans-affairs/caseflow/files/2605420/DS.Privacy.staff.training.-.November.2018.pptx)

- [ ] Privacy Team need to be able to indicate whether a task in Privacy or FOIA (FOIA tasks are managed in a different system FOIA Express)
- Would like to have the age count in list view of Reader
- [ ] **Change `FOIA` to `Privacy` everywhere**
- [ ] They'd like to be able to send cases back to the Attorney since that's all the VLJ Support Staff would have done themselves
- [ ] Will Caseflow allow search for socials **and** claim numbers? yes
- [ ] Can they see LCM (Legacy Case Management?) documents in Reader?

**Comment by lowellrex** [comment]
> Would like to have the age count in list view of Reader
What is "age count"?

**Comment by laurjpeterson** [comment]
> Can they see LCM (Legacy Case Management?) documents in Reader?
Yes

> Privacy Team need to be able to indicate whether a task in Privacy or FOIA (FOIA tasks are managed in a different system FOIA Express)
- How about we map out some of the options here. If they want all tasks to be called "Privacy", this might require the Privacy team to "edit" the task name to better clarify what the task is. 
- Can we follow up with them on if these are still their desired task types? There are a few - `FOIA Request, `FOIA Request & Other Actions` `Privacy complaint`, and `Privacy act request`.

**Comment by marvokdolor-gov** [comment]
Sorry about that, Lowell - that should be “page”. I’ve corrected it above. 

Thanks LP, for the suggestions and will do!

**Comment by laurjpeterson** [comment]
I think we've gotten this request for Reader before - page count vs. document count - because some documents in VBMS have quite a few pages within them that are only counted as one document. I don't think we have the ability to do this, but it could be a question for Mark.

**Comment by marvokdolor-gov** [comment]
Sound about right. I’ll do a search and check in with Mark.

**Comment by marvokdolor-gov** [comment]
### Message from Marvo to Meg Peak and Jessie Retan (Privacy Team Lead and Manager respectively) 11/29/2018

> Hi Meg and Jessie,
>  
> Thank you both for your time this morning to chat through some of the details of your team starting to use Caseflow. Three key things we agreed on:
> 1. Both Legacy and RAMP Appeals Privacy Tasks will be worked in Caseflow starting with Meg, Jessie, and LaToya.
>     a. We’ll touch base on a weekly basis to ensure the work load is manageable.
>     b. You’ll let me know when you’d like to have the full Privacy Team using Caseflow.
>     c. You’ll also let me know if your Team would like refresher training and we’ll get that scheduled as quickly as possible.
> 2. The Notes field in Caseflow will be used to capture Task Actions. The photo below is a screenshot of what these look like in the VACOLS dropdown you use today:
> ![image from ios 2](https://user-images.githubusercontent.com/31679660/49236529-4b798a80-f3ca-11e8-9e54-fc014ea49722.jpg)
> 
> 3. I’ll work with you every week to get an adequate productivity report prepared.

**Comment by marvokdolor-gov** [comment]
### Notes from dropping by Jessie's desk 11/30/2018

- Privacy Team labels things as `BVA-General` in VBMS `Document Category - Type:` and this shows up as `other` in Caseflow Reader column `Document Type`
- Request: would like Subject to show up in Reader (edited)
    - [ ] Marvo: see if this a feature request captured elsewhere.
- VBMS Request: would like to be able to have a FOIA/Privacy Response (rather than Request which is the only thing available) in the `Document Category - Type:` dropdown. This should go to Shawn for now.
    - Interim work around would be to use the Subject field
    - [ ] Related request: Show VBMS `subject` in Caseflow Reader

- [ ] Q: lag time between upload to VBMS to showing up in Reader. A business day at most.
- [ ] Q: timing to get Caseflow Queue functionality to Privacy team. Interim answer 2 weeks from now i.e. 12/14.
- [ ] Q: timing for Teams to be able to assign to other teams specificallyPrivacy assigned to  VLJ Support or an Attorney

**Comment by laurjpeterson** [comment]
Re: the above request - Reader does show and allow users to edit the VBMS `Subject line` - do you think this is what they are talking about?

Re: lag time between upload to VBMS and showing up in Reader. I don't think there is a lag btw VBMS and Reader, but there is a lag btw upload in Mail Portal to VBMS. Reader and VBMS should be instantaneous

Re: timing - agree. After this sprint!

Re: timing to assign to other teams - is this like assigning completed tasks back to VLJ support? That should be possible with this first pilot release for them. I'd be curious to know how often they are assigning cases to attorneys today - I didn't hear about them doing that in our research.

**Comment by marvokdolor-gov** [comment]
Thanks LP! My thoughts and next steps:
- Reader request: I will check in with Jessie on Reader - the screen he had up when we spoke did not have a Subject line column
- Lag time: Updated the notes above. Holtz mentioned ~3hr lag time.
- Timing: cool
- Timing to assign to other teams: got it re: VLJ Support; on Attorneys - will check with Jessie to understand what they do today.

**Comment by marvokdolor-gov** [comment]
Update:
- The screen definitely does not show the Subject Line. LP, I'll sit with you to try to figure this out.
- Privacy does not directly send things to attorneys now, so we'll cross that bridge at a later time.

**Comment by marvokdolor-gov** [comment]
## Touching Base with Privacy Pilot users - LaToya and Jessie Week of 01/14/2019
- LaToya indicated that Caseflow is working well for her. She said the same thing last week. So looks like we're doing well there.
- Jessie continues to have concerns about the lack of useful information on Privacy/FOIA Requests coming from **some** VLJ Support Staff. This is not a Caseflow issue per se.
- Jessie also previously expressed concern that when Privacy Team members complete a task it goes directly back to the VLJ Support Staff person it came from and not back to Jessie. He indicated today, 01/17/2019 that this was in fact alright and he had no problems with this mode of working.
