### ISSUE TITLE
Display all AMA appeals for which VSO is the representative in queue

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#7905]
VSOs currently only see cases in their standard queue tables (they see everything in search) if there has been a task assigned to that VSO (to prepare an informal hearing presentation) that is attached to that case. VSOs want to be able to view all cases for which they are the assigned representative in Caseflow, even if there are no tasks to be completed by the VSO associated with that case.

Discussion 12/17:
- Use a `TrackVeteranTask`

## Acceptance criteria:
* Display all AMA appeals for which VSO is the representative in queue
* Exclude `TrackVeteranTask` from Case Timeline and Task Snapshot

## Rollout plan
* [x] Enable hiding of tasks from Case Timeline/Task Snapshot (#9018)
* [x] Create `TrackVeteranTask` when creating RootTasks for appeals represented by VSOs (#9062)
* [x] Show all tracking tasks for VSO in the new "All cases" tab (#9115)
* [x] Close `TrackVeteranTask` when a decision is dispatched (#9173)
* [x] Create job to update `TrackVeteranTask` nightly when representation changes in BGS (#9190)
* [x] Run this job nightly! (https://github.com/department-of-veterans-affairs/appeals-deployment/pull/1991)

![image](https://user-images.githubusercontent.com/32683958/48709455-84984a80-ebd3-11e8-8be3-da38f5251198.png)

## Blocks:
* Add a job that cancels/creates new `TrackVeteranTask`s when the VSO changes (#7784, #8336)

**Comment by joeyyang** [comment]
@laurjpeterson — clarifying question on this task: how will we know when we need to create an Informal Hearing Presentation task? Our current thought is to create an IHP task if there are no hearings and the VSO is an IHP-writing VSO. Is this correct?

Also, how do we know if a VSO is not an IHP-writing VSO?

**Comment by laurjpeterson** [comment]
- Create IHP tasks for all IHP-writing VSOs if the case is an Evidence Submission docket or Direct Review docket case.
   - one exception: For appeals with Paralyzed Veterans of America (PVA) as the VSO, always create an IHP task.

- Right now, this is just a list of VSOs. Most of these are "national" rather than regional or state-based, like Texas Department of Veterans Affairs.

1. Armed Forces Services Corporation, Room 2W.240J
2. American Legion (AL), Room 2E.102B
3. American Red Cross (ARC), Room 2W.240K
4. American Veterans (AMVETS), Room 2W.240G
5. Blinded Veterans Association (BVA), Room 2W.240M
6. Disabled American Veterans (DAV), Room 2E.250J
7. Fleet Reserve Association (FRA), Room 2W.240C
8. Marine Corps League (MCL), Room 2W.240I
9. Maryland Department of Veterans Affairs (MDVA)
10. Military Order of the Purple Heart (MOPH), Room 2W.240P
11. National Veterans Legal Services Program, Inc. (NVLSP), Room 2W.240H
12. Paralyzed Veterans of America (PVA), Room 2W.210C
13. Veterans of Foreign Wars (VFW), Room 2E.450K
14. **Vietnam Veterans of America (VVA), Room 2W.220F
15. Wounded Warrior Project (WWP), Room 2W.240S – VSO-Flexi Desk
16. NCOA (Non Commissioned Officers Association)

References:
- From Jed: department-of-veterans-affairs/dsva-vacols#33
- From VSO overview epic: https://github.com/department-of-veterans-affairs/caseflow/issues/5581#issuecomment-418748166

**Comment by laurjpeterson** [comment]
@MeredithStewart here's the gh issue about showing all VSO cases, for you to follow along if you'd like. See mock above.

**Comment by lowellrex** [comment]
Remaining work to be done - SMALL
