### ISSUE TITLE
Milestone Geo-matching| Schedule roll up 

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#8020]
As a hearing coordinator and administrator, I want to see the hearing locations tied to a Regional office in a filtered view to see the associated locations before entering the daily docket. 

### Acceptance Criteria 
- [ ] Verify that there is a carrot next to the regional office that when clicked expands and sees the hearing locations tied to that date
- [ ] Verify that there is a title called hearing locations
- [ ] Verify that the hearing location is displayed:
Hearling location name (Type of location)
 - Type of location is: Vet center, VHA,  VBA

**Comment by Chingujo** [comment]
We are no longer doing this feature for this milestone will create a back log ticket
