### ISSUE TITLE
EPIC | Create training and reference materials for Caseflow Intake

### ISSUE THREAD

**Issue by steve-gov** [department-of-veterans-affairs/caseflow#8185]
This story collects tasks necessary to create training and reference materials for Caseflow Intake.

### v1

- [x] Get points of contact for each user group 
  - [x] Conduct simple research to figure out what kind of training would help them the most
- [x] Decide on a technical solution for general knowledge base/ workflow repo ([issue](https://github.com/department-of-veterans-affairs/appeals-design-research/issues/1088))
- [x] Create draft of major workflows for compensation appeals in the knowledge base (#8186)
- [x] Create draft of major workflows for non-compensation appeals in the knowledge base (#8187)
- [x] Review existing training reference guide in the [training repo](https://github.com/department-of-veterans-affairs/appeals-training/tree/master/Intake)
  - [x] Annotate the training materials with new features in the knowledge base, and pass along to Will so he can update the reference guides
- [x] Conduct user research on whether training materials outside of KB and ref guide are necessary (videos? inline feature tooltips?)

### v2

- [x] Create draft of edge case workflows for compensation appeals in the knowledge base
- [x] Create draft of edge case workflows for non-compensation appeals in the knowledge base

## User Groups

Non-compensation ([flows here](https://app.mural.co/t/workqueue2001/m/workqueue2001/1538364691019/29e2e4cfa7cc8decb1d2f32df7de1796b0f53987)):

- LGY (https://github.com/department-of-veterans-affairs/appeals-design-research/issues/1046)
- Pension (https://github.com/department-of-veterans-affairs/appeals-design-research/issues/1032)
- Insurance (https://github.com/department-of-veterans-affairs/appeals-design-research/issues/1052)
- Fiduciary (https://github.com/department-of-veterans-affairs/appeals-design-research/issues/1053)
- Vocational Rehab & Employment (https://github.com/department-of-veterans-affairs/appeals-design-research/issues/1054)
- VHA

Compensation: 

- Compensation VSRs, R-VSRs
- Compensation intake staff (Claims assistants) [Here is a mural with all the notes from the User Feedback Session on 11/15/2018](https://app.mural.co/t/workqueue2001/m/workqueue2001/1542659894037/dc8037bf39d3216a729769437bb68fbf90f33d88)
