### ISSUE TITLE
EPIC | Caseflow Data Model and Reporting

### ISSUE THREAD

**Issue by marvokdolor-gov** [department-of-veterans-affairs/caseflow#8207]
# Goals
- [ ] Create a robust way for the Board to access Caseflow data that doesn't break when we change the application.
- [x] Develop reports the Board needs in the near term to allow them to function effectively
- [x] Document the Caseflow Data Model so others can develop the understanding they need to build self-service reporting functionality in Tableau

# In Progress
-  [ ] Create Extract Transform Load [ETL] layer to allow Board Tableau instance to access Caseflow data in a reliable way.

# Completed
- [x] Get Tableau Desktop installed - Nemo, Teja
- [x] Support "Log in to Tableau" from Caseflow - Nemo #9183 
- [x] MVP Data Dictionary - Teja #8501. 
- [x] Request from foxtrot re: Feedback - Nemo #8893
- [x] Decision Hierarchy - Nemo #8815
- [x] Change `Appeal Task Type` to `Appeal` - Teja #8914: Closed.

#### Reports on RAMP Appeals requested by Rachel for Congress 
(_These are separate from AMA Section 5 Reports provided by VBA PA&I_)

- [x] [Decisions dispatched](https://caseflow-looker.va.gov/looks/66); also being wrangled by LP and Holtz
- [x] [Issues dispatched](https://caseflow-looker.va.gov/looks/89)
- [x] [Grant, Denial and Remand totals by issue](https://caseflow-looker.va.gov/looks/87)
- [x] [Remand reasons](https://caseflow-looker.va.gov/looks/86)
- [x] [Disposition breakdown by previous adjudication (Supplemental Claim or HLR)](https://caseflow-looker.va.gov/looks/99)

### Attorney & Judge productivity for AMA cases
[Productivity Dashboard](https://caseflow-looker.va.gov/dashboards/20)

- [x] Completed tasks by judges and attorneys 
- [x] Progress on appeals and decisions
- [x] Decisions signed by judges
- [x] Decisions drafted by attorneys
- [x] Total number of decisions
- [x] Total number of decision issues
- [x] Total number of request issues
- [x] Tasks completed by users in privacy branch and BVA dispatch.

### Case Distribution

- Looker Dashboard for Case Distribution:
  - [x] [Time to distribute a new priority case for Case Distribution](https://caseflow-looker.va.gov/looks/122)
  - [x] [Percentage of priority cases for Case Distribution](https://caseflow-looker.va.gov/looks/116)
  - [x] [Priority case inventory for Case distribution](https://caseflow-looker.va.gov/looks/123)

- _Background_: [original request](https://github.com/department-of-veterans-affairs/caseflow/issues/7838#issuecomment-438464714).

### VACOLS DAS reports
- [x] Marvo: Check if these reports are on the [list of Reports](https://github.com/department-of-veterans-affairs/appeals-design-research/issues/989#issuecomment-449102430) to be compiled by B3. 
**Update**: I checked and they are. A few of the reports no longer apply e.g. related to Attorney by Chief Group; the new version would be Attorney by Supervisory Senior Counsel, but B3 will cross that bridge when they get to it.
- Decision assignment sheet
- Records in the database and applet
- _Background_: #7809 DAS Deprecation

# Background
[Outline of Board Reporting Needs](https://github.com/department-of-veterans-affairs/appeals-design-research/issues/989)
[Caseflow Reporting Projects](https://github.com/department-of-veterans-affairs/appeals-design-research/issues/757)
More in #appeals-xray Slack Channel

**Comment by marvokdolor-gov** [comment]
## Chat with Rachel about reports listed above
- we want to make sure the format is what Rachel wants
- request to Rachel to review and provide feedback
