### ISSUE TITLE
Shepherd appeals from intake to auto-case distribution

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#8338]
### Creating IHP, evidence submission, and hearing tasks
 - [X] Create IHP and evidence submission window tasks on intake for direct docket and evidence submission appeals https://github.com/department-of-veterans-affairs/caseflow/issues/8334 https://github.com/department-of-veterans-affairs/caseflow/issues/7916
 - [X] Create task timing functionality days and make evidence submission tasks expire in 90 days https://github.com/department-of-veterans-affairs/caseflow/issues/8684
  - [X] Create `ready` scope, usable by auto-case distribution, that can find all appeals that are ready for distribution 
- [x] Track when an appeal became ready for distribution
 - [x] Create `ScheduleHearing` tasks, `HoldHearing` tasks, and `TranscribeHearing` tasks (@sharonwarner to coordinate completion)
 - [x] Ensure hearing tasks expire as necessary, ensure they are returned by the ready scope (@sharonwarner to coordinate completion)

### Blocking distribution of appeals with open mail tasks
- [X] When a mail task for an undistributed appeal is created, we should potentially create it as a child of the Distribution task, thus ensuring that a distribution will not happen if there is an open mail task 

### Handling POA changes
We will check POA and create IHP tasks as late as possible:
 - [X] for direct review appeals, we check POA and create necessary IHP tasks that block distribution when the appeal is intook
 - [X] for evidence submission appeals, we check POA and create necessary IHP tasks after the evidence submission window ends or is waived (so if POA changes during that window, we'll handle it correctly
- [x] for hearing appeals, check POA and create necessary IHP tasks (at least for PVA, which is apparently the only IHP-writing VSO for hearing appeals) **after** the hearing is held and evidence is submitted
 ^ The above tasks will ensure that we correctly handle a POA change before the IHP period starts. However, if POA changes after the IHP period would have started, we don't currently have a solution.
- [x] handle the case when POA changes *after* the IHP period starts 

### Supporting waiving of evidence submission period
- [ ] complete the evidence submission task early, opening up the appeal for IHP writing or distribution before the period is over
- [ ] ensure we can track any necessary side information about the waiver

### Supporting waiving of hearing
- [x] When the hearing appeal is ready to be scheduled, check if the hearing is withdrawn. If it is, don't create further hearing tasks and mark appeal as ready for distribution

### Resilience and error handling
- [x] Ensure that the TaskTimer job can handle failure of each individual task timer https://github.com/department-of-veterans-affairs/caseflow/issues/8755

### Mail
- [x] If mail comes in pre-distribution, ensure that mail blocks distribution

### Unconfirmed
-[ ] Create past due IHP task to ensure VSOs can write an IHP even after the period expires

Research here: https://github.com/department-of-veterans-affairs/caseflow/issues/8288

**Comment by laurjpeterson** [comment]
Should we add this ticket - creating 90-day evidence window tasks at Intake - to this list? https://github.com/department-of-veterans-affairs/caseflow/issues/7916

**Comment by amprokop** [comment]
Yes, your ticket is much better written than mine — sorry for not finding it!

**Comment by laurjpeterson** [comment]
Privacy/FOIA tasks should block distribution. So, if a case has open `FOIA Request`, `Privacy act request`, `Privacy complaints`, or `FOIA request & other actions` mail tasks or open `FOIA` admin action that was sent to Privacy team through VLJ support (co-located admin), it should not be distributed.

**Comment by laurjpeterson** [comment]
Privacy/FOIA tasks should block distribution. 

So, if a case has open `FOIA Request`, `Privacy act request`, `Privacy complaints`, or `FOIA request & other actions` mail tasks or open `FOIA` admin action that was sent to Privacy team through VLJ support (co-located admin), it should not be distributed.

Does this comment belong on this ticket or another one?

**Comment by laurjpeterson** [comment]
@sharonwarner @MeredithStewart can you add some more information around AMA hearing tasks? the last we talked, we discussed a `ScheduleHearing` task, a `HoldHearing` task, and a `TranscribeHearing` task. (@amprokop - We should not distribute cases to judges without the hearing being transcribed.)

Could you also share the list of Hearing Branch admin actions here, and let us know if any of them should block distribution to a judge? I know most of the admin actions are blocking ScheduleHearing, but asking just in case.

**Comment by laurjpeterson** [comment]
the one last step here is #10023. since we're tracking that work there, closing this ticket now
