### ISSUE TITLE
queue design checklist

### ISSUE THREAD

**Issue by sneha-pai** [department-of-veterans-affairs/caseflow#8352]
#### Team categories:

**Queue focus areas**
- task tree ( back-end mostly)
- single appeals views (case details, timeline)
- collection of appeals ( queue tables, search tables)
- pilots (when something has launched, features that come out of user-feedback)

**Decision focus areas**
- checkout flows
- issues
- outcoding/EP creation

#### Queue Tables
- [x] #8277 Remove Pending Action Tab
- [ ] #5565 Identify and mark cases as specialty case teams (SCT) in queue tables + case details
- [ ] #6014 Allow attorneys to view multiple admin actions in their table

#### Case Search
- [x] #8098 Add higher level reviews and supplemental claims to search results & case details

#### Case Details
- [ ] #8199 Universal Case Title (additional elements)
- [ ] #8141 Active tasks component
- [ ] #8040 Add "This is a paper case" to Case details

#### Flows/Sequences
- [ ] #7404 Create generic tasks / mail rollout 

----- 
#### Queue Tables
- [ ] #6369 Improve appearance of case table headers
- [ ] #8241 Add user column to team queue
- [ ] #8242 Introduce pagination to Queue

#### Case Details
- [ ] #7126 Change task type

------ 
### upcoming Queue initiatives (not yet started)

- [ ] #7548 Allow judges to sent RAMP/AMA appeals back to attorneys
- [ ] #8170 Create easy way for team admins to navigate to team user management page
- [ ] #5448 Scaling judge screens for senior counsel and chief judges 
- [ ] #7929 Add positive feedback to Attorney Evaluation Screen
- [ ] #6364 Open question: what happens to assigned cases when a BVA employee leaves their position?
- [ ] #7894 Desired queue enhancements
- [ ] #5597 Show overtime cases

**Comment by carodew** [comment]
@laurjpeterson I'm going through the design backlog to try to make sense of what's in there. What's the context on this one? It seems like an epic but also not an epic.

**Comment by laurjpeterson** [comment]
I think this was Sneha's way of capturing design work at this point of time in December. Since all of the bullet points have associated tickets that could be moved to the appropriate design pipeline, I think we could close this one.
