### ISSUE TITLE
Configurations in queue

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#8423]
## Background
We anticipate BVA teams and users benefiting from different behaviors and views for cases in their queue. Examples:
- [x] Hearing Management Branch needs a regional office column

- [ ]  Some other branches might want to add a user column to know who is assigned a task on their team

- [ ]  Some users within a team should work only certain types of tasks

## Assumptions
Individuals on different BVA teams want to view different information about an appeal (note: different than the hypothesis made during initial queue discovery)

## Requirements
As a Caseflow user, I want to configure my queue views to show me Veteran, case, and task data most important to my work, so I can complete my tasks in the most efficient way, and am satisfied with my user experience of Caseflow. 

* Navigation from `/queue` views to a configurations view, and back again
* Individual configurations screen that allows users to turn columns on and off for themselves
	* Note:  judges likely need to do this for their Review view and their Assign view
* Team configurations screen that allows users to turn columns on and off 

Other ideas:
* configure how cases are assigned from team to individuals (i.e. auto-assignment)
* view mail routing rules - which mail tasks go to which teams
* configure which users are admin users vs. non-admin
* define which users should receive which types of tasks
* business levers, like % case selection for Quality Review

## Open questions
* Should the team configurations page be the same as the team user management page? 
* Are there other attributes that a user might want to configure? Like tabs or Case Details information?

## Concerns
* Pages could start loading slower

**Comment by mdbenjam** [comment]
Note this PR adds an RO column for hearing schedule only. https://github.com/department-of-veterans-affairs/caseflow/pull/9071 We should remove the hackyness in that PR once we implement this ticket.

**Comment by lowellrex** [comment]
Another type of configuration we could add would be to add some visibility into the various actions available on a task's different states to a user. For example, something like the following table could be visible on the VLJ support staff team admin page (perhaps with the option to add rows or actions to cells further down the line):

### `ColocatedTask` actions:

Conditions | User is task assignee | User admin on assignee team | Count
--- | --- | --- | ---
Status: **in_progress**, Appeal type: **Legacy**, Action: **schedule_hearing** | `Send back to attorney`, `Send to Translation team`, `Place hold`, `Assign to Privacy team` | `Re-assign to person` | 87
Status: **on_hold**, Appeal type: **AMA**, Action: **translation** | `Send back to attorney`, `Place hold`, `Assign to Privacy team`, `Assign to Translation team` | `Re-assign to person` | 14

A first step in this direction to articulate the various actions available to a combination of user and task state could be created by a script of nested loops over all of these conditions and inspecting which actions are available in each condition.

**Comment by lowellrex** [comment]
Another configuration that would be nice to pull out of code and into somewhere we (or LRP?) could more easily manipulate it are the constants that are in the auto-case distribution code (examples [here](https://github.com/department-of-veterans-affairs/caseflow/blob/68c31a63721ccdec7a0a3f1347ada270f8524088/app/models/distribution.rb#L22) and [here](https://github.com/department-of-veterans-affairs/caseflow/blob/68c31a63721ccdec7a0a3f1347ada270f8524088/app/models/dockets/direct_review_docket.rb#L4)).

**Comment by araposo-tistatech** [comment]
Outdated request, closing, will open new ticket if this is requested again.
