### ISSUE TITLE
Congressional Inquiries

### ISSUE THREAD

**Issue by eric-nava** [department-of-veterans-affairs/caseflow#8524]
### Context 

A congressional inquiry is when a congressperson expresses interest in the status of a Veterans' appeal. If a Congressperson inquires about an appeal while it is being processed at the Board, BVA dispatch teams must notify them when that appeal is being dispatched.

Here's the general flow of how a congressional inquiry might happen:

1. Congresspeople can contact the board about the any appeal at the board via phone, email or formal correspondence (post/letter); if they are seeking to flag and appeal and track its status, the correspondence must be through email or post.

2. Mail team does any appropriate actions to migrate content into VACOLS.

____

## Task Creation

When a Congressional Inquiry comes in by mail/fax, mail employees need to create a mail task in Caseflow and assign it to the Lit Support Organization.

When a Congressional Inquiry comes in by mail/fax, email, or phone, mail employees or lit support employees need to log data about the Congressperson, including: 
- Name of Congressperson
- City of office(s) - could be multiple
- Address(es) of office(s) - could be multiple
- Source of request (mail, fax, phone, email)
(Note: Lit Support's preference is that this data is collected at the time of the task's creation.)

Lit support employees need to see the source of request (mail, fax, phone, email) because different team members work tasks from the different sources. 

### Task editing

If Mail team incorrectly labels/classifies the mail task, Lit Support needs the ability to edit the task type.

### Subsequent Task Creation

If another task needs to happen after Lit Support completes the Congressional Inquiry task, Lit Support needs to be able to create that task and assign it to the correct person.

- For example: if lit support notices that the Congressperson is also asking for a FOIA/Privacy Act Request, they need to create and assign that task

**Comment by eric-nava** [comment]
##Screens for production

- [ ] Mail team handling Congressional inquiry mail item
- [ ] Lit Support team lead receiving congressional inquiry
- [ ] TL assigning task to staff
- [ ] Staff receiving task
- [ ] Staff marking task as ready for dispatch

**Comment by eric-nava** [comment]
So first, the mail team needs to make a mail item in Caseflow. Below has a few proposed content items. 
<img width="729" alt="screen shot 2019-01-24 at 5 58 47 pm" src="https://user-images.githubusercontent.com/45407522/51714321-d493f300-2002-11e9-9e32-a73c914c3d0c.png">

The mail user selects Congressional Inquiry, which triggers a pre-populated instructions box.
<img width="730" alt="screen shot 2019-01-24 at 6 01 09 pm" src="https://user-images.githubusercontent.com/45407522/51714384-fd1bed00-2002-11e9-8326-9fb4f529c26e.png">

<img width="730" alt="screen shot 2019-01-24 at 6 01 37 pm" src="https://user-images.githubusercontent.com/45407522/51714423-25a3e700-2003-11e9-957b-3d54f25cd968.png">

**The Lit support user then sees some updates to the case detail page. Specifically a task in the case task snapshot, a Congressional Inquiry detail component, and an updated case timeline.**
<img width="730" alt="screen shot 2019-01-24 at 6 02 04 pm" src="https://user-images.githubusercontent.com/45407522/51714470-5257fe80-2003-11e9-8cd4-057fc699abb8.png">
..
<img width="730" alt="screen shot 2019-01-24 at 6 06 07 pm" src="https://user-images.githubusercontent.com/45407522/51714476-55eb8580-2003-11e9-95e8-91f917cacdae.png">

**Comment by eric-nava** [comment]
@lowellrex @laurjpeterson any update for development on this?
