### ISSUE TITLE
Appeals API | Appeal Status V3 Overview - Work Tracker

### ISSUE THREAD

**Issue by marvokdolor-gov** [department-of-veterans-affairs/caseflow#8685]
## Background Information/Useful Links
- Initial Appeal Status V3 ticket #7890 
- [Research Plan](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Appeals%20Status/V3/User_Research/Research_Plan.md) using VA.gov resources
- Appeal Status [documentation](https://github.com/department-of-veterans-affairs/vets.gov-team/tree/master/Products/Appeals%20Status) over on vets.gov-team repo
- [Video](https://www.facebook.com/DAV/videos/10160799755010387/) of CG talking about AMA to DAV
- [Waffle Board](https://waffle.io/department-of-veterans-affairs/caseflow?search=appeal%20status)

# VA.gov

_Note: links to individual tickets will be added as they are prepared._
[Ticket in private DS repo](https://github.com/department-of-veterans-affairs/digitalservice/issues/858).
- [x] [Create mock data](https://github.com/department-of-veterans-affairs/vets-api-mockdata/pull/65)
- [x] [Update vets-api to accept schema/enum changes](https://github.com/department-of-veterans-affairs/vets-api/pull/2770)
- [x] Updates to index page and H1s #8980
- [x] New docket section for AMA Appeals (AN)
- [x] Update content
    - [x] Docket #9322
    - [x] Events #9323
    - [x] Current Statuses/Next Events #9324
    - [x] Alerts #9325

# API

- [x] Update Swagger spec: https://app.swaggerhub.com/apis/dsva-appeals/appeals-status/2.1.0
- [x] Investigate distinguishing DTA errors/post-DTA EPs #8722  (MC)
- [x] Decide how to feature flag v3 stuff #8725  (MC)
- [x] Add in new models (Appeal, Higher-Level Review, Supplemental Claim). [Epic](https://github.com/department-of-veterans-affairs/caseflow/milestone/67).  (MC)
- [ ] Investigate issue descriptions (AN to start, post-MVP) #9416
- Related conversations to have by 01/18/2019:
  - [x] MC: Conversation with Rusty (mentioned [here](https://github.com/department-of-veterans-affairs/caseflow/issues/7890#issuecomment-451307749)). **Goal**: Extract information about tracked items.
  - [x] MC: Connect with Lowell on Task Events and Feature Flags 01/16/2019

### Attributes

- [x] Update `type` to "legacyAppeal" #8807

### Events

- [x] `statutoryOptIn` #8808

### Current Status

- [x] `statutoryOptIn` #8808

### Alerts

- [x] `amaOptInEligible` #8809
  - [x] `details`
    - [x] `dueDate`

### Attributes

- [x] `appealIds` #8830
- [x] `updated` #8831
- [x] `type` (always `"original"`)
- [x] `active` #8833
- [x] `incompleteHistory` (always `false`)
- [x] `aod` #8835
- [x] `location` #8836
- [x] `status` #8842
- [x] `events` #8996
- [x] `alerts`
- [x] `programArea` #8837
- [x] `aoj` #8838
- [x] `issues` #9160
  - [x] `active`
  - [x] `lastAction`
  - [x] `date`
  - [x] `description`
  - [x] `diagnosticCode`
- [x] `description` #9161
- [x] `docket` #8839
  - [x] `type`
  - [x] `month`
  - [x] `eligibleToSwitch`
  - [x] `switchDueDate`
- [ ] `docket` post-MVP #9418 
  - [ ] `allDocketsTotal`
  - [ ] `total`
  - [ ] `ahead`
  - [ ] `eta`

### Events

- [x] `amaNod`
- [ ] `docketChange`
- [x] `distributedToVlj`
- [ ] `hearingHeld`
- [ ] `hearingNoShow`
- [ ] `withdrawn` #9202
- [x] `bvaDecision`
- [x] `bvaDecisionEffectuation`
- [x] `dtaDecision`
- [x] `otherClose`

### Current Status

- [x] `pendingHearingScheduling`
  - [ ] `details` #9156
    - [ ] `type`
- [x] `scheduledHearing`
  - [x] `details` #9157
    - [x] `type`
    - [x] `date`
    - [x] `location`
- [x] `evidentiaryPeriod`
- [ ] `atVso`
  - [ ] `details` #9158
    - [ ] `vsoName`
- [x] `onDocket`
- [x] `decisionInProgress`
  - [x] `details` #9430 
    - [x] `decisionTimeliness`
- [x] `amaRemand`
  - [x] `details` #9162
    - [x] `issues`
- [x] `bvaDecision`
  - [x] `details` #9162
    - [x] `issues`
- [x] `postBvaDtaDecision`
  - [x] `details` #9163, #9162
    - [x] `bvaDecisionDate`
    - [x] `aojDecisionDate`
    - [x] `issues`
- [x] `bvaDecisionEffectuation`
  - [x] `details` #9163
    - [x] `bvaDecisionDate`
    - [x] `aojDecisionDate`
- [ ] `withdrawn` #9201
- [x] `otherClose`

### Alerts

- [x] `scheduledHearing` #9150
  - [x] `details`
    - [x] `type`
    - [x] `date`
- [ ] `hearingNoShow` #9151
  - [ ] `details`
    - [ ] `date`
    - [ ] `dueDate`
- [x] `evidentiaryPeriod` #9152
  - [x] `details`
    - [x] `dueDate`
- [x] `amaPostDecision` #8840
  - [x] `details`
    - [x] `availableOptions`
    - [x] `decisionDate`
    - [x] `dueDate`
    - [x] `cavcDueDate`

### Attributes

- [x] `appealIds` #8998 
- [x] `updated` #8831
- [x] `active` #8834
- [x] `incompleteHistory` (always `false`)
- [x] `location` (always `"aoj"`)
- [x] `status` #8843
- [x] `events` #8999
- [x] `alerts`
- [x] `programArea` #8837
- [x] `aoj` #8838
- [x] `issues` #9160
  - [x] `active`
  - [x] `lastAction`
  - [x] `date`
  - [x] `description`
  - [x] `diagnosticCode`
- [x] `description` #9161

### Events

- [x] `scRequest`
- [x] `scDecision`
- [x] `scOtherClose`
- [x] `hlrRequest`
- [x] `hlrDecision`
- [x] `hlrDtaError`
- [x] `dtaDecision`
- [x] `hlrOtherClose`

### Current Status

- [x] `scReceived`
- [x] `scDecision`
  - [x] `details` #9162
    - [x] `issues`
- [x] `scClosed`
- [x] `hlrReceived`
  - [ ] `details` #9424 
    - [ ] `informalConference` 
- [x] `hlrDtaError`
- [x] `hlrDecision`
  - [x] `details` #9162
    - [x] `issues`
- [x] `hlrClosed`

### Alerts

- [x] `amaPostDecision` #8840
  - [x] `details`
    - [x] `availableOptions`
    - [x] `decisionDate`
    - [x] `dueDate`
