### ISSUE TITLE
Add ability to cancel tasks in DB

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#8701]
Certain tasks in the appeals process are canceled/resolved/closed rather than completed. Two examples of this are:
- If a Veteran withdraws their hearing request, the Schedule Veteran task is closed
- If a Veteran waives their 90-day evidence window, the 90-day Evidence window is closed

Note: this is different than unassigning a task that was assigned to you, making the top level task back the team queue task, but LP wonders if there is any similarity. 

## Acceptance criteria
* [x] Update `closed_at` timestamp when task is cancelled or completed (PR #9312)
* [x] Add method that does not differentiate between a task being completed successfully and being abandoned in some other way using a new `Task.active?` method (PR #9169)
* [x] Update existing code to use the new `Task.active?` method where applicable (PR #9359)
* [ ] Add backend infrastructure to support cancelling of tasks (PR #9373)
* [ ] Update existing code to set the status to `cancelled` instead of `completed` where applicable (PR #9373)
* [x] Drop the `completed_at` column from the `tasks` table (PR #9181)

**Comment by laurjpeterson** [comment]
Related: https://github.com/department-of-veterans-affairs/caseflow/issues/8701

**Comment by laurjpeterson** [comment]
@MeredithStewart - add thoughts/use cases here!

**Comment by MeredithStewart** [comment]
The ability to make a note on the cancelation action would be helpful here. I imagine a note different than the task instructions - since task instructions are for the task you are trying to complete. For hearings, a note that could be added if you cancel the task for schedule Veteran so that you could say, "Mail dated XX/XX/XXXX from Veteran cancels hearing request."

**Comment by laurjpeterson** [comment]
Another type of canceling:
- Veteran files a motion for reconsideration. This is a task type
- Veteran withdraws that motion for reconsideration. 
- BVA user would need to cancel the Motion for Reconsideration task. BVA user would likely want to add a note to explain why the task was canceled. Task instructions field likely works here

**Comment by lowellrex** [comment]
SMALL - don't forget tests!

**Comment by lowellrex** [comment]
MEDIUM overall, SMALL rollover. Specific requests around cancellation scenarios will be re-written in more tightly-scoped tickets.
