### ISSUE TITLE
Removing and withdrawing appeals

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#8936]
## Background/Context
Veterans can choose to withdraw legacy or AMA appeals. Since the Veteran is withdrawing, there is no Board decision on this appeal. This means there should not be any decision issues.

BVA currently has a hardship case needing immediate action. The homeless Veteran has a RAMP appeal in the hearing lane. He wants to withdraw his appeal and file a supplemental claim instead. This is definitely allowed under AMA - the Board need to withdraw the current Board appeal, and then create a new EP/intake the supplemental claim. 

## Idea
- Allow users to Withdraw request issues on the Add/Remove issues screen, similar to how we currently allow them to Remove request issues. 
   - For example, in a dropdown next to the issue, the user could choose remove or withdraw. Or, another icon next to the Remove trashcan icon. **Design needed**
   - Withdrawn request issues is kind of like a type of removal. Removed issues can be intaken again in another lane. 
- If all issues are withdrawn, Caseflow closes all open or on hold tasks on the appeal. These two parameters indicate that the _entire _appeal is withdrawn. 
  - Note: this may require Caseflow having the ability to close tasks (instead of completing them). Spec to be worked on by Foxtrot this sprint: https://github.com/department-of-veterans-affairs/caseflow/issues/8701)
- If all issues are withdrawn (and all tasks closed), surface a user-facing error message explaining that the entire appeal is now withdrawn. **Design needed**
- If the user makes a mistake, they can re-add the issue as is done today. **Design needed** How to explain to the user that they can add the issue back in if they made a mistake?
- Show withdrawn request issues on the Add/Remove Issues page like we do for ineligible issues, but grayed out (**Design needed**). Include the date that the request issue was withdrawn. 
- Withdrawn issues do not show in Case details or any check out flows.

### Other considerations
- Search results: when a user searches for a withdrawn appeal. If all issues are withdrawn, update `Assigned to` column in Search results to withdrawn?
- Case timeline: add a withdrawn event?
- 

## Additional thoughts
If we like this idea, taking actions on Request issues, this pattern could apply to other scenarios. These scenarios have not been fully explored yet, and likely require a working session. 

1. **Erroneously docketed appeals** - when an appeal was incorrectly established. 
   - Currently, we are deleting these from the database, but need a long term solution (https://github.com/department-of-veterans-affairs/caseflow/issues/8824)
   - Idea: If all issues are removed, then prompt the user to close the appeal.

2. **Stayed issues/appeals** - Sometimes, issues are stayed because they are waiting for a decision from CAVC. Individual issues could be Stayed, and entire appeals can be Stayed.
   - Idea: Add Stayed as an option for Request issues (in addition to Withdraw and Remove). If all issues are Stayed, all tasks for the appeal should be on hold. 

## Resources
- [Withdrawing appeals mural](https://app.mural.co/t/workqueue2001/m/workqueue2001/1548889159757/34048ec08c834eef58e891133c852659163462d6)

**Comment by carolaponce** [comment]
Questions: who is the user withdrawing the veteran? a caseflow assistant? how does the user receive a request to withdraw issue?  I'm happy to chat and brainstorm.

**Comment by cmgiven** [comment]
Can you say more about how this would look from a data perspective? Is "withdrawn" recorded as a disposition on the request issue? Or something else?

Overall, this makes sense to me.

**Comment by laurjpeterson** [comment]
Also tagging @nicholasholtz @MeredithStewart @amprokop @lowellrex @mdbenjam @sharonwarner and @aroltsch for any feedback they might have. (No worries if no feedback, tagging for visibility as well)

will aim to set up a discussion about this on Friday, 2/1 for those who are interested.

**Comment by laurjpeterson** [comment]
@carolaponce i added notes to your mural!

**Comment by steve-gov** [comment]
Assigning myself to break down into issues.

**Comment by laurjpeterson** [comment]
Notes:
- decision made: this should live on the request issue level:
- decision made: fields needed (naming tbd):
   - request_issue_closed_at date
   - request_issue_closed_status
       - withdrawn
       - stayed
       - decision_made
       - canceled/removed
- do we need anything on the appeal level?
- short term solution
   - just go forward and soft remove these issues in intake
   - re-intake for supplemntal claim
   - get case details link
- who are our users?
   - withdrawal as a step one, then switching dockets. so bva intake users will use this feature

Next steps:
- @carolaponce - research with rachel, learn who users would be, research with users
- sierra team - incorporate this into regular development process

**Comment by steve-gov** [comment]
UI issue: #9178

**Comment by laurjpeterson** [comment]
Progress 3/29:
- Sierra is implementing according to this order of operations:
  1. Remove issue by issue
  2. Withdraw issue by issue
  3. Global withdrawal and removal
  4. Handle stayed issues 

<img width="361" alt="Screen Shot 2019-03-30 at 12 03 19 PM" src="https://user-images.githubusercontent.com/27704093/55278530-d8364580-52e3-11e9-9d43-558a30532305.png">

**Comment by allyceh** [comment]
Jumping in to weigh in on some of the Queue open questions. 

1. What happens to the issues section of case details?
*Withdrawn/removed issues*
- If we stick to our current modal where the issues on the Case Details page are the issues on appeal + the issues that need review, we would not display withdrawn or removed issues on the Case Details page. The user would see any withdrawn or removed issues when they access the "Correct issues" flow. This echoes discussion from the "Intake-Withdrawing appeals" Mural. 
*Stayed issues*
- A stayed issue is still an issue on appeal. We should display a stayed issue on the Case Details page since it will be worked once the stay is removed. Since a request issue is stayed (as opposed to a decision issue, which is visually treated differently), I am proposing that we display stayed like this, below: 
One issue stayed, BVA hasn't issued a decision
<img width="456" alt="Screen Shot 2019-04-04 at 1 51 21 PM" src="https://user-images.githubusercontent.com/40216950/55577110-c5a37e00-56e0-11e9-8a40-67f1287054e4.png">
One issue stayed, BVA made decision on other issue (question: can this scenario even happen)?
<img width="459" alt="Screen Shot 2019-04-04 at 1 51 28 PM" src="https://user-images.githubusercontent.com/40216950/55577112-c9370500-56e0-11e9-9b0b-290f076ae57f.png">

2. How does this affect the attorney-judge checkout flow?
- "Stay" is currently a disposition option in our attorney-judge checkout flow. Our validations require that judges and attorneys add a "description" to the decision issue before they save it and send the case to their judge. If stays won't be treated as decision issues, users wouldn't need to add anything to the description field. 
- We could also take "stay" out of the attorney-judge checkout flow and add an action in the actions drop-down that says "Issue stay". This could take attorneys through a checkout flow where they select the issue(s) they want to add stays to. Once they complete the checkout, the case could be put on hold or sent to the next person who needs to draft correspondence to the Veteran, etc. 

3. What task do we create so that a dismissal is distributed to an attorney/judge?
- The names "Draft dismissal" (attorney task) and "Sign dismissal" could mesh nicely with "Draft decision" and "Sign decision", which are the two proposed task names and timeline labels for decision writing. This would make it clear that it's a dismissal letter rather than a typical decision letter. 

4. What notification/labels should we show everyone who was working the case?
*All issues are withdrawn. Case doesn't need to be worked anymore and all tasks are cancelled*
To start, what if the case automatically moves to the "Completed" tab of users' Queues and we display "Appeal withdrawn" in Case Timeline? When we re-visit the timeline design, we could style this differently. Case timeline deserves some more love. 
<img width="551" alt="Screen Shot 2019-04-04 at 3 01 38 PM" src="https://user-images.githubusercontent.com/40216950/55581385-b6c1c900-56ea-11e9-936c-c5418785213c.png">

**Comment by MeredithStewart** [comment]
@laurjpeterson -- Just a point of clarification for flow on withdrawn appeals  - I thought these do get a distributed to judges to write the dismissal. Just want to make sure this is accounted for.

**Comment by nicholasholtz** [comment]
I do not think we would want a dismissed issue to disappear from view on case details. From the Board's point of view (including the attorney and judge in the checkout flow), the dismissal is how they are handling an issue that is appropriately before them.

**Comment by sneha-pai** [comment]
@allyceh @carolaponce @laurjpeterson 

### Provocation design for case search view of global-withdrawn appeal
![status column](https://user-images.githubusercontent.com/31224257/55699110-396eb080-5997-11e9-9cf0-dbe625be22c2.png)

#### Questions:
- Would we introduce a "status column" to display withdrawn appeals (appeals where all issues are withdrawn, either incrementally, or all at once?
- Would we show any other statuses for other appeals? (Active, Withdrawn, etc)

**Comment by allyceh** [comment]
From Rachel, to keep in mind: "When a veteran sends the Board correspondence saying they want to withdraw, sometimes admin staff will mark is as a withdrawal, but they cannot take action on it. It goes the attorney/judge, who decide whether it is a proper withdrawal. If the judge decides that the statement from the vet meets the legal definition of a withdrawal, the judge issues a dissmissal. If the judge decides that the statement isn't really a withdrawal, they will issue a decision on the merits (grant, deny, or remand)."

**Comment by aroltsch** [comment]
There are two more dispositions that should be treated the same way as withdrawn: `dismissed_death` and `dismissed_matter_of_law`

**Comment by laurjpeterson** [comment]
Connected with Jennifer White (BVA RMP/IT) and Rachel Sauter (LRP) this morning:

Confirmed Board policy/processes
- Veterans can send in any notice (napkin, piece of paper, etc.) to withdraw issues or appeals
- Veterans must send in an NOD when they want to switch dockets
- Judges need to send out a decision for withdrawn appeals
- BVA wants to expedite appeal withdrawal decisions

## Development we need to do/confirm is in place
Tagging for awareness, we can determine who does what work 
- Ensure that Case Details shows Request Issue dispositions of withdrawn @sneha-pai 
- Ensure that Case Timeline shows withdrawn appeals @allyceh @sneha-pai 
- Ensure that withdrawn appeals can be automatically distributed to judges through auto-case distribution @cmgiven, @monfresh 
- Change mail task routing logic for withdrawal of appeal tasks to route to BVA Intake instead of VLJ Support (https://github.com/department-of-veterans-affairs/caseflow/issues/7906#issuecomment-440442213)
- Therefore, create a queue for BVA Intake to receive these tasks @lowellrex @carolaponce 

## Training we need to do
- Train BVA Intake team on withdrawal of appeal and switching docket processes @carolaponce @wturne @sneha-pai 
   - [ ] Create deck to walk them through the process
   - [ ] Schedule training on withdrawals and removals
   - [ ] Schedule training on queue

## BVA Rollout
- All BVA Intake users (Case Review and Evaluation Branch) should have the ability to withdraw or remove issues
- All attorneys and judges should have the ability to withdraw or remove issues

**Comment by laurjpeterson** [comment]
![UNADJUSTEDNONRAW_thumb_3f04](https://user-images.githubusercontent.com/27704093/57387816-07fb2780-7185-11e9-85af-f94aa2cd90a7.jpg)

**Comment by carolaponce** [comment]
Our latest training materials for AMA - https://github.com/department-of-veterans-affairs/appeals-training/blob/master/Intake/AMA_training/Intake_training_guide.pdf

I'll connect with @R-Williams7 to review updates.

**Comment by carolaponce** [comment]
Working in training materials, I need clarification.  A withdrawn review will show in queue status.  A withdrawn issues won't, where is that information presented to the judge to finalize the request.  @laurjpeterson

**Comment by laurjpeterson** [comment]
> A withdrawn review will show in queue status
What do you mean by this?

**Comment by carolaponce** [comment]
Whenever there is a withdrawal request for an issue, or many issues, or the entire review, the final step of this process if for a judge to withdraw it. Correct?
A review that has been withdrawn in intake - the status of the case in queue is withdrawn.
**if an issue is withdrawn, but the rest of the issues in the review are still being processed - where does the judge receive this notification to withdraw the issue?**

**Comment by laurjpeterson** [comment]
Created a lot of github issues according to my comment above. 

@carolaponce 
> if an issue is withdrawn, but the rest of the issues in the review are still being processed - where does the judge receive this notification to withdraw the issue?

they will be able to see in Case Details that the request issue has the disposition of withdrawn. 
@sneha-pai is going to finalize designs for #10760

**Comment by laurjpeterson** [comment]
Note to @laurjpeterson - need to create more tickets for removal and withdrawal of entire review. Also take a look at Stayed request issues again.

**Comment by laurjpeterson** [comment]
Met with Maria Braswell, Chief of Case Review/Intake team and Kendra Jones, Chief of Mail Team and gave them an overview of this functionality. 

They need:
- to be added to the Case Review organization
- to be able to get to the Edit Issues screen from Case Details, without having to change the URL - we need to add the Correct Issues link to their Case Details pages

**Comment by laurjpeterson** [comment]
Closing, because I've trained the key stakeholder on this!
