### ISSUE TITLE
Remove action column from tasks table

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#9057]
Currently we use the action column of the task table as a psuedo-class that we use to determine various behaviours. This ticket exists to remove the code's reliance on that column (and as a follow-on to a false start in PR #7686).

Since the `Task.action` field is currently referenced across a broad swath of the codebase, I propose doing this overhaul in a few steps to avoid introducing a mass of changes that cause some bug that would be hard to troubleshoot or undo if we did the whole overhaul at once.

Before we remove the column from the database we can use [the `ignored_columns` Rails method](https://api.rubyonrails.org/classes/ActiveRecord/ModelSchema/ClassMethods.html#method-i-ignored_columns) on the `Task` class to ignore that field to see if any application logic is affected.

## 🚫 Blocked by
* [x] Migrate ColocatedTasks to their respective subclasses #11337
* [x] Remove code with behaviour based on ColocatedTask action field #11526

## Acceptance criteria
* [x] Create named subclasses for the different `ColocatedTask`s currently defined by their action field (#11295)
* [x] Migrate existing `ColocatedTask`s to new subclasses (combination of `type` and `action` fields) (#11337)
* [x] Make sure LegacyTasks are handled properly (#11817)
* [x] Remove references to the `action` field from the codebase
  * [x] Change task type (#11818) - `action` is mostly used as an argument in this workflow.
    * client/app/queue/ChangeTaskTypeModal.jsx
    * app/models/task.rb (same_task_type? function)
    * app/models/tasks/colocated_task.rb
    * app/models/tasks/mail_task.rb
  * [x] `JudgeTask` creation (#11819)
    * app/workflows/judge_assign_task_creator.rb
    * app/models/docket.rb
  * [x] Hearing disposition change workflow - Does not look like this actually needs to change because `action` is only used as an argument in the workflow.
    * client/app/queue/ChangeHearingDispositionModal.jsx
    * client/app/queue/components/PostponeHearingModal.jsx
    * app/models/tasks/assign_hearing_disposition_task.rb
* [x] Ignore the column in the class using `ignored_columns`, deploy code and wait to see if any bugs arise with the column live in production (let folks on bat-team know when this goes out and to bug the person who made the changes if bugs happen) (#11820)
    * app/models/task_pager.rb
    * app/controllers/tasks_controller.rb
* [ ] Remove the `action` column from the database in a migration

**Comment by laurjpeterson** [comment]
I checked off the boxes because #11337 is now done! Is this now blocked by DAS deprecation work because we need to make sure "LegacyTasks are handled properly"?

**Comment by lowellrex** [comment]
> I checked off the boxes because #11337 is now done! Is this now blocked by DAS deprecation work because we need to make sure "LegacyTasks are handled properly"?

I think we're ready to go with this. Planning on putting this on the upcoming sprint!

**Comment by lowellrex** [comment]
Front-end rely on `action` field as well. It should all work with type or label, but confirm that all code related to `ColocatedTask`s works with the removal of the logic based on `action` fields.

```
1 | 
2 | ||
3 | ||||||||
5 | ||
8 | 
```

Estimating this at 3. Could be a 2 because we don't think there is much code on the front-end that depends on the `action` field so that after back-end work is done the ticket is nearly complete. Don't see many issues arising from this removal. Could be a 5 because of complications of deploying, monitoring for bugs, coordinating with bat-team, and overhead of coming back to a ticket you've set aside for a while.

**Comment by jcq** [comment]
FYI, it looks like there are still some cases of this field showing up in factories. I encountered it in the appeal factory (but can't guarantee there aren't other places):
https://github.com/department-of-veterans-affairs/caseflow/blob/master/spec/factories/appeal.rb#L121

**Comment by lowellrex** [comment]
@jcq great catch! Our automated tests did not catch this because we don't use it in any automated tests, only in the seeds and I didn't run `bundle exec rake db:seed` before committing this change, but that reveals the exact problem you're pointing out. Preparing a PR.
