### ISSUE TITLE
Limit queue table view for Field VSOs to tracking tasks tab

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#9757]
#9647 added the ability to easily create `FieldVso`s. This ticket exists to make it so their queue table view only shows the "All Cases" tab and none of the other tabs.

## Acceptance criteria
* [ ] Create new `QueueTab` class
* [ ] Only show the "All cases" tab in the organizational queue view for these VSOs
* [ ] Hide tab when there is only a single tab being shown

**Comment by lowellrex** [comment]
Design team (@sneha-pai @carodew) do y'all have a preference about whether we show a tab or not for queue table views that only have a single tab?

With tab | Without tab
--- | ---
![image](https://user-images.githubusercontent.com/32683958/60821588-d812d500-a171-11e9-9fa6-e6dbca4efa13.png) | ![image](https://user-images.githubusercontent.com/32683958/60821796-3d66c600-a172-11e9-9c07-ddb597f1e0fa.png)

**Comment by carodew** [comment]
hi @lowellrex ! Some context questions – do we expect that these users (VSOs?) will ever see other tabs in the queue table in future iterations? Are there other potential views for these users in which they'd see multiple tabs, or is it and will it only ever be the one tab/view? (also pinging @laurjpeterson in case she has ideas about what the future holds).

**Comment by laurjpeterson** [comment]
@carodew - Based on what we know now, I don't think field VSOs will need to see other tabs because they don't have tasks assigned to them. Field VSOs do not write IHPs like national VSOs do. (It can be confusing because national VSOs, like American Legion, might have people stationed in field offices. But they are different in kind because they do write IHPs.)

**Comment by carodew** [comment]
Makes sense. In that case, I don't think there's any value in showing them one tab, since we're not trying to prime them to expect future tabs to be added, and they're not going to see these tabs in any other part of the interface (so they're unlikely to notice them missing and get confused). So my recommendation would be to go with the 'without tabs' version.

**Comment by lowellrex** [comment]
Sounds good! We'll go tabless!
